### ISSUE TITLE
不知是不是可以做出百度云那样的用复选框加下载按钮来下载？

### ISSUE THREAD

**Issue by joutain** [acgotaku/115#1]
不知是不是可以做出百度云那样的用复选框加下载按钮来下载？

**Comment by acgotaku** [comment]
@joutain 理论上肯定可以的,只不过我选择了实现方式最快的一种而已...

**Comment by joutain** [comment]
如果有时间的话请在后续的版本里面优化吧，这个问题关闭了

Best regards
Zhihao Jiang
