### ISSUE TITLE
chrome下无法使用。

### ISSUE THREAD

**Issue by giveup** [acgotaku/115#10]
![qq20150408-1](https://cloud.githubusercontent.com/assets/2897585/7040292/ed7e19c0-ddff-11e4-84c1-16a4cc77082a.png)
chrome版本 41.0.2272.104 (64-bit)不显示设置按钮，导出按钮，插件版本 0.0.8

**Comment by acgotaku** [comment]
@giveup  你先多刷新试试 然后没有加载的话 看看Console有啥 输出

话说这位 “放弃”君 真是忠实反馈用户啊～

**Comment by giveup** [comment]
console什么也没有
![qq20150409-1](https://cloud.githubusercontent.com/assets/2897585/7061144/4d4d0daa-dec0-11e4-9e1f-78efb780697b.png)

**Comment by acgotaku** [comment]
@giveup  那就多刷新看看？
![1](https://cloud.githubusercontent.com/assets/1191834/7061250/b8cafbcc-dec1-11e4-913f-5b8c9ee92afb.png)
看看这个面板有没有 加载插件

**Comment by giveup** [comment]
@acgotaku 
 禁止缓存重新刷新了。
![qq20150409-2](https://cloud.githubusercontent.com/assets/2897585/7062025/a3403bfa-decb-11e4-9a6e-87a9e0433bd8.png)
console一样

**Comment by acgotaku** [comment]
@giveup  那就肯定加载了才对啊 囧 页面加载什么都不显示？

**Comment by giveup** [comment]
@acgotaku 解决了。。。
进首页，账号下拉回看不到菜单，然后点文件，这时候账号下拉菜单就能看到插件设置，（在这里刷新不会丢失设置按钮）再次回到首页也能看到插件设置，不过刷新之后就会丢失，需要重复刚才的步骤。
问题是依旧看不到导出按钮。
在firefox上，有相当的几率会出现看不到导出按钮菜单。（刷新几次就可以）
另外，建议按钮调整一下位置。会经常挡住右上角的信息
![qq20150409-3](https://cloud.githubusercontent.com/assets/2897585/7062401/7187cd36-decf-11e4-8c3f-1e59a866dff9.png)

**Comment by acgotaku** [comment]
@giveup 你干嘛非要在首页设置啊！ 首页我也不能下载文件啊。。。

我只确保在网盘页面能正常使用，而且也是在网盘页面刷新 

主页跳转到网盘页面那个问题我也知道 也研究过几次 但是那个iframe确实恶心。。

一定几率看不到是因为那个iframe加载的顺序不一致导致的。目前还没比较好的思路。

插件位置问题这个我现在可以解决的。 你为啥要跳转还得保证能用啊  QAQ

**Comment by giveup** [comment]
@acgotaku 我不是挑刺。。firefox上，首页里就能直接设置插件，我的理解是chrome上也一样。。
其实我要求不高。。115限速厉害，却又只能浏览器下载，真心恶心。可以导出到aria2就不用管了。

**Comment by acgotaku** [comment]
@giveup 还是买个VIP省事吧 == 某宝不是20元一年么
