### ISSUE TITLE
看不见下载按钮

### ISSUE THREAD

**Issue by itspig** [acgotaku/115#11]
不过插件设置倒是可见，是我打开的方式不对吗？
![2015-04-27 21 18 42](https://cloud.githubusercontent.com/assets/1708360/7348316/181963f6-ed23-11e4-8bc6-b6b079ca3d01.png)
![2015-04-27 21 18 49](https://cloud.githubusercontent.com/assets/1708360/7348317/18fa8958-ed23-11e4-9315-a357ad13cee3.png)

**Comment by acgotaku** [comment]
@itspig 多刷新几下试试？ iframe加载顺序的问题吧

**Comment by acgotaku** [comment]
@itspig 一般从主页跳转都不会出现。。。网盘页面刷新才会有

**Comment by itspig** [comment]
是的，在网盘页刷新几下就好了，谢谢！
![2015-04-27 22 04 45](https://cloud.githubusercontent.com/assets/1708360/7349129/87a62c62-ed29-11e4-9bc5-1fbaeaffffb5.png)
