### ISSUE TITLE
经常无法加载成功，要多刷新几遍才能加载出来

### ISSUE THREAD

**Issue by lurui45** [acgotaku/115#110]
好几个版本都是这样哦，经常看不到导出的按钮，要刷新很多遍才有机会看到。

**Comment by acgotaku** [comment]
好吧。。。 因为115这个iframe的原因 而且还和网络原因有关 

所以这个BUG一直 迟迟未能搞。。。

**Comment by lurui45** [comment]
thanks for your reply, i like this plugin and use it frequently, but this bug bother me a lot, it will be lots of appreciate if you can fix it, or build it in tampermonkey, in where i found i similar plug-in, but it doesn't work.
