### ISSUE TITLE
aria2下载115失败

### ISSUE THREAD

**Issue by cyz198** [acgotaku/115#111]
我用aria2下载经常遇到出错停止下载的情况，提示是http response header was bad or unexpected，有何解决方法

**Comment by user1121114685** [comment]
我也遇到这个问题，貌似没有解决办法，115只有等作者更新了！！！这个链接直接点击用浏览器是可以下载的！！！

**Comment by acgotaku** [comment]
重新导入就可以了（ 

偶尔失败很正常

**Comment by seven8889** [comment]
现在有这个问题，能下的就肯定可以下载成功，失败的永远是HTTP response header was bad or unexpected，导入重置多少次都没用

**Comment by NepetaLemon** [comment]
依然 HTTP response header was bad or unexpected ，不是特定资源，现在我没有测试到有资源能成功导出到 Aria2 的了。烦请解决一下。

**Comment by novineet** [comment]
试下将aria2的【单任务最大线程】修改到3以下试试。
# 单个任务最大线程数, 添加时可指定, 默认:5
split=3

还有个不知是否有影响的参数，如果这项是true，修改成false试试？没有这项就无视。
enable-http-pipelining=false

**Comment by wyd2004** [comment]
@novineet enable-http-pipelining=false 亲测有效. 多谢,多谢.

**Comment by acgotaku** [comment]
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-enable-http-pipelining

@wyd2004

**Comment by jackdiy** [comment]
发现一个问题，今天突然115导出的链接无法下载了，想问下你们是不是也是100%失败了？我感觉115是不是做了什么手脚

**Comment by Naituw** [comment]
@jackdiy @acgotaku  遇到同样的问题，
测试了下，User-Agent 和登陆的浏览器完全一致时可以正常下载，否则回报 403。

现在最新版本似乎无法动态读取浏览器 UA，只能先从检查器控制台用 `navigator.userAgent` 手动获取到之后填入设置页面里。

**Comment by cbfrank** [comment]
@Naituw 试了一下，果然是这个问题，这样改了以后就又能正常下载了

**Comment by lll113** [comment]
这两天也是不知道为什么chrome能同步到aria2的UI，显示有下载任务，但一直都没有速度，试过很多个不同的下载链接都是一样，不知道为什么呢？

**Comment by freeman02** [comment]
不行，导出到ARIA2直接打X失败。User-Agent改成和浏览器一样也不行。版本1.34.0

**Comment by acgotaku** [comment]
@freeman02 100%出现？

**Comment by jackdiy** [comment]
手动修改User-Agent问题依旧,感觉这个不像是User-Agent的问题,是115改版故意屏蔽了一样?
 HTTP response header was bad or unexpected
各位有成功的其他办法吗?NAS上下载DS肯定不行了,现在就剩115了,迅雷也屏蔽了....

**Comment by freeman02** [comment]
我昨晚更新插件0.3.1已经正常了。

**Comment by jackdiy** [comment]
@freeman02  我刚刚更新问题依旧？请教有没有什么技巧？

**Comment by freeman02** [comment]
@jackdiy 没什么技巧，一更新就可以了。还有就是我是VIP会员，下载满速。

**Comment by jackdiy** [comment]
@freeman02 感谢各位,我已经搞掂了,是群晖NAS上通过Docker安装的Aria2默认参数有问题,希望能帮助后人:
根据上面各位大哥讲的,网上大部分教程里给群晖通过Docker安装的Aria2 是1.32.0版本,同时默认的:
split=10
enable-http-pipelining=true

务必把enable-http-pipelining改为false
建议将split改为5

所以更新到acgotaku的 0.3.1 插件后目前已可以运行,感谢大家

**Comment by kid2323** [comment]
我也是添加任務100% 失敗 
插件是0.3.1  aria2版本不知道從哪看
如圖 https://imgur.com/ZxoOWVh

**Comment by vava24680** [comment]
有成功的大大可以講下如何用嗎
怎麼試都不成功QQ

**Comment by novineet** [comment]
昨天下午6点多还可以下载的，晚上10点的时候，再下就开始失败了。
115Exporter 0.3.1
aria2 1.33.1
chrome 63.0.3239.132

**Comment by iVoldemort** [comment]
我插件版本 0.3.1，群晖 NAS 里 Docker Aria 2 1.33.1。无论是用 @jackdiy 改 aria2.conf 的方法，或是 @Naituw 的手改 UA 方法，亦或是在插件设置里勾选「使用浏览器 UA」与否，目前都必定下载失败：「下载出错 HTTP 请求头错误或者无效.」

**Comment by vava24680** [comment]
感覺是115那邊檢查cookies
正常可以下載的cookies長這樣
![image](https://user-images.githubusercontent.com/21094580/41190338-35a9c6fe-6c0f-11e8-94b7-4ada9e4f729a.png)
但是導出的會變成這樣
![image](https://user-images.githubusercontent.com/21094580/41190341-4a67d0c2-6c0f-11e8-92c0-0ce1ca22baae.png)

**Comment by freeman02** [comment]
是的，今天发现又无法下载了。问题又回到了更新扩展(0.3.0)前的状态。

**Comment by acgotaku** [comment]
Cookies的验证机制变了 明天再看看

**Comment by sbw983** [comment]
@vava24680 你的cookie是怎么查的？

**Comment by user1121114685** [comment]
恩其实我这个问题已经解决了，感谢大佬，感谢各位，现在115没法看小姐姐了！我也很绝望。。。。

**Comment by kid2323** [comment]
大神更新插件 0.3.2 依然不能用 提交任務後  馬上變X
https://imgur.com/W38i5fv

**Comment by acgotaku** [comment]
@kid2323 至少把导出的文本贴出来 这样看也分析不出来结果啊 ==

**Comment by kid2323** [comment]
是這個嗎
http://cdnfhn210.115.com/pBoqyID0AliXdzBB_zbNK5vSRGDUWxBt78KXPSOO/%E6%96%B0%E6%9C%A8%E4%B9%83%E4%BC%8A.The.Mummy.2017.BD720P.x264.%E5%AE%98%E6%96%B9%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.btrenren.mp4?t=1528855824&u=16383857&s=13107200&d=vip-1878605929-chmc6epux7oo3d9pw-1&c=2&f=3&k=c3ca60f906e97cddc94966ae4afa007a

**Comment by acgotaku** [comment]
@kid2323 点击插件的文本导出 然后把显示的文本贴出来 这样我才能分析分析

**Comment by kid2323** [comment]
麻煩大神
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "新木乃伊.The.Mummy.2017.BD720P.x264.官方中文字幕.btrenren.mp4" --header "User-Agent: " --header "Referer: " --header "Cookie: f167c50a6ad12baae3672ab94fe1cef8=193f9e632162393f2ab6ee50859ff816" "http://cdnfhn210.115.com/pBoqyID0AliXdzBB_zbNK5vSRGDUWxBt78KXPSOO/%E6%96%B0%E6%9C%A8%E4%B9%83%E4%BC%8A.The.Mummy.2017.BD720P.x264.%E5%AE%98%E6%96%B9%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95.btrenren.mp4?t=1528930484&u=16383857&s=13107200&d=vip-1878605711-chmc6epux7oo3d9pw-1&c=2&f=3&k=6812f2c2c231eff042e95a6901c6b4a0"

**Comment by lll113** [comment]
同样的出http错误的路过。。。辛苦大大了。

**Comment by yeahfish** [comment]
同楼上http vip会员导出文本链接 复制到下载器里面下载错误 辛苦大大

**Comment by yeahfish** [comment]
链接复制到FDM下载 显示http 403 禁止错误

**Comment by acgotaku** [comment]
@kid2323 可是我测试的是没啥问题的。。。 你重新登录 并清除缓存试试

**Comment by jackdiy** [comment]
0.3.2  VIP会员OK，直接用插件设置好Aria2地址后,点击 ARIA2 RPC即可成功。

**Comment by kid2323** [comment]
大神還是不行 = ="
請問樓上 沒看到 ARIA2 RPC 按鈕 https://imgur.com/sWZZhmk 只有導出下載
如何用插件設置Aria2地址

**Comment by acgotaku** [comment]
@kid2323 你就不知道鼠标点上去 试试么。。。 
我真的不知道说啥好。。。

**Comment by vava24680** [comment]
@acgotaku 可以用了，大神谢谢啊

**Comment by kid2323** [comment]
就只看到這2個 https://imgur.com/0Snu8dH
                        https://imgur.com/IGMoTcr

**Comment by acgotaku** [comment]
@kid2323 这个是因为你用的浏览器太老了吧。。。 
我真的没有那么闲。。。

**Comment by yeahfish** [comment]
@acgotaku 大大 经过测试 直接aria2 rpc 导出下载是有效的 直接文本导出 复制链接到下载器里面都会下载错误 求更新...谢谢

**Comment by netfan** [comment]
由于115调整策略，禁止使用第三方下载器，所以只能用Aria2或eagleget之类能修改“用户代理”字符串的第三方下载器，将“用户代理”字符串修改为提取115直链的浏览器的用户字符串。

**Comment by yeahfish** [comment]
@netfan 能否详细说下如何修改用户字串符

**Comment by netfan** [comment]
首先在115浏览器 地址栏中 输入 Chrome://version ， 在页面上将“用户代理”后面的字符串复制下来，然后填入Aria2或者Eagleget的“用户代理” 的文本框中，保存起来。之后提取的115直链就能正常下载了

**Comment by netfan** [comment]
aria2和wget能下，说明用户代理字符串设置是正确的，axel报错，则要检查用户代理字符串的设置与提取115直链的115浏览器的用户代理字符串是否一致。你可以把提取的原始115直链，用eagleget测试一下，看看链接日志。

**Comment by sbw983** [comment]
wget,aria2和axel用的是相同的User-Agent和Cookie值以及url，wget和aria2正常，axel报错403，奇了怪了。以前一直习惯文本导出后用axel直接下到目标目录下，使用下来感觉axel一直比aria2稳定，就习惯用axel了。

**Comment by netfan** [comment]
你把提取的115原始直链 发来 我用axel和eagleget测试一下

**Comment by sbw983** [comment]
aria2c -c -s10 -k1M -x16 --enable-rpc=false -o
"Memphis.Belle.1990.1080p.BluRay.X264-AMIABLE.mkv" --header "User-Agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36" --header
"Referer: https://115.com/" --header "Cookie:
a86efe8890a2b1e7ca1825c25b12b18d=28ba31ee27b796457fd3ec47a0810698" "
http://cdnfhn202.115.com/NCMMtP5AB6WjDRCkrtM722n_eIg6jjFBZnQGBOEM/Memphis.Belle.1990.1080p.BluRay.X264-AMIABLE.mkv?t=1530740791&u=60567188&s=13107200&d=vip-1927260265-cu1l73d8h0p8ndmjg-1&c=2&f=3&k=f1462d7e309573a4272042d699576f56
"

上面是导出的信息，用wget和aria2导出下载正常，浏览器直接下正常，axel报错403，我没有eagleget，没试过

**Comment by netfan** [comment]
你提供的下载直链 中的 User-Agent字符串不是115浏览器用的字符串，因此无法下载，先在谷歌浏览器中安装User-Agent Switcher，然后设置 用户代理字符串为：Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 115Browser/9.0.0  并切换至115浏览器用户代理字符串，再提取115下载直链

**Comment by sbw983** [comment]
好的，谢谢

**Comment by sbw983** [comment]
UA要和登录使用的浏览器一致才行，如果要套用你的UA就得伪装

塞北的雪 <notifications@github.com> 于 2018年7月6日周五 11:24写道：

**Comment by vava24680** [comment]
請問各位大大，在aria2.conf里面设定user-agent是这样设定吗?
![image](https://user-images.githubusercontent.com/21094580/42421975-f5291f4e-8310-11e8-8cbf-9f4581d671c8.png)
因為設了之後使用文本导出的下载链结都无法使用

**Comment by netfan** [comment]
user-agent不用在aria2.conf中设定，直接登录Aria2 WebUI管理界面，在全局设置中设定即可，这样更方便。

**Comment by mslugyfw** [comment]
@wyd2004 
群晖上的aria2，改成 spilit=3 , enable-http-pipelining=false 就可以下载啦， 早点找到这个帖子就好了。
感谢。

**Comment by Annihilater** [comment]
以上讨论纯属扯淡！
刚买了百度云超级会员，aria2 100m 全速彪起！
关键时刻还是得花钱

**Comment by isslayne** [comment]
> 试下将aria2的【单任务最大线程】修改到3以下试试。
> 
> # 单个任务最大线程数, 添加时可指定, 默认:5
> split=3
> 
> 还有个不知是否有影响的参数，如果这项是true，修改成false试试？没有这项就无视。
> enable-http-pipelining=false

这个有效！

**Comment by snowman** [comment]
NICE!!! 

I have `enable-http-pipelining=true` in my `aria2.conf` file, now it has full download speed support!!!

**Comment by snowman** [comment]
> 我测试过了，axel 不支持带空格的用户代理字符串，换其他下载器吧

https://github.com/axel-download-accelerator/axel/issues/161#issue-326025631
