### ISSUE TITLE
115 改版後介面顯示異常 

### ISSUE THREAD

**Issue by kid2323** [acgotaku/115#115]
如題 已經好幾天了
特來求助大神~
現在情況是這樣  https://ibb.co/mbr6M7
我系統是xp 跟朋友借電腦win7 就正常
所有文件看不到 離線任務也看不到
請問這還有得救嗎

**Comment by acgotaku** [comment]
@kid2323 大哥 这是XP系统的问题吧 你也该更新到win7 了。。。
