### ISSUE TITLE
115下载重复出现http response header was bad or unexpected

### ISSUE THREAD

**Issue by puredarkff** [acgotaku/115#116]
aria2版本1.33.1（群晖的Docker） 插件0.2.8 Chrome 66.0.3359.139
下载地址aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "StarCraft.II.Nova.Covert.Ops.CHS-ALI213.part02.rar" --header "User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3" --header "Referer: https://115.com/" --header "Cookie: UID=340197704_A1_1525518780; CID=089c1d843c7f669ba837c6c66ef1277c; SEID=b2eb7d24d8dc577d9e27a63a5f74e993759ffb7cb47010816ca3fc277bb1f92bb69d729b13927879f2aefd319d2d017cdd47687ab3aeb36f30ec7547" "http://cdnfhn302.115.com/kClqfpRpBB3z1JCVqQf2onjy9KKPh04nEhWjAMPE/StarCraft.II.Nova.Covert.Ops.CHS-ALI213.part02.rar?t=1525638863&u=340197704&s=13107200&d=vip-2510891060-b6k0pbkmejls8886w-1&c=2&k=dd4cc5f59f68641f35517a0d26d27411"
总是下载的时候过段时间自动就提示出错了，但是点击重新开始又可以继续下载一段时间，有的文件重试一两次可以下完，大部分文件需要反复重新点击，百度云的插件下载也是这样。
但是这个用IDM下载就没什么问题
试着改改配置什么的加入check-certificate=false等等都没有什么用，试了好久了实在没有办法了TAT

**Comment by acgotaku** [comment]
用 IDM下载就没啥问题  说明插件本身的导出是没啥问题的。。。

很多情况下是和自己网络环境有问题  以及aria2c的配置

所以这种情况下 我也无能无力  不是代码可以修复的地方

**Comment by puredarkff** [comment]
网络环境是一样的啊，能帮我看看配置有什么问题吗？

> dir=/data
input-file=/conf/aria2.session
on-download-complete=/conf/on-complete.sh
save-session=/conf/aria2.session
#save-session-interval=60


file-allocation=falloc
log-level=warn
enable-http-pipelining=true

max-concurrent-downloads=16
max-connection-per-server=5
min-split-size=10M
split=10
continue=true
max-overall-download-limit=0
max-overall-upload-limit=1K
max-tries=0
timeout=240
connect-timeout=240
lowest-speed-limit=2k
retry-wait=5

check-certificate=false
enable-rpc=true
rpc-listen-all=true
rpc-allow-origin-all=true
rpc-listen-port=6800

**Comment by acgotaku** [comment]
这个问题我看配置也看不出啊  每个人的网络环境都不一样。。。

**Comment by snowman** [comment]
`enable-http-pipelining=true` 改成 `enable-http-pipelining=false`
