### ISSUE TITLE
出现重复下载情况

### ISSUE THREAD

**Issue by jeremy1991310** [acgotaku/115#117]
这两天才出现的问题，导出下载选择Aria2 RPC之后，发现Aria2那边每个任务出现了两个，即每个任务都重复下载了。
导出下载选择文本到处会弹出复制文本的对话框，同时Aria2那边开始下载，任务没有重复。
不知道是什么情况

**Comment by acgotaku** [comment]
你是不是装了两次插件？ 一个开发版 一个Chrome商店版本？

**Comment by jeremy1991310** [comment]
只装了一个商店版，没装过开发版，不过看到这个回复突然想到，去删除了插件从商店重新安装了一次，又正常了……
没搞明白为什么

**Comment by brucmao** [comment]
我也遇到了，勾选多个视频文件，选择导出下载-Aria2 RPC 会出现重复下载的情况，
