### ISSUE TITLE
15rMBP上按钮位置显示正常，但是13rMBP上按钮与原生按钮有重叠

### ISSUE THREAD

**Issue by poplarch** [acgotaku/115#12]
详见图片
![qq20150511-1 2x](https://cloud.githubusercontent.com/assets/153857/7564553/6acad9c0-f81a-11e4-9264-449b00a10fce.png)
![image](https://cloud.githubusercontent.com/assets/153857/7564641/74b6266e-f81b-11e4-8e29-12386ad7bb81.png)

**Comment by acgotaku** [comment]
@poplarch 楼主快送我一台Mac 我来调试 QAQ

**Comment by acgotaku** [comment]
@poplarch 0.1.2版本已经解决了这个问题

**Comment by poplarch** [comment]
还是有点小问题…
![image](https://cloud.githubusercontent.com/assets/153857/8053243/3448b58a-0ec1-11e5-9ac2-48f6534249c6.png)

**Comment by acgotaku** [comment]
@poplarch 因为空隙很小啊 QAQ  我又不好监听click事件 要不我做成半透明？

**Comment by poplarch** [comment]
这样其实也可以了…我close吧，强迫症go to hell
