### ISSUE TITLE
115网页界面更新，插件无法使用了~

### ISSUE THREAD

**Issue by wzymmy** [acgotaku/115#120]
有时间的话更新下吧~

**Comment by jeremy1991310** [comment]
今天突然发现更新了，不但插件不能用，正常用也更麻烦了

**Comment by tony1016** [comment]
同样期待

**Comment by zeroxia** [comment]
今天也发现了。现在无法用Exporter，暂时用这个：`Aria2c Integration`，单个文件选择VIP下载，就可以用Aria2接管。

[https://chrome.google.com/webstore/detail/aria2c-integration/cnkefpcjiolhnmhfpjbjpidgncnajlmf](https://chrome.google.com/webstore/detail/aria2c-integration/cnkefpcjiolhnmhfpjbjpidgncnajlmf)

**Comment by acgotaku** [comment]
更新了 等0.2.9版本吧

**Comment by wzymmy** [comment]
大佬反应迅速w好评w

**Comment by wzymmy** [comment]
更新后正常试用中w

**Comment by jeremy1991310** [comment]
@acgotaku
更新后可以导出了，但是经常会遇到一种情况
就是鼠标停留在导出下载按钮上弹出菜单ARIA2 RPC，文本到处，设置
但是准备去点这三个选项，鼠标离开导出下载按钮的时候，弹出菜单就消失了

**Comment by acgotaku** [comment]
@jeremy1991310 这个问题我也看到了 当时更新的快 偶尔也能触发 就没管
