### ISSUE TITLE
请问如何把这个插件 安装到浏览器 小白求指点

### ISSUE THREAD

**Issue by ylyjack** [acgotaku/115#122]
是下载zip解压后 用浏览器打包拓展程序吗？我一打包就提示

无法为内容脚本加载 JavaScript“js/start.js”。

用的是360极速浏览器

本人小白 不懂 希望作者和大家能指点下 感谢！

**Comment by acgotaku** [comment]
装个 Chrome  然后商店安装

**Comment by ylyjack** [comment]
谢谢老大 因为国内打不开谷歌商店 找了个vpn才下到，希望老大能以后更新时顺带发下crx，谢谢老大

**Comment by acgotaku** [comment]
这个不好说。。。 因为我发完就睡觉了 想不起来更新CRX。。。
