### ISSUE TITLE
请提供一下新版的crx文件。

### ISSUE THREAD

**Issue by lll113** [acgotaku/115#123]
谢谢，之前的失效了，国内都打不开google的链接，麻烦提供一下crx的直接下载链接。谢谢。

**Comment by lll113** [comment]
之前是在您的release里面找到的。https://github.com/acgotaku/115/releases，但这里没有新版，能提供一下新的吗。谢谢。

**Comment by acgotaku** [comment]
CRX更新的比较慢 稍微等下吧
