### ISSUE TITLE
与Aria2 1.33.1兼容性问题

### ISSUE THREAD

**Issue by Fengyao115** [acgotaku/115#125]
0.3.0版本使用 aria-rpc 导入Aria2 1.33.1版本时提示HTTP  response header was bad or unexpected，使用1.18.8版本时无此问题

**Comment by inikkidoll** [comment]
我也遇到这个问题了，我的aria 2显示也是1.33.1版本的，就前两天下午突然就不能再添加任务了，添加都显示错误

**Comment by acgotaku** [comment]
那就换个版本就是了。。。 这个基本上不会是插件的问题

**Comment by pinoyo** [comment]
原来不止我一个人有这个问题“http请求头错误或无效”，今天研究一天了，我路由固件里只有1.23，无法换版本。

**Comment by pinoyo** [comment]
不过作为惭愧的伸手党，还是感谢雪神长久以来的贡献。

**Comment by Fengyao115** [comment]
谢谢，那就暂时使用旧版本好了
