### ISSUE TITLE
aria2无速度

### ISSUE THREAD

**Issue by lll113** [acgotaku/115#129]
这两天也是不知道为什么chrome能同步到aria2的UI，显示有下载任务，但一直都没有速度，试过很多个不同的下载链接都是一样，不知道为什么呢？不知道其他朋友有没有问题呢？

**Comment by donglin2000** [comment]
我是直接报错，aria2的日志显示返回的是403。估计是115升级了，最近两天连115fake也不好使了。

**Comment by lll113** [comment]
@acgotaku 看到您前两天又更新了新的文件，不知道能否做个crx放在release里面让我们下载呢？谢谢。

**Comment by acgotaku** [comment]
@lll113  https://github.com/acgotaku/115/releases/tag/v0.3.1

**Comment by lll113** [comment]
谢谢，已经下载安装了，但又出现了另一个问题，在115页面的“导出下载”-》设置里面，完全按照之前的填写内容，然后“测试链接”那里点击会出错，显示“错误，请查看是否打开aria2”，但我已经确认已经打开了，而且用命令行grep有，然后在aria2的UI也能显示连接成功的。不知道是为什么呢？

**Comment by acgotaku** [comment]
@lll113 先重置下试试吧 必须保存后再点击

**Comment by lll113** [comment]
@acgotaku已经全都试过了，都不行。。。真奇怪

**Comment by lll113** [comment]
@acgotaku我的aria2版本：1.33，不知道是否因为没有更新有1.34而出问题呢？

**Comment by acgotaku** [comment]
已经更新了

**Comment by lll113** [comment]
谢谢，麻烦在release那里放个crx文件。谢谢。

**Comment by lll113** [comment]
@acgotaku麻烦更新一下新的crx文件到release。谢谢。

**Comment by acgotaku** [comment]
@lll113 https://github.com/acgotaku/115/releases/tag/v0.3.2 自己也学学翻墙吧
