### ISSUE TITLE
chrome下第一次不出现

### ISSUE THREAD

**Issue by Hasset** [acgotaku/115#13]
不是首页不出现，是点击文件后仍然不出现。
**必须**刷新后才出现，每次都这样，不方便。

**Comment by acgotaku** [comment]
@Hasset 这个BUG早就存在了 看来确实得修复了  QAQ

**Comment by acgotaku** [comment]
@Hasset 更新了 你看看

**Comment by Hasset** [comment]
@acgotaku 速度好快，抓紧测试了一下！

1、第一次进入云盘文件里，能不刷新就看见了，这个问题解决了！谢谢！
2、从离线文件里，点击下好的文件进入云盘文件夹后，仍然不可见，望修复！谢谢！

**Comment by acgotaku** [comment]
@Hasset 第二个也修好了！

**Comment by Hasset** [comment]
@acgotaku 测试成功！极好！:D

**Comment by acgotaku** [comment]
@Hasset 那你倒是关了这个  issue 啊！QAQ
