### ISSUE TITLE
Aria2失效

### ISSUE THREAD

**Issue by acshmily** [acgotaku/115#131]
Aria2RPC调用115的资源地址显示403

**Comment by zlhdd108** [comment]
确实是提示403了，貌似115迁到阿里云了？？？难道跟这个有关？？？
![image](https://user-images.githubusercontent.com/16465666/41164540-002ef46e-6b6e-11e8-91f9-4c49def50de7.png)

**Comment by IsoaSFlus** [comment]
同403,凉凉QAQ

**Comment by acshmily** [comment]
猜测应该是检测UA以及cookie了..

**Comment by tony1016** [comment]
same,same a

**Comment by jeremy1991310** [comment]
HTTP response header was bad or unexpected
……

**Comment by FPG-Alan** [comment]
我也遇到这个问题报错
`HTTP response header was bad or unexpected `

**Comment by simmy2001** [comment]
same problem

**Comment by acgotaku** [comment]
知道了， cookies机制更新了而已 等下个版本

**Comment by acgotaku** [comment]
更新了

**Comment by acshmily** [comment]
非常感谢您

**Comment by tony1016** [comment]
支付宝来一个，buy you a coffee

acshmily <notifications@github.com> 于 2018年6月10日周日 下午7:27写道：
