### ISSUE TITLE
115中配置的插件下载路径不起作用啊

### ISSUE THREAD

**Issue by zjz894251se** [acgotaku/115#133]
115中配置的插件下载路径不起作用啊，到底应该怎么配置呢？
/data/a
这种的不行啊
环境chrome + xujinkai-aira2-with-webui

**Comment by acgotaku** [comment]
测试 是可以的 必须绝对路径 你自己环境 或者权限没弄好吧

**Comment by zjz894251se** [comment]
下载没问题
我用的是docker 版的 xujinkai/aria2-with-webui  地址：https://hub.docker.com/r/xujinkai/aria2-with-webui/
指定二级文件夹不行，文件夹创建了，但是没有放到二级文件夹下面，全部放到了map过的/data文件夹下面了，不知道怎么回事，难道我用的这个版本有问题？

**Comment by acgotaku** [comment]
@zjz894251se 这个问题 你就应该问开发docker的那个人啊 我没有这个义务给你测试啊？

**Comment by zjz894251se** [comment]
好的，谢谢，不是让你帮我测试的，我只是想问下你知道问题出在哪了不知道，叨扰了，多谢！！！
