### ISSUE TITLE
IDM下载显示 403 没有权限下载此文件

### ISSUE THREAD

**Issue by ODtian** [acgotaku/115#134]
用文本导出功能获得下载地址，所有下载器都下载不了，aria2下载到40%多就错误

**Comment by 990721830** [comment]
应该是需要cookies了....单个下载idm可以下载的......

**Comment by netfan** [comment]
由于115调整策略，禁止使用第三方下载器，所以只能用Aria2或eagleget之类能修改“用户代理”字符串的第三方下载器，将“用户代理”字符串修改为提取115直链的浏览器的用户字符串。
