### ISSUE TITLE
点击rpc下载后，先提示下载成功，1秒后提示下载失败，实际上仍然下载成功

### ISSUE THREAD

**Issue by liangxyz** [acgotaku/115#136]
插件版本0.32 浏览器 百分浏览器 3.4.3.39 系统win10 1804
点击rpc下载，然后弹出提示，下载成功，1秒以后，紧接着就弹出提示下载失败，是不是没有开启aria2c。
然后我打开webui，发现下载任务正常添加

**Comment by acgotaku** [comment]
非Chrome浏览器 不予官方支持
