### ISSUE TITLE
问题！？

### ISSUE THREAD

**Issue by SilverTiTan** [acgotaku/115#138]
在打包扩展程序时 提示：无法为内容脚本加载 JavaScript“js/start.js”。和无法加载logo_16的图片。 大佬如果看到请回复 谢谢 红包感谢哦！ @acgotaku

**Comment by qwt2003** [comment]
清单文件路径不正确，不过解决起来没啥用，你把src文件夹下的三个文件夹移动到根目录就会发现报找不到css/style.css文件。目前0.3.2版本要想使用可以按照我提出的那个方法来试试。不过目前测试aria2不能下载115的文件，添加任务会提示http head 错误。

**Comment by SilverTiTan** [comment]
qwt2003 你说的没错 那我把清单文件引用的css/style.css那一行去掉可以吗 （个人觉得不行 但还是要问问） 你是在哪里提出的方法呢？？ @qwt2003 @

**Comment by qwt2003** [comment]
@SilverTiTan 应该是不行，因为style.css应该是在网页框架内确定按钮位置这些东西的样式表，没有这个的话插件应该是没法工作的，我的那个方法就写在issues里了，叫无法加载

**Comment by SilverTiTan** [comment]
我看到了 但你在里面又说道要作者提供的crx文件 这个crx文件不就是打包扩展程序获取到的吗 我现在是无法打包扩展程序 提示之前说到的一些问题 @qwt2003

**Comment by qwt2003** [comment]
@SilverTiTan 不是，你在作者的code->release里可以找到作者打包好的crx文件

**Comment by qwt2003** [comment]
@SilverTiTan 我刚刚在win下测试了，提取了插件之后在win用115浏览器在aria2中下载没有问题，但是mac不行..很奇怪...

**Comment by SilverTiTan** [comment]
好吧 我也不懂这些 对了 你qq或vx能说下吗  我加完115后就不知道怎么设置了 @qwt2003

**Comment by acgotaku** [comment]
本项目 官方下载渠道 是使用 Chrome Web Store 目前还没提供开发模式
如果有编程经验的当然可以使用 `npm run build`来获取生成的目标文件
