### ISSUE TITLE
aria2下载偶尔403错误 偶尔无速度

### ISSUE THREAD

**Issue by ODtian** [acgotaku/115#139]
有没有办法提升下成功率

**Comment by acgotaku** [comment]
目前没有完美的办法

**Comment by overfirmament** [comment]
我修改了aria2.conf這幾個選項後就沒403錯誤或者aborted/incomplete了 無速度這個倒是時有時無...
max-connection-per-server=1
split=1
max-file-not-found=65536
max-tries=0
retry-wait=1
