### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by zjsywcc** [acgotaku/115#14]
我直接用的js 发现要把@include的网址改成115.com才生效 但是chrome拓展manifest.json里的match的网址是*://*.115.com/* 为什么还可以匹配到115.com 而我在本地把插件的配置文件乱改了还是能匹配到115.com 这是什么原理 ？ 对chrome插件不了解 见谅。。

**Comment by acgotaku** [comment]
@zjsywcc 不推荐单独使用 JS 匹配机制应该是不一样的 本地修改的话 联网应该还会重新加载好的

**Comment by zjsywcc** [comment]
*.115.com 是匹配的u.115.com吗

**Comment by acgotaku** [comment]
@zjsywcc 包含那个子域名
