### ISSUE TITLE
无法加载文件

### ISSUE THREAD

**Issue by qwt2003** [acgotaku/115#140]
额，不知道作者能不能看见，目前不知道什么原因，在git上下载的zip文件解压缩后在115浏览器内安装会提示找不到清单文件，或者是找不到logo16.png文件；crx版本会提示crx_version_number_invalid问题，经过折腾，问题解决，希望作者能够注意以下这些问题。

一、已知问题
1.目前115浏览器用的chrome内核版本是54.0.2840.59，目前最新的chrome webstore 打包的 CRX 的版本号（ CRX 文件偏移量 4 的值）从原来的 0x02 升级到 0x03 了，而老版本内核只能使用02的crx插件，因此在使用作者上传的crx插件会提示crx_version_number_invalid问题。
2.mainfest清单文件中logo16等文件路径已经从原先的根目录移动到scr文件夹下，因此也许需要更新一下mainfest文件？而且mainfest文件中仍然有style.css文件，目前0.3.2版本中已经不存在这个文件了（本人并非专业it人士，只是个有点儿it基础的上班族，如果说的不对麻烦作者别嫌弃）

二、解决方法（暂时）
1.首先在最新的chrome浏览器中安装作者提供的crx文件（**该文件在code->release中可以找到**），然后在chrome://extensions中查看插件ID，接着前往chrome插件存储文件夹：
mac:~/Library/Application Support/Google/Chrome/Default/Extensions
win:自行百度
2.找到相应ID文件夹，打开后拷贝文件夹0.3.2_0（至少我的叫这个名字）至其他地方；
3.删除_metadata文件夹，在115浏览器中打开扩展页面，进入开发者模式，拖拽0.3.2_0，安装成功。

三、其他
目前这个办法只在mac os10.13.5环境中的115浏览器（8.6.4.5）测试成功。

**Comment by qwt2003** [comment]
------
@silveryTiTan，在这
------
补充，按照之前的修改split=3和enable-http-pipelining=false仍然出现http response header was bad or unepected。导出测试连接为：http://cdnfhn200.115.com/8D9z4XHvD5giWkChDpGUO5e4pPnLi_2GUgzJDgGB/%E7%BD%AA%E6%81%B6%E9%BB%91%E5%90%8D%E5%8D%95.The.Blacklist.S01E21.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.BD-HR.1024X576.mkv?t=1531829650&u=5614685&s=13107200&d=vip-1039145090-agq4nvq9nxnclht0o-1&c=2&f=1&k=7e54a19f6356471ad49aa978c6053c9f
@acgotaku

**Comment by acgotaku** [comment]
目前 我也只支持Chrome浏览器啊 别的浏览器不在支持范围
