### ISSUE TITLE
不明白为啥要“读取浏览器历史记录”的权限

### ISSUE THREAD

**Issue by imkaihao** [acgotaku/115#145]
插件需要“Read your browsing history”权限，不太明白为啥需要该权限

**Comment by acgotaku** [comment]
只有读取 cookies的权限 不放心的话 可以读读源代码

**Comment by acgotaku** [comment]
因为有读取 tabs的权限 所以会出现那个提示， 但插件并没有读取其他网站

**Comment by imkaihao** [comment]
明白了👌
