### ISSUE TITLE
按钮位置错位

### ISSUE THREAD

**Issue by sicode** [acgotaku/115#15]
![image 016](https://cloud.githubusercontent.com/assets/3986116/8872477/ef06d46a-322f-11e5-8bbb-ba45e8022861.png)

谷歌浏览器，从谷歌市场里下载安装

分辨率1080P

**Comment by acgotaku** [comment]
@sicode 115 UI又更新了啊  我之后也更新～

**Comment by sicode** [comment]
OK~~更新后正常

**Comment by sicode** [comment]
还有个问题，就是我选中了文件夹，它导出的文件列表会以"文件夹名/文件名"重命名文件

**Comment by acgotaku** [comment]
@sicode 你是什么下载方式？  文件列表是 "文件夹名/文件名" 这样会新建一个文件夹
存放文件 并没有 把文件重命名吧 ？

**Comment by sicode** [comment]
设置好参数后，选中文件夹，直接点RPC下载....不是这样子用的吗？

**Comment by acgotaku** [comment]
@sicode 是 的啊  你的文件 被重命名了的么？ 求截图看看

**Comment by sicode** [comment]
![image 017](https://cloud.githubusercontent.com/assets/3986116/8922813/b37a263e-351a-11e5-9980-32ceaf7fa955.png)

**Comment by sicode** [comment]
后台生成的路径是正常的，那这个标题会包含文件夹名是aria2的问题吗？

**Comment by acgotaku** [comment]
@sicode  资源管理器生成的正常就行 你这个管理界面好别扭  还是用 YAAW吧

https://github.com/binux/yaaw  用过都说好～

**Comment by sicode** [comment]
之前用过YAAW，他那个下载失败或者请求失败很难从界面上看到是哪个连接出错~~

**Comment by acgotaku** [comment]
@sicode  好吧 我来给你 @binux 反馈反馈  话说这个要是没问题就 关闭 issue吧

**Comment by binux** [comment]
一个下载一般不是就一个连接吗？为什么要看哪个连接出错？

**Comment by sicode** [comment]
如果我同时预先排队下载很多个，中间出现网络问题呢？

**Comment by binux** [comment]
你指的是不同的任务吧，失败的任务，在文件名后面有一把叉啊。

**Comment by binux** [comment]
而且完成的百分比也能看出来吧。

![image](https://cloud.githubusercontent.com/assets/646451/8923114/2acfe530-351f-11e5-89e8-5ceaef4362b8.png)

**Comment by sicode** [comment]
那个是成功开始才会有吧？连文件名都还没获取到的话，失败后文件名的标题栏会一片空白
最近更新过了？

**Comment by binux** [comment]
如果是从迅雷导出的，是指定了名字的，那么一开始就带有。

你的意思是，因为文件名为空，看不出失败的是哪一个吗？
不过如果 url 里面不带文件名，看 url 也看不出是什么东西吧。特别是同一个网盘导出的时候。

**Comment by sicode** [comment]
嗯嗯
115导出的URL包含文件名，经过URL编码后还能看得出来是哪个文件，到时候我就可以直接去找这些文件单独下载

**Comment by snowk155** [comment]
![qq 20150801025407](https://cloud.githubusercontent.com/assets/8599522/9015020/9f8d6dee-37f8-11e5-9b7d-7cc1e7cb32e3.png)
下载全是错误，这是为啥啊，百度网盘的倒是正常

**Comment by acgotaku** [comment]
@snowk155  我刚刚测试 一切正常啊

**Comment by liangdl** [comment]
我这里也是百度正常，115下载就会错误

**Comment by acgotaku** [comment]
@liangdl 有没有什么错误输出?

**Comment by liangdl** [comment]
@acgotaku 哪里能看到错误输出？现在只观察到失败时“状态: error”，

**Comment by acgotaku** [comment]
@liangdl 你是在115下载页面出现的失败 还是 aria2的前台看到的失败 具体下载失败的文件可以分享下么?

我可以尝试下载试试 看看情况

**Comment by liangdl** [comment]
@acgotaku 在yaaw的web UI页面看到的，和楼上@snowk155 的情况一样，不是个别文件，是所有115的下载都会有问题，百度插件的就没问题，要文件分享的话，我身份认证还没开。
文件大小: 0 KB (0 @ 1.00 MB)
状态: error
目录: /shares/Public/Downloads
下载进度:

**Comment by liangdl** [comment]
![2015-08-10 10 44 33](https://cloud.githubusercontent.com/assets/2654471/9158632/e9db8eb6-3f4c-11e5-8054-743feef9117e.png)

**Comment by acgotaku** [comment]
@liangdl  你试过 导出下载么? 就是 aria2c的命令行下载方式 

你把导出下载的文本框里面的内容 粘帖出来 给我看看~

**Comment by liangdl** [comment]
aria2c -c -s10 -k1M -x10 -o "Terminator.Genisys.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG.mp4" --header "User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3"  --header "Referer: http://115.com/"  "https://fscdntel-vip.115.com/files/c301/1/cAdTWv81CsKw2IBS51oe74HEWBNfPJctmk7wH-wP/Terminator.Genisys.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG.mp4?t=1439249565&u=vip-2005079309-5551565-cz88gpzw4rhyidzlb&s=104857600&k=0sehI726z5prjFwLA94jJQ"

**Comment by acgotaku** [comment]
@liangdl  你的下载链接居然是 https的....  你把 115的页面 换成 http试试

**Comment by liangdl** [comment]
![2015-08-10 10 49 57](https://cloud.githubusercontent.com/assets/2654471/9158682/9e6a09b6-3f4d-11e5-80f3-a717bf4264e6.png)
这样不是https了吧　，貌似还是不行

**Comment by liangdl** [comment]
@acgotaku aria2c -c -s10 -k1M -x10 -o "Terminator.Genisys.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG.mp4" --header "User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3"  --header "Referer: http://115.com/"  "https://fscdntel-vip.115.com/files/c301/1/cAdTWv81CsKw2IBS51oe74HEWBNfPJctmk7wH-wP/Terminator.Genisys.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG.mp4?t=1439249850&u=vip-2005079309-5551565-cz88gpzw4rhyidzlb&s=104857600&k=gKlUuK-3NchEvnW0dVJFiw"

**Comment by acgotaku** [comment]
@liangdl 明明是http的网页 请求的结果却是  https 我怀疑是其它插件冲突了?

你开隐身模式 然后开启我这个插件在隐身模式也启用试试

**Comment by liangdl** [comment]
@acgotaku 也不行![2015-08-10 10 59 57](https://cloud.githubusercontent.com/assets/2654471/9158789/4f18116c-3f4f-11e5-89e0-2fbde0c75817.png)

**Comment by acgotaku** [comment]
@liangdl 这还真是奇怪 QAQ

**Comment by sicode** [comment]
我也试了下...导出来的是正常的HTTP

**Comment by acgotaku** [comment]
@liangdl  我就不信你点页面上  115官方的下载按钮出来的也是 https的?!

**Comment by liangdl** [comment]
@acgotaku 还真是https的
![2015-08-11 3 52 29](https://cloud.githubusercontent.com/assets/2654471/9182287/75d57776-3fdc-11e5-9109-4090d6ed6700.png)

**Comment by liangdl** [comment]
@acgotaku 安全模式下也一样

**Comment by acgotaku** [comment]
@liangdl 这.... https的能下载么?  感觉 除非你把你帐号给我 否则都不好测试原因 ==

**Comment by liangdl** [comment]
@acgotaku 怎么给帐号你

**Comment by acgotaku** [comment]
@liangdl 因为这个https的加密算法不被 aria2c支持 所以目前只能导出链接 你可以换其它的下载工具下载

**Comment by liangdl** [comment]
@acgotaku 好的，谢谢了

**Comment by ocean521** [comment]
楼主，我也有上述问题。百度网盘可以正常使用，115的话点PRC下载也提示成功，但是AIRA2 WEBUI里面却失败。
![qq 20150820140321](https://cloud.githubusercontent.com/assets/13881865/9376833/c5cdb0da-4744-11e5-817a-fb44cf0c8222.png)
楼主能分析一下么我是115会员。
115的下载链接也是HTTPS 的，
![qq 20150820140625](https://cloud.githubusercontent.com/assets/13881865/9376837/d7a0bfd2-4744-11e5-8afa-b2c152780eeb.jpg)

**Comment by ocean521** [comment]
楼主，我也有上述问题。百度网盘可以正常使用，115的话点PRC下载也提示成功，但是AIRA2 WEBUI里面却失败。
![qq 20150820140321](https://cloud.githubusercontent.com/assets/13881865/9376900/a39ee19a-4745-11e5-8799-1a7d1ca26fe0.png)

楼主能分析一下么我是115会员。
115的下载链接也是HTTPS 的，
![qq 20150820141019](https://cloud.githubusercontent.com/assets/13881865/9376902/a578a802-4745-11e5-9d72-a804ea2ecd62.png)

**Comment by acgotaku** [comment]
@ocean521 https 目前不能用 aria2c下载 可以导出链接 换其它下载器下载 例如 IDM

**Comment by sicode** [comment]
@ocean521 你是怎么启用HTTPS的？我这边一直都是HTTP，每次下载谷歌都弹提示说不安全

**Comment by ocean521** [comment]
没启用啊，就是这样啊，IE浏览器也是这样的

**Comment by ocean521** [comment]
跟COOKIES没关系么,我曾经看过一个软件，好像得用COOKIES

**Comment by acgotaku** [comment]
@ocean521  没关系 部分用户的下载链接确实是 https的 原因不明

**Comment by sicode** [comment]
@ocean521 难道跟帐号有关系？

**Comment by acgotaku** [comment]
@sicode 对的

**Comment by binux** [comment]
aria2 对 https 的报错是什么?

**Comment by acgotaku** [comment]
@binux  https://plus.google.com/u/0/+%E9%9B%AA%E6%9C%88%E7%A7%8B%E6%B0%B4%E9%85%B1/posts/ZhiQWRmF3EL  

参见这个PO

**Comment by ocean521** [comment]
idm支持远程下载么，想在单位操作家里的NAS,另外CHROME的IDM插件有什么用啊。
另外看了一个介绍aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.觉得似乎说可以支持HTTPS啊

**Comment by acgotaku** [comment]
@ocean521   https是支持 只是很不巧 不支持115的证书的加密算法

**Comment by ocean521** [comment]
哦这样啊，那有什么好推荐的呢，我想远程下载115的资源。另外请问YAAW和WEBUI就是两个不同的界面呗，安装方法一样么，可以装一起么？

**Comment by acgotaku** [comment]
@ocean521  YAAW就是单纯的HTML文件 浏览器打开就可以用啦~ 肯定可以装一起啊~

远程下载还真没想到比 aria2c好的东西  迅雷远程?

**Comment by ocean521** [comment]
迅雷还得会员吧，115已经弄了会员，而且资源也不少，其实ARIA2挺好，昨天突然发现它在百度云下载时，都不用保存到自己的网盘，有链接直接下载就可以

**Comment by ocean521** [comment]
YAAW的地址是什么啊

**Comment by acgotaku** [comment]
@ocean521 先用百度吧 要是这个问题很明显 我就去找 aria2c作者 提 issue

**Comment by ocean521** [comment]
谢谢楼主不厌其烦

**Comment by acgotaku** [comment]
@ocean521  http://binux.github.io/yaaw/

**Comment by ocean521** [comment]
那这个呢http://aria2c.com/
我理解是不是得将下载下来的YAAW文件传到NAS的WEB文件夹，和WEBUI一样的位置。

**Comment by acgotaku** [comment]
@ocean521  在线的也可以直接用 输入你的RPC地址就行

**Comment by ocean521** [comment]
没明白，比较小白，是一点点猜的，楼主能说的详细点么

**Comment by ocean521** [comment]
http://aria2c.com/你的意思是在线的呗

**Comment by ocean521** [comment]
似乎明白了 http://aria2c.com/是在线的，WEBUI和YAAW是需要上传到NAS的WEB文件夹后使用的

**Comment by ocean521** [comment]
115那个问题还请楼主分析一下，需要的话我可以提供账户测试，我的QQ 61226271 谢谢

**Comment by binux** [comment]
try this? https://github.com/tatsuhiro-t/aria2/issues/392

**Comment by ocean521** [comment]
看的不是太明白，新版ARIA2会解决这个问题么？

**Comment by sicode** [comment]
@ocean521 binux说的那个好像在6月份的时候已经修复了

**Comment by ocean521** [comment]
怎么将现有的升级呢？

**Comment by acgotaku** [comment]
@binux 那个帖子我也搜到了 不就是说GnuTLS已经支持他提问的那个算法了么?

然后 115的这个还是不支持?  所以说是   GnuTLS 的问题?

**Comment by binux** [comment]
默认编译参数不支持，改个参数重新编译

**Comment by acgotaku** [comment]
@binux 还要重新编译 GnuTLS啊 QAQ

**Comment by g129368** [comment]
一下载就下载了两个一样的文件，请问这个是什么原因
