### ISSUE TITLE
关于115插件导出到IDM配置文件中，出现“你没有权限下载此文件 403错误”

### ISSUE THREAD

**Issue by user1121114685** [acgotaku/115#151]
EMMMM,大佬你没有原来可爱了，我还是更喜欢原来的你。感谢大佬女装出席，并回复。

出现这个问题我对比过可能是以下原因。
`http://cdnfhn306.115.com/6C7gB-95CFe_hhC0sLNHZPaFHLqwhR6G_Qy6NmMD/ThisIsUsS01E02.mp4?t=1534969863&u=308695392&s=13107200&d=vip-和谐号&c=2&f=3&k=dfb601c854301712572fb6e88c0d48d7
user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
referer: https://115.com/
cookie: 8eae6a23b5353f58c2e9dd8cd174fd18=05377169945607344dcc2ef2e8c91606
>`
=======================================
t=1534969863 这个不对，猜想应该是时间问题。正常略过
k=dfb601c854301712572fb6e88c0d48d7  key不对？what估计也是和时间挂钩的。
================================================
除开这个还有2个重要因素
referer: https://115.com/  也许这是其中一个原因，认为算是一个关键原因，403错误经常发生在没有正规签名的https里面。
cookie: 8eae6a23b5353f58c2e9dd8cd174fd18=05377169945607344dcc2ef2e8c91606  这行我没有去提取检验，想来应该关系不大，正确几率较大。

烦请大佬，在看看使用插件导出到IDM文件，再从IDM下载的问题。非常感谢大佬女装回复。

**Comment by acgotaku** [comment]
你这个说话方式我很讨厌 我不女装

**Comment by acgotaku** [comment]
我的 IDM过期了。。。 有能用的IDM提供一下么？

**Comment by acgotaku** [comment]
@shap2zj 这个 RAR被报有毒。。。
