### ISSUE TITLE
导出含有大量文件的时候会有错误

### ISSUE THREAD

**Issue by olol110** [acgotaku/115#154]
导出含有大量文件夹/文件的目录时最后会报错(我试了个200多子文件夹&3000多文件的和一个300多子文件夹&7000文件的都出现这个现象)，然后115要求重新登录，怀疑是115的某些机制，不太确定，有没有可能设置为可以分批次导出呢？？

**Comment by czhu** [comment]
一样的问题 需要一次只导出少量文件 然后暂定一段时间

**Comment by acgotaku** [comment]
你就把文件分小点吧 这个需求不常用 我就不加了

**Comment by olol110** [comment]
好的，了解，多谢！
