### ISSUE TITLE
请问大佬，请问为什么将115的链接导入至aria2后，会出现“HTTP response header was bad or unexpected”的错误，感谢！

### ISSUE THREAD

**Issue by liuyangno1** [acgotaku/115#156]
请问大佬，请问为什么将115的链接导入至aria2后，会出现“HTTP response header was bad or unexpected”的错误，感谢！

**Comment by acgotaku** [comment]
https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf#L52
 
看看配置文件有没有这个选项

**Comment by zjhong** [comment]
我的也有这个问题，不过插件是百度用的，改了52项，问题依旧。

**Comment by canwushuang** [comment]
问题可能在于协议多了set cookies吧。我是采用python模拟请求拿地址。

**Comment by zjhong** [comment]
感觉百度对这类客户端进行了线程限制。小了就没有这个问题了。

**Comment by canwushuang** [comment]
修改home.js 的第xxx行，用.getAllResponseHeaders('Set-Cookie')把data.cookies = cookies 完善一下即可。

**Comment by canwushuang** [comment]
修改home.js 的第xxx行，用.getResponseHeaders('Set-Cookie')把data.cookies = cookies 完善一下即可。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/163

看看是不是这个问题 ？

**Comment by cnngcnng** [comment]
> https://github.com/acgotaku/BaiduExporter/blob/master/aria2c/aria2.conf#L52
> 
> 看看配置文件有没有这个选项
check-certificate这个选项我在webui里无法更改，conf文件里也没有，请问怎么更改为false?
