### ISSUE TITLE
已解决“HTTP response header was bad or unexpected”

### ISSUE THREAD

**Issue by dec2hex** [acgotaku/115#163]
1、直接用115浏览器登录
2、在115浏览器里添加chrome的115扩展程序，具体方法自己百度
3、设置enable-http-pipelining为false，split我默认还是10，改成3的话跑不满宽带
4、user-agent插件自动在115浏览器里获取，无需再修改

ok，问题解决

**Comment by CaiPeterCai** [comment]
Chrome也可以，user-agent在浏览器里自动获取，referer也不改即可使用
https://github.com/kkHAIKE/fake115

**Comment by zzzop** [comment]
我连接数一直都只有两个，速度大概2MB/s，50M网络，aria2配置这两个参数也一样

**Comment by twinfishxixi** [comment]
> Chrome也可以，user-agent在浏览器里自动获取，referer也不改即可使用
> https://github.com/kkHAIKE/fake115

今天好像又不行了，我是ubuntu 18.04.1，Chromium 版本 70.0.3538.77，通过fake115可以顺利采用用户名/密码方式登录，user-agent在浏览器里自动获取改不改referer都无效，同样出现“HTTP response header was bad or unexpected”错误，不过没有在google chrome上测试，等会儿下载一个再测试一下！

**Comment by BrianLu765** [comment]
Chrome配合fake115的方法现在解决不了这个问题，有些不情愿用115浏览器，不知道还有没有什么别的解决办法

**Comment by YLaido** [comment]
请问有办法在出现此错误之后retry吗？很多时候都是下到一半报这个错，手动重试就会解决。但毕竟人手操作很麻烦。。

**Comment by acgotaku** [comment]
我也不知道他 啥时候出错啊 所以只能你自己手动 重试了 我插件也没这么大本事
