### ISSUE TITLE
分片下载最多只能两个连接

### ISSUE THREAD

**Issue by CoderYellow** [acgotaku/115#169]
其他链接报403
` [HttpSkipResponseCommand.cc:240] errorCode=22 The response status is not successful. status=403
`
有办法破解吗，还是是115限制？

**Comment by acgotaku** [comment]
充值会员 应该就没这个问题

**Comment by zzzop** [comment]
应该是115限制了，我是会员也这样

**Comment by acgotaku** [comment]
充值之后单线程也很快啊  115的限制我也爱莫能助

**Comment by CoderYellow** [comment]
> 充值会员 应该就没这个问题

确实充了会员了，我大概抓包看了一下115浏览器可以多线程，估计还少了些认证信息。普通浏览器速度只能每个线程好像只能2m/s。
