### ISSUE TITLE
为什么速度很慢，连接数只有2

### ISSUE THREAD

**Issue by sevenfxx** [acgotaku/115#17]
是不是UA要改？

**Comment by acgotaku** [comment]
@sevenfxx 慢成啥样?

**Comment by sevenfxx** [comment]
速度只有200多kb

**Comment by acgotaku** [comment]
我插件全默认的 也有4百k 啊

**Comment by sevenfxx** [comment]
好吧，我以为能达到几兆

**Comment by acgotaku** [comment]
@sevenfxx 应该可以吧?  能贴出你 导出下载的内容么?

**Comment by sevenfxx** [comment]
aria2c -c -s10 -k1M -x10 -o "[www.d9zx.net]-Prototype.2.CHS.full.rip-RAS.rar" --header "User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3"  --header "Referer: http://115.com/"  "http://fscdntel.115.com/gdown_group360/M00/05/F0/cWmPM1AUVi8AAAABOZTUiC2q5OI6955263/%5Bwww.d9zx.net%5D-Prototype.2.CHS.full.rip-RAS.rar?k=UlbOrTPRwTA3Z-z8QkVdKg&t=1439840544&u=1857823362-26325743-b2kwk0jya8li5&s=102400&file=%5Bwww.d9zx.net%5D-Prototype.2.CHS.full.rip-RAS.rar"

**Comment by sevenfxx** [comment]
顺便说一下，我只是115普通会员，跟这个没关系吧

**Comment by acgotaku** [comment]
@sevenfxx 你不是 VIP 貌似只有这个速度....
