### ISSUE TITLE
aria2已经开启远程，115网盘助手如何配置？

### ISSUE THREAD

**Issue by a739986248** [acgotaku/115#172]
华硕路由器，配合ddnsto，aria2已经可以远程访问，接下来想远程115助手下载，但是在导出设置，RPC地址部分，不知道怎么填。token应该没问题。目前我尝试过http://token:xxxxx@dns:6800/jsonrpc，连接不上

**Comment by acgotaku** [comment]
http://binux.github.io/yaaw/demo/

和这个一样 你在这里 能用 就都 能用

**Comment by fanzhen1** [comment]
同问！
看插件的设置界面没有填token的地方，本小白也不知道应该去哪找手动设置文件。
不过我的rpc是部署在远程vps上的

**Comment by acgotaku** [comment]
@fanzhen1  看 readme啊 http://token:secret@hostname:port/jsonrpc  就在网址里 用 token的形式
