### ISSUE TITLE
最近转到aria2后没有速度

### ISSUE THREAD

**Issue by oracle91** [acgotaku/115#173]
之前一直都可以用，配置也没改过，最近转到aria2后没有速度，文件大小也显示0B

**Comment by acgotaku** [comment]
我最近 115 过期  也没法测试了 。。。

**Comment by zzzop** [comment]
我的还可以用

**Comment by MorphyHu** [comment]
和我的问题一样，估计也是DNS原因

把DNS解析指向国内的DNS。不要用8.8.8.8
