### ISSUE TITLE
下载文件夹出错

### ISSUE THREAD

**Issue by 329928** [acgotaku/115#177]
下载会创建文件夹和子文件夹，但是整个文件夹里的文件数量只有8个，其余的文件全部都在根目录里；看了下貌似很久以前有这个问题并且解决了，现在是否又有这个问题。

**Comment by starrin** [comment]
你用的是docker里的aria2吗？如果是的话可以参考https://github.com/XUJINKAI/aria2-with-webui/issues/11

**Comment by acgotaku** [comment]
先分析 分析自己的问题 ==  我这代码都没更新过。。。

就跑来提issue。。。
