### ISSUE TITLE
你这个东西怎么用？

### ISSUE THREAD

**Issue by gu20124848** [acgotaku/115#178]
我是win7下面自己组装的aria2。你的这个是插件还是脚本？我是电脑下载。

**Comment by acgotaku** [comment]
去 Chrome Web Store安装   https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf

**Comment by gu20124848** [comment]
大佬。我已经把fake115导入到油候，115界面出来个<选择文件>。你的这个导入油候无效。

**Comment by acgotaku** [comment]
我的这个又不是导入用的脚本。。。
