### ISSUE TITLE
无法与aria2服务器连接的问题

### ISSUE THREAD

**Issue by mapleshadow** [acgotaku/115#18]
我的环境是nas设备x86，系统是omv系统，linux环境。
因为omv的官方源问题，aria2最高版本也就是1.15.1。
目前我配置插件，输入地址，输入访问的账号密码，仍然无法测试正常连通aria2服务，请问是什么原因呢？
PS：是我的aria2程序确实版本太低吗？
PS：我用该网址http://ziahamza.github.io/webui-aria2/测试我的aria2是正常的，并可以正常下载

**Comment by acgotaku** [comment]
@mapleshadow  用户名密码的支持好像最低也得是  1.15.2  你试试不加密能用么?

**Comment by mapleshadow** [comment]
你指的是我的aria2 1.15.1不加密嘛？
我好像没开启加密

**Comment by acgotaku** [comment]
@mapleshadow aria2c和迅雷有什么关系??

**Comment by mapleshadow** [comment]
@acgotaku 听说，本地开启了迅雷之后，他会扫描没加密的aria2服务，然后占用之，纳入他自己的库，盗取下载和上传流量。

**Comment by acgotaku** [comment]
@mapleshadow 这听说的太不靠谱了吧~

**Comment by mapleshadow** [comment]
算了，别管这些了，总之还是解决了，最终还是升级到了1.18.X版本，抛弃了RPC用户账号密码，改成了验证码的方式，目前已经OK了
