### ISSUE TITLE
导出的IDM文件依旧无法下载

### ISSUE THREAD

**Issue by ZerOri** [acgotaku/115#181]
RT，目前插件导出的IDM文件依旧无法下载，显示error，请问有什么解决办法么？

**Comment by acgotaku** [comment]
~~资助作者一个能用的IDM~~

**Comment by ZerOri** [comment]
官方下载地址：[http://mirror2.internetdownloadmanager.com/idman633build1.exe?b=1&filename=idman633build1.exe](url)，IDM有一个月的免费试用期。留下邮箱发你注册工具。

**Comment by acgotaku** [comment]
邮箱在这里 https://github.com/acgotaku/115/blob/master/.circleci/config.yml#L49

**Comment by illinity** [comment]
> 
> 
> RT，目前插件导出的IDM文件依旧无法下载，显示error，请问有什么解决办法么？

不需要导出，直接使用快捷键强制调用idm下载，我这里速度只有100KB/s。
