### ISSUE TITLE
fake115失效了吗？

### ISSUE THREAD

**Issue by gu20124848** [acgotaku/115#183]
我在百度浏览器下成功安装油猴子脚本管理器+fake115.在油猴里成功导入了115master。出来个《选择文件》。我熟练使用ARIA2，你的这些好像不能快速下载115大文件啊。怎么联系你？我在墙内。截图都不让发。急死人了。

**Comment by acgotaku** [comment]
下载大文件？ 在墙内 就好好学习翻墙啊（

**Comment by gu20124848** [comment]
翻墙不是犯法的吗

**Comment by acgotaku** [comment]
是的 所以你还是老老实实用官方下载吧

**Comment by gu20124848** [comment]
我在火狐浏览器商店看见你写了个115插件，希望你继续更新。可以吗？

**Comment by acgotaku** [comment]
不可以 我只更新 Chrome

**Comment by gu20124848** [comment]
那你在谷歌应用商店，写个115的Aria2插件不就行了？我可以上谷歌商店的。完全在墙内，完全守法。

**Comment by gu20124848** [comment]
弟弟。。你写的东西真是多啊。许多破解网站都是你的名字。继续努力。继续更新。我貌似在墙内找到了方法。

**Comment by acgotaku** [comment]
你谁啊 不要这样套近乎
