### ISSUE TITLE
HTTP 返回头无效或无法识别

### ISSUE THREAD

**Issue by Totuz** [acgotaku/115#187]
### 使用环境
硬件: 树莓派3B+
系统: archlinux arm
aria2版本: 1.34.0
AriaNg: v1.1.0 (dc90369)
chrome: 74.0.3729.131 (Official Build) (64-bit)
115插件: 0.3.3
### 问题描述
使用本插件导出下载出错，无法下载
ARIA2 RPC\存为Aria2文件\拷贝下载链接
这几种方式都100%出现"HTTP 返回头无效或无法识别"
### 尝试解决
看过大家提交的issues，尝试使用其中的解决办法
* 修改.aria2.conf配置:
check-certificate=false
enable-http-pipelining=false
split=3
max-concurrent-downloads=3
* 更改Cookie
* 更改User-Agent
* 更改Referer
* 使用aria2旧版本1.18.8（因为看到有朋友说1.18.8正常）
* 在115浏览器中使用本插件

以上方式都无效
### 可能的办法
我看到文本导出\存为Aria2文件的Cookie是空的，我从chrome里找到并设置的Cookie是这种格式：
`acw_tc=784e2c9c15578488xxxxxxxxe432da1507abb8cbedba63feb57xxxxxxx21; UID=341531258_A1_xxxxxxxx31; CID=2134c8967xa0e614xxxxxxx0f51a85ee; SEID=ba6d3ffa026e09a8462ecxxxxxxxx34b18a41f4a9d19752fcac178a26b685acbac9842bf8c262d31e0f5361b76da74cb44cadxxxxxxxx17b68a686c6; 115_lang=zh`

Referer：
`https://115.com/?cid=1368779188346774548&offset=0&mode=wangpan`

但我看到这位朋友贴图说正常下载的Cookie和我Cookie格式是不一样的：
感覺是115那邊檢查cookies
正常可以下載的cookies長這樣
![image](https://user-images.githubusercontent.com/21094580/41190338-35a9c6fe-6c0f-11e8-94b7-4ada9e4f729a.png)
但是導出的會變成這樣
![image](https://user-images.githubusercontent.com/21094580/41190341-4a67d0c2-6c0f-11e8-92c0-0ce1ca22baae.png)

_Originally posted by @vava24680 in https://github.com/acgotaku/115/issues/111#issuecomment-395956737_

所以可以确定是Cookie的问题吗？
要怎么样获取到正确的Cookie？
然后看到这位的回复：
修改home.js 的第xxx行，用.getResponseHeaders('Set-Cookie')把data.cookies = cookies 完善一下即可。

_Originally posted by @canwushuang in https://github.com/acgotaku/115/issues/156#issuecomment-431313391_
这个是不是能解决问题呢，但是我不知道该怎么修改，而且我使用chrome加载插件源码会出错：
![image](https://user-images.githubusercontent.com/45308854/57771433-4d9b8f80-7745-11e9-818f-e65b102886a4.png)

希望作者和各位朋友帮忙，感激不尽！

**Comment by acgotaku** [comment]
写了很多。。但没啥用。。。
不要做多余的设置 Chrome下 重新登录

文本导出 并把导出的内容贴出来 看看

**Comment by Totuz** [comment]
> 写了很多。。但没啥用。。。
> 不要做多余的设置 Chrome下 重新登录
> 
> 文本导出 并把导出的内容贴出来 看看

文本导出内容
`aria2c -c -s10 -k1M -x16 --enable-rpc=false -o "Deadpool.2.2018.Super.Duper.Cut.UNRATED.1080p.BluRay.x264.DTS-HDC.mkv" --header "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" --header "Referer: https://115.com/" --header "Cookie: " "http://cdnfhnfile.115.com/5b6b4ef9b883977653dc8c4ae15755d674cdcc37/Deadpool.2.2018.Super.Duper.Cut.UNRATED.1080p.BluRay.x264.DTS-HDC.mkv?t=1558783527&u=341531258&s=13107200&d=vip-1948124212-chet4krcavc56dxrh-1&c=2&f=3&k=ced81fe8c0d7d531f4baa5901ecdcf9a" --checksum=sha-1=9793A1189450EEA7735DA913A271825094D29301`

**Comment by acgotaku** [comment]
你是手动删除了 cookies？ 试试使用fake115登录

**Comment by Totuz** [comment]
> 你是手动删除了 cookies？ 试试使用fake115登录

没有手动删除cookie
应该是获取cookie的问题，我使用fake115登录也不行
使用tampermonkey的aria2HelperFor115可以正常下载
https://github.com/QuChao/Watsilla/raw/master/userScripts/aria2HelperFor115.user.js

**Comment by acgotaku** [comment]
这个问题确实很奇怪，你可以清空浏览器缓存试试。 或者试试别的电脑或者账号 定位下原因

**Comment by boeing888** [comment]
我的也是这个问题，导出后cookies为空，应该是没有获取到。

**Comment by snowman** [comment]
https://github.com/kkHAIKE/fake115/issues/87
