### ISSUE TITLE
能否开发一个比特球的插件

### ISSUE THREAD

**Issue by ODtian** [acgotaku/115#194]
比特球跟115差不多但是会员比较便宜，如果能用aria2下载一定很不错！

**Comment by acgotaku** [comment]
我又没用过。。。

**Comment by pinoyo** [comment]
楼主跟我想着一块去了，版主不用也没办法，115现在版权限制还是比较麻烦的，有些美剧下不了，比特球刚出来，暂时不会受限

**Comment by freefrank** [comment]
同！可以借给作者会员用。

**Comment by acgotaku** [comment]
我在 日本。。。  比特球在日本访问很不好。。。
