### ISSUE TITLE
没有显示导出下载

### ISSUE THREAD

**Issue by k1n** [acgotaku/115#2]
OS: MAC OS X 10.10.1
Browser: Chrome 41.0.2272.35 beta (64-bit)

**Comment by k1n** [comment]
希望这个有帮助，我在MAC OS X的aria2测试OK。
http://chunchu.org/web/2012/07/23/2118.html
谢谢付出，还有期望会有firefox的add on或者脚本。

**Comment by acgotaku** [comment]
@k1n 目前只做了 RPC的功能,后续功能继续添加的 敬请期待.

**Comment by shinvdu** [comment]
os: ubuntu 14
chrome: 版本 36.0.1985.125

没有显示

**Comment by acgotaku** [comment]
@shinvdu 配置菜单有的，在个人信息 帐号设置  菜单的下面 看 readme的截图

**Comment by acgotaku** [comment]
@k1n 新版本发布 了  这回支持了

**Comment by acgotaku** [comment]
@k1n  FF版本也发布了
