### ISSUE TITLE
下载速度比客户端慢很多，VIP用户

### ISSUE THREAD

**Issue by gxjy00** [acgotaku/115#20]
用客户端可以达到1M/s，但是aria2只有100-200k/s，而且只有两个线程。这正常吗？有没有可能提高啊？

**Comment by acgotaku** [comment]
@gxjy00 由于现在需要手机客户端才能登录... 我都不打算继续维护了...

**Comment by scgaw2000** [comment]
@acgotaku 
![screenshot 2015-10-17 17 43 44](https://cloud.githubusercontent.com/assets/3814422/10558117/a0dc01b6-74f6-11e5-99a4-514dc397ce3e.png)
我是一個小小的搬運工。

**Comment by acgotaku** [comment]
@tsekityam 这个我知道啊 感觉绑定了QQ 就更加泄漏隐私了 还是不太情愿

**Comment by w0330t** [comment]
@acgotaku 目前我是这么做的，用虚拟机装上115浏览器，然后把您的插件用开发者模式加载进去，这样保证了使用也保证了隐私，就是稍微麻烦一点，不过现在的费用不可的国产软件我几乎都会用虚拟机运行，就看自己了。

**Comment by wao1201** [comment]
有人今天 aria2 离线 115 工作吗？我这里不行了。
浏览器自带下载的话，需要先点击个证书相关的弹窗才能继续。
是不是证书的原因导致用不了呀？
谢谢

**Comment by acgotaku** [comment]
@wao1201 就是证书的问题 因为 115现在登录很恶心 插件暂时停止更新了

**Comment by wao1201** [comment]
@acgotaku 好的，收到

**Comment by wao1201** [comment]
貌似证书问题没有了？我这刚试了个 https 的链接，可以下载了
![](http://ww2.sinaimg.cn/large/6bdc3836gw1ey3ocu2l6dj20xy03hgma.jpg)
![](http://ww3.sinaimg.cn/large/6bdc3836gw1ey3odb8v4tj205p01kmx0.jpg)
