### ISSUE TITLE
115无法获取下载链接

### ISSUE THREAD

**Issue by tyhunter** [acgotaku/115#206]
Chrome版本：79.0.3928.4（正式版本）dev （64 位）
插件版本：Version: 0.3.5 Update date: 2019/08/11
昨天点击ARIA RPC还是正常的，今天点击后，出现“正在获取下载地址“，不会接着出现成功的字样，ARIA里也没有任务被添加进去，试着点击“批量打开“和“文本导出”功能，也无效，希望大佬能修复下

**Comment by acgotaku** [comment]
我自己测试了一下，是可以使用的。 你试试 是否资源本身被封了？

或者换其他资源 试试？

**Comment by Artieeeeee** [comment]
我也是，无法获取地址，应该不是资源的问题

**Comment by zzzop** [comment]
能用啊，今天还用的

**Comment by Artieeeeee** [comment]
我下了稳定版的chrome，发现低版本的还是正常的
开发者版的Version 79.0.3941.4 (Official Build) dev (64-bit)用不了
Version 77.0.3865.120 (Official Build) (32-bit)可以使用没问题

**Comment by acgotaku** [comment]
先使用正式 Release版本吧

**Comment by moerfutin** [comment]
设置成功，但是导出失败。。。。
![image](https://user-images.githubusercontent.com/9960618/69723371-550c0e80-1154-11ea-9d77-e29a7612cf95.png)

**Comment by ericjee** [comment]
Version 79.0.3945.56 (Official Build) beta (64-bit)

**Comment by fz19870823** [comment]
我也碰到了这个提示，不过虽然提示出错，不过查看aria2的任务时，发现其实已经添加了。

**Comment by czhu** [comment]
同样的问题 v79的chrome文本导出就没有反应了 希望能解决下 谢谢

**Comment by jinbo0122** [comment]
同上Version 79.0.3945.79 (Official Build) (64-bit) 点击导出无反应，前天用着还没问题来着

**Comment by acgotaku** [comment]
https://www.chromium.org/Home/chromium-security/extension-content-script-fetches

Chrome新版 更改了 fetch规则，我之后会更新。现在先用老版本Chrome凑合下吧

**Comment by acgotaku** [comment]
已修復

**Comment by ghbeta** [comment]
请问新版本会push到商店吗 还是需要手动更新

**Comment by acgotaku** [comment]
@ghbeta 商店还在审核，想用的话 直接使用源代码编译

**Comment by s3cj0y** [comment]
这个是不是跟我那个同样的问题，但是我的chromeos里的chrome，mac里的chrome都是好的，只有windows出现同样问题

**Comment by remedy1111-git** [comment]
> @ghbeta 商店还在审核，想用的话 直接使用源代码编译

麻烦问下大佬，手动更新用源代码编译的方法能指教一下吗，我直接下载了代码页的zip解压后用chrome加载但是
![Uploading 微信图片_20191217113332.png…]()不知道能不能帮忙解答下

**Comment by acgotaku** [comment]
这个需要编译的，还是等我处理下商店的审核吧

想用的话 我给你个 zip包 解压载入就行
[chrome.zip](https://github.com/acgotaku/115/files/3973238/chrome.zip)

**Comment by remedy1111-git** [comment]
> 这个需要编译的，还是等我处理下商店的审核吧
> 
> 想用的话 我给你个 zip包 解压载入就行
> [chrome.zip](https://github.com/acgotaku/115/files/3973238/chrome.zip)

谢谢大佬啦。

**Comment by zhaoleihello** [comment]
<img width="1063" alt="WX20191219-165554@2x" src="https://user-images.githubusercontent.com/24755701/71159421-90e05280-2280-11ea-9e6c-42eeb35acb9f.png">

`imagemin-pngquant`和`gulp-imagemin`报错

`imagemin-pngquant`重新安装以后没事了, `gulp-imagemin`还不行, build结束后chrome.zip里img文件夹没打包进去.

请问大佬这个我是不是哪里错了?

**Comment by acgotaku** [comment]
@zhaoleihello  依赖安装有问题，我已经打包好了
https://github.com/acgotaku/115/blob/master/115.crx

**Comment by BlueFang** [comment]
> @zhaoleihello 依赖安装有问题，我已经打包好了
> https://github.com/acgotaku/115/blob/master/115.crx

大佬能重新发个链接吗？

**Comment by MCZSR** [comment]
我也发现问题了，更新chrome之后115无法播放，aria2推送也不行，播放问题要通过flags关闭cookie限制，但还是推送不了，多装了一个旧版本的（78）就好了

**Comment by litianjin66** [comment]
> @zhaoleihello 依赖安装有问题，我已经打包好了
> https://github.com/acgotaku/115/blob/master/115.crx

大佬 115好像对文件大小进行限制了 小的文档文件可以用aria2下载 但是大的视频文件无法获取下载地址 用的是0.3.6的插件 不知道有没有办法？

**Comment by litianjin66** [comment]
大佬 115好像对文件大小有限制了 小的文档可以用aria2下载 大的视频文件无法获取下载地址 我用的是0.3.6的插件 不知道有没有什么办法？

**Comment by pupilcc** [comment]
> 大佬 115 好像对文件大小有限制了 小的文档可以用 aria2 下载 大的视频文件无法获取下载地址 我用的是 0.3.6 的插件 不知道有没有什么办法？

尝试一下使用目前最新的 0.3.7 版本https://raw.githubusercontent.com/acgotaku/115/master/release/115.crx

**Comment by Dexter1217** [comment]
目前使用0.3.8版本插件，似乎还是无法正常导出大文件
