### ISSUE TITLE
发现一个问题，发送到导出下载到Aria2c时可以成功，但是aria2c 没有速度，接收不到数据包

### ISSUE THREAD

**Issue by MorphyHu** [acgotaku/115#208]
发现一个问题，发送到导出下载到Aria2c时可以成功，但是aria2c 没有速度，接收不到数据包。感觉是115方面进行了屏蔽。

**Comment by freefrank** [comment]
感觉是115做限制了哟

**Comment by zzzop** [comment]
你用的什么浏览器，版本是多少，给作者点信息啊。
我的谷歌稳定版浏览器78.0.3904.97没问题，发现是其他浏览器有问题，手机上kiwibrowser，pc的centbrowser都不可以。另一个issue里也有人提过测试版chrome不能用

**Comment by MorphyHu** [comment]
今天经过一天的测试排查，终于找到原因所在。
原因在于DNS解析问题, 我之前的下载服务器DNS使用的是8.8.8.8, 最近可能115 CDN网络升级，国外的DNS解析出来的IP连接失败，导致任务不继续进行了。
后来将DNS设为国内DNS 223.5.5.5 又可以正常下载了。 问题圆满解决。可以CLOSE了。
