### ISSUE TITLE
国外欧洲下载速度是不是被限速了 无解了吗？

### ISSUE THREAD

**Issue by linker999** [acgotaku/115#210]
用国外欧洲的vps下载只有3-5MB/S。。

**Comment by zzzop** [comment]
就两个线程本地也没多快，国外115也没服务器吧

**Comment by acgotaku** [comment]
没充会员超级慢的都没说话。。。

**Comment by linker999** [comment]
> 没充会员超级慢的都没说话。。。

哈哈 多个任务跑咯 比较有性价比

> 用国外欧洲的vps下载只有3-5MB/S。。


哈哈 多个任务跑咯 比较有性价比

**Comment by linker999** [comment]
> 没充会员超级慢的都没说话。。。

能否搞个火狐的版本呢？

**Comment by acgotaku** [comment]
@linker999  火狐没时间搞，而且装个Chrome也不费啥时间啊
