### ISSUE TITLE
能否在搜索结果中加入aria下载按钮？

### ISSUE THREAD

**Issue by truebit** [acgotaku/115#211]
如题。对于资源量大的人，搜索后下载的需求比较大。感谢

**Comment by acgotaku** [comment]
我看看是否方便添加吧，搜索找到路径也不是不能下载

**Comment by gexiaopeng** [comment]
能找到路径，但如果文件夹下面文件很多，就很难定位了。

**Comment by 362227** [comment]
> 能找到路径，但如果文件夹下面文件很多，就很难定位了。

复制文件到空文件夹再下载 ，只能这样了
