### ISSUE TITLE
前端问题？是否支持AriaNg？

### ISSUE THREAD

**Issue by boluohong** [acgotaku/115#213]
脚本作者你好
我是一个小白，所以以下提的问题可能有些奇怪，请不要介意
我在自己的PC端WIN系统装了一个ARIA2 （以下简称Local-A2） ，前端界面用的是Aria2 & YAAW
然后在GCP的虚拟机上也安装了一个ARIA2 （以下简称GCP-A2），前端界面用的是AriaNg
以nyaa上的新漫画资源测试，GCP-A2可以以12Mb/s下载（即排除GCP-A2本身不正常）

依照指引，在chrome上安装阁下脚本，并开始操作，得出下列反应
1.Local-A2 下完全正常
添加RPC：http://localhost:6800/jsonrpc，连接成功并显示版本号
导出115下载测试，结果显示正常

2.GCP-A2 无法用阁下的115脚本下载
添加RPC，即将localhost代换为GCP的IP
报错：错误，请查看是否开启Aria2

问题：
到底是为什么呢？
因注意到Chrome 应用商店上提到：支持YAAW。
那么GCP-A2因为用的是AriaNg所以不支持？

因为我是一个大一计算机基础都差点挂科的小白
所以很多关于计算机网络的知识都靠搜索引擎自学
实在没有办法，来打扰脚本作者，希望指点一二

**Comment by zzzop** [comment]
gcp上的aria2的rpc添加其他下载正常不，可能是rpc模式没启用或者你端口没打开

**Comment by acgotaku** [comment]
AriaNg 和 YAAW都只是客户端，和 Aria2服务本身没关系。

你不启动Aria2服务的话，是没有意义的。

GCP的 Aria2服务有问题的话，AriaNg和 YAAW都会用不了

**Comment by boluohong** [comment]
真是福至心灵呀！！
我刚刚想来看有没有新回复，还没进来看，先看到usage的Recommended Settings
突然想起我在脚本设定rpc的时候，密钥没有填！
因为我之前一直按照http://hostname:port的格式于是我按照http://token:secret@hostname:port/jsonrpc的格式填好。
bingo！！！问题解决了
进来看到两位的回复，在此谢谢了。

**Comment by boluohong** [comment]
> gcp上的aria2的rpc添加其他下载正常不，可能是rpc模式没启用或者你端口没打开

你说的对，我在脚本填rcp的时候，忘记填密钥了，刚刚看到usage，突然想起来，修改后问题解决了。

**Comment by boluohong** [comment]
> AriaNg 和 YAAW都只是客户端，和 Aria2服务本身没关系。
> 
> 你不启动Aria2服务的话，是没有意义的。
> 
> GCP的 Aria2服务有问题的话，AriaNg和 YAAW都会用不了

**Comment by boluohong** [comment]
> AriaNg 和 YAAW都只是客户端，和 Aria2服务本身没关系。
> 
> 你不启动Aria2服务的话，是没有意义的。
> 
> GCP的 Aria2服务有问题的话，AriaNg和 YAAW都会用不了

**Comment by boluohong** [comment]
> AriaNg 和 YAAW都只是客户端，和 Aria2服务本身没关系。
> 
> 你不启动Aria2服务的话，是没有意义的。
> 
> GCP的 Aria2服务有问题的话，AriaNg和 YAAW都会用不了
真是福至心灵呀！！
我刚刚想来看有没有新回复，还没进来看，先看到usage的Recommended Settings
突然想起我在脚本设定rpc的时候，密钥没有填！
因为我之前一直按照http://hostname:port的格式于是我按照http://token:secret@hostname:port/jsonrpc的格式填好。
bingo！！！问题解决了
进来看到两位的回复，在此谢谢了。

**Comment by acgotaku** [comment]
解决了 就  close掉吧
