### ISSUE TITLE
大佬您这个插件怎么安装呀？能否给个教程？

### ISSUE THREAD

**Issue by wutongskype** [acgotaku/115#214]
大佬您这个插件怎么安装呀？能否给个教程？

**Comment by wutongskype** [comment]
最近115导到Aria2中无法下载了，能在Aria2中看到任务，但是一直都是0过一会就去提示失败，之前都好着呢。

**Comment by acgotaku** [comment]
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf

直接去 Chrome Web Store安装啊
