### ISSUE TITLE
使用windows10 fake115 的时候会触发chrome Cross-Origin Read Blocking

### ISSUE THREAD

**Issue by s3cj0y** [acgotaku/115#215]
最近在windows10 上用fake115 使用chrome的时候，发现点完导出下载，不出现下载成功，也确实未发送给aria2，查看console，发现触发了chrome的机制。
Cross-Origin Read Blocking (CORB) blocked cross-origin response  with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
提示触发位置为home.js 871行 
                    fetch("//webapi.115.com/files/download?pickcode=".concat(e), t).then(function(e) {
大概酱紫，不过windows10 可以用115浏览器，也无所谓啦，哈哈

**Comment by acgotaku** [comment]
这个问题我已经解决了，不过chrome商店没通过审核。。。
