### ISSUE TITLE
115下载后文件都跳到根目录

### ISSUE THREAD

**Issue by kavinlam7** [acgotaku/115#217]
首先非常感谢开发这个插件，115是主力下载方式，这个插件解决了我大问题，目前唯一的问题就是下载后文件都跑到了下载的根目录，文件结构简单的还好，在下载4k原盘的时候，就很头大，期望能修复这个问题，多谢。

**Comment by acgotaku** [comment]
看看是不是你自己设置的问题

**Comment by acgotaku** [comment]
参考： https://github.com/XUJINKAI/aria2-with-webui/issues/11
