### ISSUE TITLE
从115导出的链接无法在aira2下载

### ISSUE THREAD

**Issue by akioen** [acgotaku/115#218]
谢谢插件作者，使用时候最近遇到的问题、使用了旧版的Chrome的浏览器，可以导出到aira2。但一到达air2就进到了失败文件之列。错误的信息是任务状态: 发生错误 (19)temporary failure in name resolution

**Comment by acgotaku** [comment]
可以说一下你的文件名么？ 是不是有特殊字符？

试试下载其他文件？

**Comment by akioen** [comment]
文件名是任务名称: 2009.The.Hangover.[Extended.Cut].1920x800.BDRip.x264.TrueHD.mkv，算是基本的文件名吧 我试过其他115导出的文件均没办法下载。错误提示就是域名无法解析。
115导出的下载地址是：http://cdnfhn307.115.com/5D46SqKZBKhOh_D5voPOhoOh5PIpR9dICqxCBMcC/2009.The.Hangover.%5BExtended.Cut%5D.1920x800.BDRip.x264.TrueHD.mkv?t=1577422514&u=12322978&s=13107200&d=vip-1947607739-eiqqmq4hgq82zzhk4-1&c=2&f=3&k=2a96d4382e8f0be522862e6d5cc010f4
这串地址在Chrome浏览器是可以直接下载，不过无论复制在aria2还是通过您的插件导入到aria2都出错。

**Comment by akioen** [comment]
> 可以说一下你的文件名么？是不是有特殊字符？
> 
> 请下载其他文件？

已找到解决方法，应该问题来自我的aira2的bt服务器配置，我添加了最新的bt服务器配置文件就可以解析115的域名了。谢谢
