### ISSUE TITLE
115界面更新功能失效

### ISSUE THREAD

**Issue by smilelhong** [acgotaku/115#219]
![image](https://user-images.githubusercontent.com/20783859/71225154-98503c00-2312-11ea-9fc9-df2e7bd423eb.png)

**Comment by shengdie** [comment]
貌似无法获取下载地址

**Comment by jaysh-yin** [comment]
+1

**Comment by acgotaku** [comment]
社畜很辛苦，有时间看看吧

**Comment by MorphyHu** [comment]
感谢+1

**Comment by acgotaku** [comment]
修复了 https://github.com/acgotaku/115/blob/master/115.crx

**Comment by truebit** [comment]
请问我想在Firefox怎么编译打包呢？

**Comment by acgotaku** [comment]
@truebit  可以看看Firefox的教程
