### ISSUE TITLE
忽然无法下载，控制台爆跨域的问题

### ISSUE THREAD

**Issue by tony1016** [acgotaku/115#220]
Console里的错误如下：

home.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://webapi.115.com/files/download?pickcode=bj2lm9epe6p688l84 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

**Comment by acgotaku** [comment]
新版本已经出了 但是商店不让更新 之后我会出一个 rex

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/206#issuecomment-566519886

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/blob/master/115.crx
