### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by 2909272751** [acgotaku/115#221]
导出不了了，麻烦作者大大修复下

**Comment by zzzop** [comment]
更新过了，你用的哪个版本

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/blob/master/release/115.crx

**Comment by 2909272751** [comment]
> https://github.com/acgotaku/115/blob/master/release/115.crx

请问怎么使用啊，拖进chrome显示该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by acgotaku** [comment]
因为Chrome商店不让发布了，所以只能自己打包。

**Comment by 2909272751** [comment]
> 因为Chrome商店不让发布了，所以只能自己打包。

请问能提供打包教程吗？不太懂

**Comment by acgotaku** [comment]
我不都提供打包好的 crx 了，打包教程请自己谷歌搜
