### ISSUE TITLE
github release也可以更新啊

### ISSUE THREAD

**Issue by 2909272751** [acgotaku/115#222]
github release也可以更新啊

_Originally posted by @YFTX2015 in https://github.com/acgotaku/115/issues/216#issuecomment-566648007_

请问怎么更新啊，我的chrome显示该扩展程序可能在您不知情的情况下安装

**Comment by YFTX2015** [comment]
插件导入115浏览器可以直接用，谷歌的话，估计只有等商店审核通过了，才能用
