### ISSUE TITLE
Chrome插件的市场都找不到这个插件了，是不是被下架了

### ISSUE THREAD

**Issue by SCGabriel** [acgotaku/115#225]
https://chrome.google.com/webstore/detail/ojafklbojgenkohhdgdjeaepnbjffdjf
404了

直接在商店搜索也找不到了

**Comment by LarkinZero** [comment]
作者推上说，是因为审核没过，然后就下架了

**Comment by acgotaku** [comment]
下架了，直接使用 crx安装吧
