### ISSUE TITLE
更新0.3.6后无法连接到Aria2

### ISSUE THREAD

**Issue by KIRI-Z** [acgotaku/115#226]
Aria2 RPC: https://token:MySecrect@MyHost:6800/jsonrpc
提示：错误，请查看是否开启Aria2

而执行命令
`curl -X POST https://MyHost:6800/jsonrpc -H "Content-Type:application/json" -H "Accept:application/json" --data "{\"jsonrpc\":\"2.0\", \"method\":\"aria2.getVersion\", \"params\":[\"token:MySecrect\"], \"id\":1}"`
返回结果为
`{"id":1,"jsonrpc":"2.0","result":{"enabledFeatures":["Async DNS","BitTorrent","Firefox3 Cookie","HTTPS","Message Digest","Metalink","XML-RPC"],"version":"1.34.0"}}`
Aria2应该是已经正常运行了

**Comment by KIRI-Z** [comment]
Update：虽然提示错误，但应用设置后可以直接导出下载。再次测试连接就正常了。

是不是要应用设置后再测试连接？

**Comment by acgotaku** [comment]
我在Usage的时候都说了 先保存再使用。。。
