### ISSUE TITLE
无法获取下载地址 0.3.6

### ISSUE THREAD

**Issue by ghbeta** [acgotaku/115#233]
作者好，
今天发现0.3.6的 aria-rpc无法获取地址了， 选中115的文件然后点击aria-rpc， 出现一个正在获取地址后，就结束了，是不是chrome又更新了

**Comment by acgotaku** [comment]
是不是很多文件都尝试了？ 我测试了一下 可以下载的

**Comment by ghbeta** [comment]
多谢回复，我刚才又试了相同的文件又可以了 我估计就是115的网络问题，谢谢了

**Comment by stanlu1013** [comment]
请问一下，用Fake115开启115後，如果一次选取大约100个左右的资料夹
再点击ARIA PRC下载，在解析连接到一半後，115就会自动登出，请问这样是115的限制吗?

感谢!

**Comment by acgotaku** [comment]
@stanlu1013  应该是请求太频繁 被登出  还是尝试小量文件下载吧
