### ISSUE TITLE
Android火狐浏览器下HTTP 返回头无效或无法识别.

### ISSUE THREAD

**Issue by hellomrvan** [acgotaku/115#236]
之前在安卓火狐浏览器下用插件加user agent下载正常，最近不知道是火狐更新还是什么问题，下载总是错误22，HTTP 返回头无效或无法识别.
在页面中文本导出的连接cookie正常，如有可能烦请作者测试一下。

**Comment by acgotaku** [comment]
安卓 火狐不在我的 处理范围内啊。。。

**Comment by hellomrvan** [comment]
好吧，谢谢。
