### ISSUE TITLE
aria 下载无速度

### ISSUE THREAD

**Issue by 2909272751** [acgotaku/115#237]
如题，aria导出成功，但是无速度

**Comment by zzzop** [comment]
我可以

**Comment by illinity** [comment]
firefox测试有速度100KB/s 
firefox使用Aria2 下载器集成组件也是一样的速度。没有看到加速效果还是2线程再跑。

**Comment by acgotaku** [comment]
没速度 就充会员

**Comment by rr4e** [comment]
> 没速度就充会员

直截了当干脆利落 哈哈
