### ISSUE TITLE
115下载cookie迁移的问题（aria无法下载或无速度）

### ISSUE THREAD

**Issue by hmglife** [acgotaku/115#238]
作者你好！经测试会员账号使用网页下载时大部分文件都能配合aria2 rpc实现和115电脑版相同的批量下载效果，但部分大文件（一般为视频主文件）仍只能单独选中且只能用谷歌浏览器本身下载，即使使用aria2 rpc带了cookie的下载在列表里仍然没有速度，不知道对此问题是否在之后的更新里修复。希望作者的插件越做越好，最好能提供cookie的转化方式实现其他下载工具的下载（如IDM），或者完善aria2 rpc本身下载的正确性。相信最终这个插件能够取代115电脑版的作用！

**Comment by acgotaku** [comment]
哈哈哈 因为我买不起会员 又没有 IDM 所以很多case 我也没法对应。。。

**Comment by 94leon** [comment]
我用这个，aria-ng-gui，从没遇到过不能下载的情况。只遇到过偶尔下载中断，继续下载也没问题
