### ISSUE TITLE
AriaNg下载速度为50kb，而且插件长时间不用自动消失？

### ISSUE THREAD

**Issue by jiujiwuan** [acgotaku/115#245]
如题，长时间不用，发现这个插件找不到了。然后自己重新添加的扩展插件。
另外这次好像不能加速了，之前能够100kb下载，而现在恢复到了50kb了。本人非会员。
请问这两个问题都是怎么回事呀？

**Comment by acgotaku** [comment]
谷歌把我插件下架了 说不符合规范 不充会员速度 降低是正常现象
