### ISSUE TITLE
新加坡服务器，有会员，下载速度只有 150k

### ISSUE THREAD

**Issue by Pengyiz** [acgotaku/115#246]
你好，我的服务器在新加坡，有会员，最近下载速度只有 150k，非常困惑。请问是区域限制了么，还是有了新的验证机制，限制了远程的下载。因为这显然是纯粹的限速，特别稳定的 150k/s。心塞。

**Comment by zzzop** [comment]
应该只是服务器问题，我的异地下载没有限速

**Comment by acgotaku** [comment]
我这插件半年都没更新了， 显然你来这里问也不会有答案。。。

**Comment by libucai** [comment]
我刚购置的服务器也在新加坡，下载速度达到了40mb/s，应该是你服务器问题

**Comment by Pengyiz** [comment]
换了 内核解决问题，速度10m/s。感恩。
