### ISSUE TITLE
貌似下载失效了

### ISSUE THREAD

**Issue by altrixe** [acgotaku/115#249]
115网盘所有文件都无法下载了，全部报错
任务状态: 发生错误 (22)
错误描述: HTTP 返回头无效或无法识别.

**Comment by acgotaku** [comment]
我测试了一下 是可以的 检查一下自己的网络环境 或者资源吧

**Comment by altrixe** [comment]
> 我测试了一下 是可以的 检查一下自己的网络环境 或者资源吧

我的锅，nas重启下就ok了
