### ISSUE TITLE
RPC下载时，部分任务获取地址失败

### ISSUE THREAD

**Issue by sicode** [acgotaku/115#25]
插件目前还能用，只是登陆方式着实恶心
RT，选中多个任务后点RPC下载，有些成功开始下载，有些会失败，大概是由于获取不到下载地址
希望可以加个提示什么的，把获取不到地址的文件名提示下，自己再点一次获取就好了

**Comment by acgotaku** [comment]
@sicode 因为登录很恶心 所以放弃维护了....
