### ISSUE TITLE
文件放的时间久了小文件不会下载

### ISSUE THREAD

**Issue by CXido** [acgotaku/115#251]
我在多文件下载的时候发现小文件放久了不会下载（大约在150MB左右的文件）
解决方法是小文件优先下载

还有您的插件是可以远程下载的，不知道您后面会不会开发

**Comment by CXido** [comment]
只要小文件不下载就会占用下载任务数，导致后面的文件都无法下载QwQ

**Comment by acgotaku** [comment]
本来就是可以远程下载的啊

**Comment by CXido** [comment]
啊我瞎了，请无视这个问题

那么小文件优先下载可不可以优化一下？只要文件不下载就一直占位置，满了后会导致后面一直在排队

**Comment by acgotaku** [comment]
这个没法优化 我又不是万能的， 你每次少下点 就是了
