### ISSUE TITLE
求作者更新啊

### ISSUE THREAD

**Issue by yaoshu** [acgotaku/115#26]
115的界面更新了，无法使用了。。。

**Comment by nickkwok** [comment]
求更新！

**Comment by droid-Q** [comment]
@nickkwok  @yaoshu  可以先看下我的pull request ，可以先自己打包试用下。

**Comment by chztv** [comment]
@droid-Q 用了你的版本，发现插件设置那个按钮找不到，RPC下载的按钮位置正确了，下载也正常

**Comment by droid-Q** [comment]
@chztv 我这边是正常的，在文件目录下插件设置是有的，首页没有，我再改下。

**Comment by droid-Q** [comment]
@chztv  已更新。
