### ISSUE TITLE
提示"下载成功!赶紧去看看吧~" 后Aria ng没有任务!

### ISSUE THREAD

**Issue by ni94wei1** [acgotaku/115#273]
需要使用了aria 远程下载功能, 直接将文件下载到手机,  在aria设置中将 localhost 改成了本地手机ip地址, 然后115中提示成功但aria中没任务, 如果该回到localhost是可以正常使用的.   但本身我配置的这个远程下载功能是可用的, 我尝试过下载别的网站连接可以正常使用.
![image](https://user-images.githubusercontent.com/25652988/92347101-79444500-f101-11ea-8114-dd9214d6513f.png)

**Comment by zzzop** [comment]
看看路径，还有手机上aria2的日志

**Comment by hcwhan** [comment]
发现同样问题 控制台有报错 原因是115现在限制了 Web端下载文件的大小
![image](https://user-images.githubusercontent.com/7278897/102807279-4cd6df00-43f9-11eb-9ea7-771178b0af15.png)
https://github.com/kkHAIKE/fake115 新增了一个 `https://github.com/kkHAIKE/fake115/blob/master/fake115d.user.js` 专门获取下载链接的脚本 应该可以集成下

**Comment by hcwhan** [comment]
https://github.com/acgotaku/115/pull/322
请问 这个是已经修复了是吧

**Comment by acgotaku** [comment]
请更新到 0.3.8 版本
