### ISSUE TITLE
aria2下载没有速度！

### ISSUE THREAD

**Issue by heitu001** [acgotaku/115#277]
![QQ截图20200910022853](https://user-images.githubusercontent.com/50029572/92638860-8df52880-f30d-11ea-99e5-c5d6fc4e8564.jpg)
任务添加成功但是就是没速度！

**Comment by heitu001** [comment]
![QQ截图20200910023050](https://user-images.githubusercontent.com/50029572/92638919-a82f0680-f30d-11ea-8f76-d8292f345553.jpg)

**Comment by acgotaku** [comment]
不充钱怎么能变强。。。

**Comment by heitu001** [comment]
> 不充钱怎么能变强。。。

可是我115是会员呀~~以前用的好好的~最近一段时间没用突然就变成这样子了！

**Comment by pikachullk** [comment]
我也有同样的情况...然后只要docker重启一下aria2就可以有速度了~
下载地址的链接用别的下载软件是能下的~这就很奇怪啊~
