### ISSUE TITLE
安卓下的kiwibrowser也是返回错误22

### ISSUE THREAD

**Issue by climbshan** [acgotaku/115#279]
看issue里似乎只有win平台的插件是正常的，其它都是返回错误22

**Comment by climbshan** [comment]
我好像发现为什么了，只有windows下的aria2可以把115的下载链接解析到具体的文件名，其它的都还是具体的下载链接，单独在windows里用ariang新建下载链接也是下载不了的，是115账号登录信息没有传递的原因么？

**Comment by crazyshitass** [comment]
> 我好像发现为什么了，只有windows下的aria2可以把115的下载链接解析到具体的文件名，其它的都还是具体的下载链接，单独在windows里用ariang新建下载链接也是下载不了的，是115账号登录信息没有传递的原因么？

看来真的就是只有win下正常，其它平台没有成功解析。但是之前1-2年我用的都还正常，不知道是不是最近115改了解析规则？不知道作者能否改进一下插件。

**Comment by acgotaku** [comment]
我抽时间看看把  如果我的Linux 平台 能复现 BUG的话

**Comment by crazyshitass** [comment]
> 我抽时间看看把 如果我的Linux 平台 能复现 BUG的话

老哥有进展吗？

**Comment by acgotaku** [comment]
Linux平台是可以正常下载的

**Comment by climbshan** [comment]
又试了下mac上的chrome也是可以的，查了下，可能是kiwi browser虽然是基于chromium开发的，但是没有samesite来传递cookies所以获取不到文件

**Comment by crazyshitass** [comment]
> 又试了下mac上的chrome也是可以的，查了下，可能是kiwi browser虽然是基于chromium开发的，但是没有samesite来传递cookies所以获取不到文件

重新试了下，mac下的chrome正常了，是115客户端更新后不能用这个插件

**Comment by crazyshitass** [comment]
> 又试了下mac上的chrome也是可以的，查了下，可能是kiwi browser虽然是基于chromium开发的，但是没有samesite来传递cookies所以获取不到文件

放弃mac下的115客户端，mac下直接用chrome加载插件是可以正常用的，亲测。
