### ISSUE TITLE
错误描述: HTTP 返回头无效或无法识别.

### ISSUE THREAD

**Issue by ritech** [acgotaku/115#281]
115 在下载大文件和小文件的cdn服务器好像不太一样，
小文件是
下载地址: http://cdnfhnfile.115.com/
大文件是
下载地址: http://cdnfhn210.115.com/    这个210的数字可能会变

在队列里面 小文件的地址在一定时间后地址貌似变化了， 造成下载失败，大文件地址反而一直正常（如果小文件在队列靠前位置，会被正确下载）

<img width="873" alt="0399202C-3A77-48D6-A060-7D41CBB3207D" src="https://user-images.githubusercontent.com/11290395/93659293-3de93500-fa76-11ea-9330-e7dc4e65d6a6.png">

**Comment by acgotaku** [comment]
现在已经加了小文件 优先下载的选项 你可以试试

**Comment by ritech** [comment]
等会试试
另外115.aacc.in 是你维护的吗 ，感觉都一样啊

**Comment by ritech** [comment]
我发现115 现在服务器都是cdn加速服务器，如果队列过长， 很多靠队列后面的地址都会变化

**Comment by acgotaku** [comment]
@ritech  不是

**Comment by ritech** [comment]
新版本小文件优先的什么时候能release ， 感觉低于5m的文件都有很大几率地址会快速刷新

**Comment by acgotaku** [comment]
@ritech  https://github.com/acgotaku/115/tree/master/release  一直都有最新版本 不用 release

**Comment by ritech** [comment]
已解决，但是只能在一次队列中有效，如果加入第二次队列，因为前面的队列没完成， 第二次增加队列的小文件全部不能下载，好像也没什么好办法。

**Comment by acgotaku** [comment]
没啥好办法
