### ISSUE TITLE
零碎的小文件下载

### ISSUE THREAD

**Issue by Hyper0128** [acgotaku/115#297]
请问这个功能在什么时候可以整合进插件，因为我不清楚如何把魔改后的js文件转换成chrome可以识别的情况，所以问问

**Comment by acgotaku** [comment]
![Screenshot from 2020-11-27 22-46-05](https://user-images.githubusercontent.com/1191834/100455637-5de64600-3102-11eb-9d6c-3b4c2da0fb33.png)


已经加了
