### ISSUE TITLE
firefox 扩展不考虑上官方扩展网站么？现在由于签名问题无法安装，目前可以手动关闭签名验证，46开始好像要强制开启签名验证了

### ISSUE THREAD

**Issue by poplarch** [acgotaku/115#30]
如题:)

**Comment by acgotaku** [comment]
@poplarch 115我都不太想维护了。。。。 登录太恶心。

**Comment by acgotaku** [comment]
@poplarch  已经上官方了 https://addons.mozilla.org/zh-CN/firefox/addon/115exporter/
