### ISSUE TITLE
115云界面改版，rpc下载和导出下载按钮被界面按钮挡住

### ISSUE THREAD

**Issue by colorblank** [acgotaku/115#31]

**Comment by skyqty** [comment]
同样的问题..

**Comment by anamewing** [comment]
在 Firefox 版中也遇到此问题。
Firefox 44.0.2
115Exporter 0.1.1

**Comment by acgotaku** [comment]
@anamewing  既然喵呜都发话了 我还是看看吧~

**Comment by anamewing** [comment]
@acgotaku  其实，如果不打算修 #30 的话，折腾这个用处也不大。干脆放弃 Firefox 扩展，专注 Chrome
那边也好。

**Comment by acgotaku** [comment]
@colorblank  @skyqty  @anamewing  这个只是 FF的问题吧 ? Chrome正常不?

**Comment by anamewing** [comment]
Chrome 正常。
Chrome 插件把按钮往下移了一行，不被顶上黄色的操作栏挡住了。

![46aa2648-b15b-4f61-a03b-55cde357ebbd](https://cloud.githubusercontent.com/assets/856102/13898337/ea7320bc-ee08-11e5-952c-fddbfbae8c8e.png)

**Comment by acgotaku** [comment]
@anamewing  firefox也更新了 gg~

**Comment by anamewing** [comment]
好快！
感谢~~
