### ISSUE TITLE
坏了，115似乎改版了

### ISSUE THREAD

**Issue by samlee111** [acgotaku/115#311]
20201204，导出下载无效，导出文本无反应。
20201203晚上还下过几个文件，正常可用。
早两天发现115对导出下载限速了，单个文件最高6.2MB/s，多个文件一起下可以堆叠满带宽。

简单测了一下，可能是按文件体积检测，119.95MB的文件触发下载成功，120.19MB失败。

**Comment by pxia** [comment]
```
Error handling response: TypeError: Cannot read property 'match' of undefined
    at chrome-extension://nmejofnhpfdidpciogkmmjompibkmddc/js/home.js:1:24616
```

应该是home.js里的这行错误
```
const path = data.file_url.match(/.*115.com(\/.*\/)/)[1]
```

**Comment by opfans** [comment]
> 20201204，导出下载无效，导出文本无反应。
> 20201203晚上还下过几个文件，正常可用。
> 早两天发现115对导出下载限速了，单个文件最高6.2MB/s，多个文件一起下可以堆叠满带宽。
> 
> 简单测了一下，可能是按文件体积检测，119.95MB的文件触发下载成功，120.19MB失败。

我也遇到同样的问题啊，昨天晚上还可以导出，后面就不行了，获取不到地址啊

**Comment by pxia** [comment]
115网页上的下载按钮也没有反应，似乎移除了下载功能

windows客户端也登录不上去，说安全系统升级。。

**Comment by opfans** [comment]
> 115网页上自带的下载按钮也没有反应，似乎移除了下载功能
> 
> windows客户端也登录不上去，说安全系统升级。。

下载按钮还有，客户端登不上去，不清楚，我一直没有用客户端。不知道现在用客户端下载会不会丢包了。

**Comment by IsoaSFlus** [comment]
> 115网页上自带的下载按钮也没有反应，似乎移除了下载功能
> 
> windows客户端也登录不上去，说安全系统升级。。

不会真跑路了吧。。。不应该啊十年都撑过来了

**Comment by pxia** [comment]
windows客户端用二维码登陆可以下载

**Comment by opfans** [comment]
你系统问题吧，win 客户端可以登入？



---原始邮件---
发件人: "IsoaSFlus"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 上午9:04
收件人: "acgotaku/115"<115@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [acgotaku/115] 坏了，115似乎改版了 (#311)




  
115网页上自带的下载按钮也没有反应，似乎移除了下载功能
 
windows客户端也登录不上去，说安全系统升级。。
  
不会真跑路了吧。。。不应该啊十年都撑过来了

**Comment by opfans** [comment]
刚才试了一下，几百KB 的小文件可以获取下载地址，导入到ARIA

**Comment by iwestlin** [comment]
webapi这个接口对于大文件不返回`file_url`了。。

115之前那一波促销活动看来是有备而来。。我大E了，没有闪……

**Comment by opfans** [comment]
我是618买的，500三年。我今天晚上用客户端下载。有没有批量校验sha1的软件，推荐一下。



---原始邮件---
发件人: "issue哥"<notifications@github.com&gt;
发送时间: 2020年12月5日(周六) 上午9:55
收件人: "acgotaku/115"<115@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Y3Y4"<392814736@qq.com&gt;;
主题: Re: [acgotaku/115] 坏了，115似乎改版了 (#311)




 
webapi这个接口对于大文件不返回file_url了。。
 
115之前那一波促销活动看来是有备而来。。我大E了，没有闪……

**Comment by iwestlin** [comment]
抓包看了下客户端的下载，
下载接口是 `http://proapi.115.com/app/chrome/downurl`
post请求和返回的字段都被加密了。。类似这种
{
  "state": true,
  "msg": "",
  "errno": 0,
  "data": "MG5u+9HnsF5wq4RDbxV4rfLccr7j+B6hXcJZCpKY5qthvck1O6J2HhvG1XPQyx0O0SVCfjUaBpvKfVmaAIoa+Jvr5VWXZwFPkKM58ZOnfRzagR2McTSaqLK4I4QLI6tpdIuO3hEG\/naHmX5m5U\/KabFEOwbG2bhtBn3r28HTeh4u\/cWiBxazrwVsT9MJuan+fXsDgMAb\/2gej\/v51CeJY7gq1QVnrb640MSXWiw+PZj1oT2h8sag78GNqp7p5EX1uFhZhMfCvd8iT4+4bGjinJ\/pLZobQIFFk6VeI0SWpHZQXhIjyR7u8IW62\/+ibz8KM0VdHoY4tns23xPBdVm5f4mzpGFkW9VaQn541u7\/z1BxLHtnY6ZmNfCkVNAvTUdrK8fUmtuHrwkbfgZvRhTI\/gXvpXA05QHFSoRf1B8TQk7Xl3zySXZQcJAEu474GdsSc6aWgzIymnZDlj3cdwqJgnWGknu42\/oMKDWNq5AwSQAA7PhS9r6dNsznEZ+LPskCY0LJPatuIXRf+sErnN64j0pGPho9nHolytjEn+fe6BlEjfe6r0gmz\/Y18pxmTchsNC8XwR6pOaQxLI3DzhbqSIUD+zuvcs7RqBXwuxqF1oGPJ5gB+dPA3D+AlHgZXy5J2GUVpnNG+uqDLBgZjU1Y+Ls5Z\/4dOGtG5gbvPHS0C6dETb0BsXaSiggEjmysIsn5kntnyZo5\/ktZy+J+Dxqw4EKlpnzPBObUMBf3Ac0JROWVe\/3vp1BKOkvbFCGKW\/0gTC\/R\/E6ylMW7noeP...=="
}
base64 decode之后是一串乱码，应该还需要进一步解密。
试了下这里的方法：https://github.com/T3rry7f/Fake115Upload/blob/68fe7993baf924cd3a659dd79c642a77c9f572dc/fake115upload.py#L101

解密出一堆乱码。。可能密钥或者加密方式变了

总之蹲一个逆向大佬……

**Comment by larchsis** [comment]
> 抓包看了下客户端的下载，
> 下载接口是 `http://proapi.115.com/app/chrome/downurl`
> post请求和返回的字段都被加密了。。类似这种
> 
> ```
> {
>   "state": true,
>   "msg": "",
>   "errno": 0,
>   "data": "MG5u+9HnsF5wq4RDbxV4rfLccr7j+B6hXcJZCpKY5qthvck1O6J2HhvG1XPQyx0O0SVCfjUaBpvKfVmaAIoa+Jvr5VWXZwFPkKM58ZOnfRzagR2McTSaqLK4I4QLI6tpdIuO3hEG\/naHmX5m5U\/KabFEOwbG2bhtBn3r28HTeh4u\/cWiBxazrwVsT9MJuan+fXsDgMAb\/2gej\/v51CeJY7gq1QVnrb640MSXWiw+PZj1oT2h8sag78GNqp7p5EX1uFhZhMfCvd8iT4+4bGjinJ\/pLZobQIFFk6VeI0SWpHZQXhIjyR7u8IW62\/+ibz8KM0VdHoY4tns23xPBdVm5f4mzpGFkW9VaQn541u7\/z1BxLHtnY6ZmNfCkVNAvTUdrK8fUmtuHrwkbfgZvRhTI\/gXvpXA05QHFSoRf1B8TQk7Xl3zySXZQcJAEu474GdsSc6aWgzIymnZDlj3cdwqJgnWGknu42\/oMKDWNq5AwSQAA7PhS9r6dNsznEZ+LPskCY0LJPatuIXRf+sErnN64j0pGPho9nHolytjEn+fe6BlEjfe6r0gmz\/Y18pxmTchsNC8XwR6pOaQxLI3DzhbqSIUD+zuvcs7RqBXwuxqF1oGPJ5gB+dPA3D+AlHgZXy5J2GUVpnNG+uqDLBgZjU1Y+Ls5Z\/4dOGtG5gbvPHS0C6dETb0BsXaSiggEjmysIsn5kntnyZo5\/ktZy+J+Dxqw4EKlpnzPBObUMBf3Ac0JROWVe\/3vp1BKOkvbFCGKW\/0gTC\/R\/E6ylMW7noeP...=="
> }
> ```
> 
> base64 decode之后是一串乱码，应该还需要进一步解密。
> 试了下这里的方法：https://github.com/T3rry7f/Fake115Upload/blob/68fe7993baf924cd3a659dd79c642a77c9f572dc/fake115upload.py#L101
> 
> 解密出一堆乱码。。可能密钥或者加密方式变了
> 
> 总之蹲一个逆向大佬……

还想这抓包看呢，已经有人做了。不过这个加密就挠头了，需要解密大佬看怎么处理了。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/314

重复了 关了
