### ISSUE TITLE
2020.12.5日，显示下载地址中后，ariaNG没反应。。测试版本号正常

### ISSUE THREAD

**Issue by kyrie868** [acgotaku/115#312]
![Snipaste_2020-12-05_00-06-27](https://user-images.githubusercontent.com/73956088/101186326-e8442200-368d-11eb-9b99-6f68390cef09.png)
![Snipaste_2020-12-05_00-07-11](https://user-images.githubusercontent.com/73956088/101186336-eaa67c00-368d-11eb-919a-4c7462d10a1f.png)
如图，求解

**Comment by pikachullk** [comment]
就是今天晚上改的好像,就是容量超了就一定要求你用115浏览器来下载~你就用chrome之类的点击下载就会提示你用115浏览器才能下载

**Comment by samlee111** [comment]
> 
> 
> 就是今天晚上改的好像,就是容量超了就一定要求你用115浏览器来下载~你就用chrome之类的点击下载就会提示你用115浏览器才能下载

我用的Firefox，体积超了没有提示，只是单纯的不下载，刚也发了个issue

**Comment by opfans** [comment]
我也想用115客户端下载，可惜客户端不争气，下载容易丢包，不校验SHA1。之前用ARIA2下载一直都很完整。希望作者修复一下这问题，感激不尽。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/314

重复 关了
