### ISSUE TITLE
ARIAR RPC无法获取115地址

### ISSUE THREAD

**Issue by opfans** [acgotaku/115#313]
昨天晚上2020.12.5号，ARIAR RPC无法获取115地址，导致1155文件不能用ARIA2下载

**Comment by opfans** [comment]
本想用115客户端下载，客诉客户端下载经常丢包，没有校验SHA1，所有一直用ARIA2下载，现在不能用，很着急啊，希望大神解决，谢谢。

**Comment by opfans** [comment]
发现几百KB 的小文件，可以获取地址，导入到ARIA2.大一点的文件就不行。

**Comment by larchsis** [comment]
115更新了，现在大文件必须通过客户端下载，取消了网页下载入口

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/314

重复
