### ISSUE TITLE
批量导出下载如果文件夹内有文件夹将无法正确获取下载链接

### ISSUE THREAD

**Issue by clk01** [acgotaku/115#324]
先谢谢大佬做的插件，非常好用！
但最新版本的115导出插件有点问题，如果导出的文件夹内有文件夹，将无法获取下载链接，导出文本和直接导入ARIA2都不能使用。
再次感谢！

**Comment by acgotaku** [comment]
如果有两个人以上反馈， 那确实是程序有问题。 如果只有你一个人反馈， 可能先看看是不是自己环境有问题。

**Comment by clk01** [comment]
测试过115浏览器和chrome正式版最新版，都是提示获取链接，获取后CPU会有占用提升一小下是真的，但是没反应。
如果文件夹下没有文件夹，就可以正常下载整个文件夹内的文件了。

**Comment by acgotaku** [comment]
再测测别的文件夹吧

**Comment by leixtye** [comment]
首先感谢作者的无私奉献。
clk01所反映的问题确实存在，下载目录中还有多个或多层目录时，收到提示正在生成下载，在目录遍历完成后收不到下载成功提示。
0.36版本就有这个问题，0.37也有。

**Comment by acgotaku** [comment]
@leixtye 文本导出 并贴出来数据看看 可以详细描述下目录结构

**Comment by leixtye** [comment]
@acgotaku 我试了一个不能转换到aria2-rpc的目录，点文本导出收到提示正在获取列表，目录遍历完后没有任何提示，没有文本。

**Comment by acgotaku** [comment]
@leixtye  可以打开终端 看看有没有报错

**Comment by leixtye** [comment]
@acgotaku 我用的是chrome插件，打开个终端？

**Comment by leixtye** [comment]
@acgotaku 同一个目录如果不能导出，我试过退出115再登录，有时就能导出了，但不是这样操作每次都成功。
另外，我也打开页面调试工具，不论能不能导出，都没有报错。

**Comment by acgotaku** [comment]
@leixtye 我说的就是 Chrome的 调试工具的console 面板， 如果不是稳定复现的BUG 确实很难找出来。。。

**Comment by q741451** [comment]
我这边测试正常
我怀疑有的文件夹有反斜杠，百分号，空格，星号，&，双引号这类特殊字符
也有可能运行aria2的权限不够，或者目录有诡异的粘滞这类权限设置

**Comment by leixtye** [comment]
”复杂结构目录”在任何环境都不变的情况下，就是不停点导出文本按钮，偶尔也能导出成功，应该与特殊字符无关。
简单结构、文件数目小的目录导出成功率100%，一复杂就看机率了。

**Comment by acgotaku** [comment]
上面的同学们  有人可以提供 115测试帐号 给我测试下么？ 否则我也模拟不出来这个现象。。。

我的邮箱是 acgotaku311 # gmail.com

并告诉我文件夹

**Comment by leixtye** [comment]
帐号：344081534
密码：acgotaku311
试用帐号7天有效，登录的时候可能要手机验证码，怎么发给你？

雪月秋水 <notifications@github.com> 于2020年12月15日周二 上午11:45写道：

**Comment by acgotaku** [comment]
这个问题已经修正 请下载 0.3.8 版本
