### ISSUE TITLE
0.3.7后可以成功 但是不会生成文件夹了？

### ISSUE THREAD

**Issue by vvlaw** [acgotaku/115#325]
这几天0.3.6的版本不能发送视频文件过去，但是小文件好像可以.

今天升级到最新版后可以成功发送，但是文件夹不会在Google网盘生成了，这个可以解决下吗？谢谢

**Comment by xhunterx20** [comment]
请问最新的0..3.7在哪下载？

**Comment by vvlaw** [comment]
> 请问最新的0..3.7在哪下载？

Release 里面有呀

**Comment by tanfeng** [comment]
> > 请问最新的0..3.7在哪下载？
> 
> Release 里面有呀

release里最后版本是0.3.6呢
