### ISSUE TITLE
到处链接aiar2可以下载，无法用potplayer直接播放

### ISSUE THREAD

**Issue by onceyourgong** [acgotaku/115#329]
首先感谢大神及时的推出了那么nb的插件。
aiar2的下载完全没有问题，2线程可以到27MB的速度
在chrome里面贴下载链接也是可以正常下载

但是昨天还是可以直接把链接贴到potplayer里面播放
今天发现不行了，貌似链接带了cookie的信息

请问有什么解决办法

再次感谢了

**Comment by acgotaku** [comment]
貌似没有别人遇到过这个问题？ 你先下载看吧。。。
