### ISSUE TITLE
关于115网盘无法下载大文件

### ISSUE THREAD

**Issue by xunwu659** [acgotaku/115#330]
版本为1.5.36
115 会员
Error handling response: TypeError: Cannot read property 'match' of undefined
    at chrome-extension://difokpibbkccdobfjeecjohkidanphaf/dist/inject_home.entry.js:1:13867
下载大文件就提示这个,小于20M 的文件可以直接下载.

**Comment by acgotaku** [comment]
现在最新版本也才 0.3.8, 发issue的时候 能不能先更新下版本？  不知道你的1.5.36 版本哪来的
