### ISSUE TITLE
大文件无法导出下载

### ISSUE THREAD

**Issue by lurui45** [acgotaku/115#333]
最近在出差在异地用，aria RPC里面就填了公网的地址，小文件可以导出下载，大文件（视频文件）点导出没有任何反应。。。可能是什么原因呢？

**Comment by acgotaku** [comment]
请更新到 0.3.8 版本

**Comment by lurui45** [comment]
> 请更新到 0.3.8 版本

谢谢，你的作品是我的主要下载方式，哈哈，麻烦问一下
aria可以通过ipv6连接rpc吗？
还有以后有机会在chrome商店上架吗

**Comment by acgotaku** [comment]
我没有 ipv6 环境 无法测试

不会在Chrome上架

**Comment by lurui45** [comment]
> 我没有 ipv6 环境 无法测试
> 
> 不会在 Chrome 上架

谢谢解答， 我刚才试了一下
RPC里面直接填ipv6地址是可以连接的，例如http://token:xxxx@[A:A:A:A]:6800/jsonrpc
如果填我绑定的ipv6域名就无法连接，但是我填ipv4的域名就可以连接。
不是很懂，这是什么原因呢？
