### ISSUE TITLE
请问为什么配置了RPC链接，但就是连不上呢？

### ISSUE THREAD

**Issue by ukiyo99** [acgotaku/115#334]
http://token:10912312xzxza9432daa71b60@127.0.0.1:6800/jsonrpc

是这个地址有问题吗？（IP地址用127.0.0.1替换了）
其他的Aria2插件能正常导出，比如百度网盘助手

**Comment by ukiyo99** [comment]
没仔细看大大的说明，啊啊啊啊，很抱歉！已经折腾好了！感谢大大这么牛逼的工具！

**Comment by ukiyo99** [comment]
新问题…………点了导出，Aria2上没有反应，测试上也显示版本号了……

**Comment by acgotaku** [comment]
更新到 0.3.8 版本
