### ISSUE TITLE
M1版Mac mini 解析出的aria2链接有误

### ISSUE THREAD

**Issue by lootali** [acgotaku/115#336]
M1版Mac mini 上安装的最新115插件，解析出的文件aria2链接有误，无法下载，直接停止
在非M1版的Mac book上就可以正常解析下载，相同文件对比解析出的链接后发现就最后等号后的一段不一样

M1版解析链接
http://cdnfhnfile.115.com/5fd8e293f8bd2f294cf463f0e90c90d7f3b4f136/Cinema.Paradiso.1988.mkv?t=1613247433&u=341914179&s=13107200&d=vip-1927425337-bcps6khveu6zp8lby-1&c=2&f=1&k=61d55801f4d92199fa3d74b1d67d44cc

非M1版解析链接
http://cdnfhnfile.115.com/5fd8e293f8bd2f294cf463f0e90c90d7f3b4f136/Cinema.Paradiso.1988.mkv?t=1613247642&u=341914179&s=13107200&d=vip-1927425337-bcps6khveu6zp8lby-1&c=2&f=1&k=72ff690d4422289f9eba22e4ac64e865

**Comment by acgotaku** [comment]
我没有 M1 设备 无法测试
