### ISSUE TITLE
为啥没有反映了？不好用了？

### ISSUE THREAD

**Issue by hyy34** [acgotaku/115#339]
显示正在获取下载地址之后就开启的aria2没有下载，在设置里测试连接，可以看到版本号。。。
额，小文件可以，难道限制下载了？？

**Comment by acgotaku** [comment]
你看看自己有没有 更新到 0.3.8 版本

**Comment by boluohong** [comment]
> 你看看自己有没有 更新到 0.3.8 版本

请问作者，只看到0.36的版本，没找到0.38的版本啊。
我目前也是用的0.36的版本，和上面的提问者一样，已连接显示版本号，但是点了下载之后没反应

**Comment by acgotaku** [comment]
@boluohong https://github.com/acgotaku/115/tree/master/release
