### ISSUE TITLE
115客户端最新版本24.0禁用115下载助手

### ISSUE THREAD

**Issue by gexiaopeng** [acgotaku/115#341]
刚才下载了最新的115客户端,提示禁用了115下载助手。

**Comment by gexiaopeng** [comment]
虽然24.0版本可以在开发者模式下安装115下载助手插件，但我试了一下无法获取到下载地址，也就是无法通过115下载助手下载文件了，115客户端大家谨慎升级到24.0版本。

**Comment by gexiaopeng** [comment]
我卸载了24.0版本，重新安装以前的23版本还是可以用115下载助手的。

**Comment by acgotaku** [comment]
本插件只 官方支持 Chrome 浏览器 你就别在这喊了
