### ISSUE TITLE
115浏览器(24.0.0.32)使用最新版115下载助手无法获取下载链接

### ISSUE THREAD

**Issue by microka** [acgotaku/115#342]
更新至115浏览器最新版（24.0.0.32）后，通过crx文件安装的115下载助手被禁止使用了，只能通过开发者模式加载文件夹来使用。但是下载助手UA设置为浏览器自带的“mozilla/5.0 (windows nt 10.0; wow64) applewebkit/537.36 (khtml, like gecko) chrome/83.0.4103.61 safari/537.36 115browser/24.0.0”或使用下载助手预设的“Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3”都无法成功获取文件下载连接。

**Comment by acgotaku** [comment]
我只 官方支持 Chrome 浏览器
