### ISSUE TITLE
secret中含有某些符号导致错误

### ISSUE THREAD

**Issue by xcgx** [acgotaku/115#349]
secret中含有某些符号导致错误
如< >等
例：
secret为< abc >
名称为xyz
配置为http://token:< abc >@127.0.0.1:6800/jsonrpc （无空格，GitHub上貌似也表示隐藏或格式符？）
列表中名称会变为@127.0.0.1:6800/jsonrpc>xxx
估计是此符号涉及到语法判断？

**Comment by acgotaku** [comment]
是的 不用特殊符号 密码强度也足够了吧 何必这样折腾

**Comment by acgotaku** [comment]
URL 格式是有 标准的，非法的URL是无法解析的， 这方面我也不打算做特殊对应
