### ISSUE TITLE
指向没有问题，可是就是说aria2没有开启

### ISSUE THREAD

**Issue by lanechang** [acgotaku/115#350]
![360截图20210124151842379](https://user-images.githubusercontent.com/77914126/105623795-8fa43080-5e57-11eb-888d-5ef4955a109e.jpg)
![360截图20210124151858551](https://user-images.githubusercontent.com/77914126/105623796-9337b780-5e57-11eb-8408-1259fc5d527a.jpg)
![360截图20210124152036195](https://user-images.githubusercontent.com/77914126/105623818-ba8e8480-5e57-11eb-9a12-8e08263eed59.jpg)

指向没有问题，可是就是说aria2没有开启，版本的是0.38，请大神帮助一下。

**Comment by lanechang** [comment]
搞定了，原来是忘了加token了。。。。

**Comment by acgotaku** [comment]
...
