### ISSUE TITLE
是不是aria2无法下载了？

### ISSUE THREAD

**Issue by yuqoo** [acgotaku/115#356]
最近想下载115网盘的文件，但是能获得下载链接也可以发送到aria2的，但是无法下载文件，错误提示： -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: Error: 由于吊销服务器已脱机，吊销功能无法检查吊销。
(80092013)

**Comment by yuqoo** [comment]
![image](https://user-images.githubusercontent.com/48486265/107037514-2678d180-67f6-11eb-9962-3a009ea686f6.png)

**Comment by yuqoo** [comment]
![image](https://user-images.githubusercontent.com/48486265/107037820-9a1ade80-67f6-11eb-9ae5-1ff6cfd9cc50.png)

**Comment by yuqoo** [comment]
![Uploading image.png…]()

**Comment by yuqoo** [comment]
![image](https://user-images.githubusercontent.com/48486265/107037934-c7678c80-67f6-11eb-9ac4-5e3f876d6714.png)

**Comment by acgotaku** [comment]
请检查自己网络

**Comment by yuqoo** [comment]
> 请检查自己网络

查到原因了，是因为电脑的clash代理造成无法下载
