### ISSUE TITLE
115网页界面改版后，按钮位置错误

### ISSUE THREAD

**Issue by Dragon-Yu** [acgotaku/115#38]
115网页改版后，按钮会出现在界面的左上角，与原本的新建下载按钮几乎重合。
希望作者可以修复。

**Comment by acgotaku** [comment]
115这家伙就知道天天改UI。。。。

**Comment by Dragon-Yu** [comment]
后来又试了下，发现在文件夹中选择要下载的文件后，115会在顶部显示一排按钮，于是插件的按钮被完全覆盖了。另外，请问这个下115一般能到什么速度，我只能达到直接用浏览器的2倍。

**Comment by acgotaku** [comment]
因为115服务器 限速了 只有冲钱才能变快。。。

**Comment by yuhang316** [comment]
115下载助手一直aria出错，百度云助手，YAAW for chrome都没问题

**Comment by Haixing-Hu** [comment]
已经修复，请参考我的pull request
