### ISSUE TITLE
导出下载按钮的位置挡住了删除按钮

### ISSUE THREAD

**Issue by falltree** [acgotaku/115#389]
当前版本0.3.8，115浏览器版本23.9.2.1
插件工作正常，可以将文件推送至aria2下载，但是导出下载按钮的位置有些尴尬。
有些目录里面存在一些不需要的文件，如果要删除这些不要的文件，多选之后，删除按钮正好被导出下载给挡住。
只能一个文件单选，此时删除按钮的就出现在导出下载的右边，可以点击删除文件。当目录下有很多不要的文件准备删除时，一个一个删除就比较繁琐了。

最好是把导出按钮的位置调整到最右边空白的位置，这样就不会和115自带的按钮位置产生冲突。

**Comment by acgotaku** [comment]
这么说 确实是， 我有空改正下。

**Comment by acgotaku** [comment]
调整好了， 可以试试最新的 0.3.9
