### ISSUE TITLE
改了rpc地址，测试一直没反应，报错误

### ISSUE THREAD

**Issue by wolifutengqq** [acgotaku/115#392]
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
上下文
https://115.com/?cid=2074123994931396081&offset=0&tab=&mode=wangpan
堆叠追踪

**Comment by wolifutengqq** [comment]
之前还是好的，一个月不行了，就是点测试连接的时候没反应，也传不过去。

**Comment by acgotaku** [comment]
可能你的浏览器版本太老了吧， 记得升级
