### ISSUE TITLE
某些任务下载列表无法完全获取

### ISSUE THREAD

**Issue by poplarch** [acgotaku/115#4]
比如这个磁力链接 magnet:?xt=urn:btih:T77HZWFXFTX45CYNU7K3SUTBZYTZTBYZ
只能获取其中一部分链接
任务数是103，实际只能获取到20个
OS: Mac OS X 10.10.3
Browser: Chrome 版本 40.0.2214.111 (64-bit)

**Comment by acgotaku** [comment]
@poplarch 反馈已经收到 确实有这个问题 我会尽快修复的

**Comment by acgotaku** [comment]
@poplarch 已经修复 更新到 0.0.4版本即可

**Comment by poplarch** [comment]
应该是正常了，感谢:) 同时祝新年快乐

**Comment by acgotaku** [comment]
@poplarch 新年快乐～
