### ISSUE TITLE
ass格式的文件下载出错

### ISSUE THREAD

**Issue by himarrin** [acgotaku/115#417]
115大文件下载正常，只有ass字幕文件下载直接报错

**Comment by OUZYcn** [comment]
请问那个浏览器，什么版本？ 插件的版本又是多少？我来复现一下

**Comment by himarrin** [comment]
> 请问那个浏览器，什么版本？ 插件的版本又是多少？我来复现一下

chrome90，插件设置页面显示的版本是0.3.9，aria2的版本是1.34.0
