### ISSUE TITLE
近期115页面无法加载插件了

### ISSUE THREAD

**Issue by OUZYcn** [acgotaku/115#418]
Chrome base 
115浏览器，v24.1.0.10  可以在开发者模式导入插件。 115.com页面可以加载插件，但是无法正确获取下载链接
edge  90.0.818.66 可以在开发者模式导入插件。115.com页面无法加载插件。 

可否更新一下呢？谢谢！！

**Comment by acgotaku** [comment]
我只 支持Chrome浏览器， 你拿别的浏览器来用 我也没啥办法啊

**Comment by ytzong** [comment]
@acgotaku Chrome  91.0.4472.77 也用不了了

**Comment by OUZYcn** [comment]
Chrome Version 90.0.4430.72 (Official Build) (64-bit)
可以工作。。。

**Comment by FLTJones** [comment]
我也是用不了了显示为该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by jutongpan** [comment]
> @acgotaku Chrome 91.0.4472.77 也用不了了

一样，Chrome 91.0.4472.77用不了，没有显示加载成功，按钮图标也没有出现。Chrome更新前可正常

**Comment by liunice** [comment]
我的也用不了，按钮显示错位，点了没反映，看了下控制台是有报错的

**Comment by zzzop** [comment]
能用 chrome 91.0.4472.77

**Comment by jutongpan** [comment]
> > @acgotaku Chrome 91.0.4472.77 也用不了了
> 
> 一样，Chrome 91.0.4472.77用不了，没有显示加载成功，按钮图标也没有出现。Chrome更新前是正常可用的

近日升级到91.0.4472.124后又正常了，加载成功

**Comment by FLTJones** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
