### ISSUE TITLE
大家最近115到Aria2的速度多少

### ISSUE THREAD

**Issue by iroi1984** [acgotaku/115#422]
之前基本可以跑满500M宽带，用的大佬插件
现在最高100Mbps了。

**Comment by zzzop** [comment]
牛蛙，你aria2之前都能500m？115按理说限制连接数，没见过那么快，100m很正常

**Comment by iroi1984** [comment]
> 牛蛙，你aria2之前都能500m？115按理说限制连接数，没见过那么快，100m很正常

是的，我是跑在群晖Docker上的，之前如果4部片子一起下载是可以到60MB/s左右

**Comment by crazyshitass** [comment]
1000m宽带，多任务最多跑满200m，然后降速，唉，好日子一去不复返

**Comment by linker999** [comment]
看来不是我一个人的问题呀，之前是多任务跑满带宽，现在最高100M带宽。。。

**Comment by ansonhorse** [comment]
> 看来不是我一个人的问题呀，之前是多任务跑满带宽，现在最高100M带宽。。。

请问你们最近这几天都可以用？我能找到的脚本版本是 0.2.1，不可以用，提示“很抱歉，提取码不能为空”。是有其他什么途径获取较新版本的脚本吗？我看到有一个telegram的群还是什么（group115comment），但telegram提示这个不存在。

**Comment by ansonhorse** [comment]
> > 看来不是我一个人的问题呀，之前是多任务跑满带宽，现在最高100M带宽。。。
> 
> 请问你们最近这几天都可以用？我能找到的脚本版本是 0.2.1，不可以用，提示“很抱歉，提取码不能为空”。是有其他什么途径获取较新版本的脚本吗？我看到有一个telegram的群还是什么（group115comment），但telegram提示这个不存在。

不好意思，把这个跟另一个脚本搞混了。测试了一下，这个扩展确实可以下小文件。

**Comment by iroi1984** [comment]
> 看来不是我一个人的问题呀，之前是多任务跑满带宽，现在最高100M带宽。。。

抱歉，是我自己无论了，我是楼主，原因找到了，是因为我家路由器和交换机之间的线破损了，变100M线了，现在换了先，5个文件一起下载，可以吃满500M了

**Comment by ansonhorse** [comment]
@iroi1984 能提示一下从哪里找到能用的版本么？
