### ISSUE TITLE
115无法下载 检测显示版本正常

### ISSUE THREAD

**Issue by ichali** [acgotaku/115#423]
环境: Chrome  91.0.4472.77 插件内测试 显示版本正常 1.35.0

选中文件后，点击导出下载，提示正在获取下载地址，然后没有反应，aria后端没有下载任务
文本导出功能也无法使用

这几天突然出现问题，期间没有修改配置
谢谢啦

**Comment by liunice** [comment]
我的也是这样

**Comment by ichali** [comment]
> 我的也是这样

删除插件重新安装后可以解决了
