### ISSUE TITLE
Aria2 连接成功 点击下载后Aria2接收不到任务

### ISSUE THREAD

**Issue by StefanZhang** [acgotaku/115#428]
你好，
我是Mac chrome 版本号91.0.4472.114 
Aria2 是配置在VPS上，本地提交任务都可以下载成功
在您的插件上配置了Aria2的信息，显示连接成功
点击下载或者是文本导出都是显示正在获取下载地址，然后什么也没有发生... Aria2并没有收到任务
请问这种情况需要做什么特殊的设置吗？

**Comment by liunice** [comment]
我跟楼主一模一样的情况，也是MAC chrome V91
看了下控制台，报错如下：
115.com/:1 Error handling response: TypeError: Cannot read property 'match' of undefined
    at chrome-extension://noinmigdikjdgabliopkbadajncfbbba/js/home.js:1:24048

**Comment by acgotaku** [comment]
> chrome-extension://noinmigdikjdgabliopkbadajncfbbba/js/home.js:1:24048

这个可以展开截图看看么？

**Comment by StefanZhang** [comment]
我也看到这个了，
115.com/:1 Error handling response: TypeError: Cannot read property 'match' of undefined
    at chrome-extension://dmdmhlcbkcalabmbmngnieolopklfmce/js/home.js:1:24048
点进去以后显示这一行有问题：
var t = e.file_url.match(/.*115.com(\/.*\/)/)[1];

**Comment by liunice** [comment]
@acgotaku 我来两张截图，第一张是按钮布局错位，第二张是错误代码行
<img width="845" alt="1" src="https://user-images.githubusercontent.com/224557/125882553-07958482-2138-4650-b16d-263cafa0ae6b.png">
<img width="898" alt="2" src="https://user-images.githubusercontent.com/224557/125882566-e327e8b4-8268-4bbc-ab66-70c363495f6a.png">

**Comment by otakustay** [comment]
超过尺寸限制的无法下载，不返回`file_url`

**Comment by liunice** [comment]
@otakustay  能下载的最大尺寸是多少？

**Comment by acgotaku** [comment]
看看你自己是否使用了隐身模式，以及是否充VIP了。。。

**Comment by StefanZhang** [comment]
> 看看你自己是否使用了隐身模式，以及是否充VIP了。。。

没有开隐身，开了VIP

**Comment by eeoa** [comment]
https://github.com/acgotaku/115/blob/01d7d63ebec6a5d1206a861d003f258a86756ae2/background.js
或者crx解压后的background.js文件第85行
```javascript
chrome.cookies.getAll(detail, resolve)
```
改成
```javascript
chrome.cookies.getAll({url:"https://115.com"}, resolve)
```
就能好，不要问我为什么，js我也不懂

**Comment by StefanZhang** [comment]
> https://github.com/acgotaku/115/blob/01d7d63ebec6a5d1206a861d003f258a86756ae2/background.js
> 或者crx解压后的background.js文件第58行
> 
> ```js
> chrome.cookies.getAll(detail, resolve)
> ```
> 
> 改成
> 
> ```js
> chrome.cookies.getAll({url:"https://115.com"}, resolve)
> ```
> 
> 就能好，不要问我为什么，js我也不懂

你好，这个background.js 是改根目录里面的还是release文件夹里面的呢？

**Comment by liunice** [comment]
@eeoa 哥们，首先感谢。不过我改了还是一样的报错。你确定你是这样改的吗？

**Comment by eeoa** [comment]
破案了，不要下载Releases里的0.3.6版本，那个很老了根本用不了。要用代码仓库里release文件夹的0.3.9版本。通过chrome的“加载解压缩的扩展”添加release文件夹。刚才试了一下是可以使用的。同时建议作者去掉Releases和Tags吧，避免不必要的误会。

**Comment by liunice** [comment]
@eeoa 我靠太感谢了，终于可以了！

**Comment by StefanZhang** [comment]
@eeoa 谢谢大佬，我这边也可以了，速度拔群

**Comment by liunice** [comment]
@eeoa 请教一下，我发现单个文件好像被限速到最高15MB/S？这个有办法突破吗？

**Comment by eeoa** [comment]
@liunice 同时下载多个文件😔

**Comment by zzzop** [comment]
> @eeoa 请教一下，我发现单个文件好像被限速到最高15MB/S？这个有办法突破吗？

115服务器限速的，有时候10m都没有

**Comment by YLaido** [comment]
请问问题是否还存在？我这里仍然能够复现，首次登录能够一次下载150个文件，但之后就无法获得其他链接。
进行文本导出时抓包显示 `405 Not Allowed`。返回的是 html，当中包含一句话：**很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。**

Post URL: https://proapi.115.com/app/chrome

作者可以抽空测试一下吗？感谢~

**Comment by sachindjj** [comment]
> se folder in the code repository

where I can get 0.3.9, also can someone provide detailed guide on how to export download links to aria2c-rpc.
