### ISSUE TITLE
8.1开始，115官方客户端装控件也下载不了咯

### ISSUE THREAD

**Issue by gz0007** [acgotaku/115#43]
7.31之前在115客户端装上for chrome控件是能正常使用的，求解决办法。

**Comment by acgotaku** [comment]
我抽空看看

**Comment by gz0007** [comment]
6.0.5.29版的115暂时还可以用到你的控件，但新装的115浏览器已经是7.0版，用不了你的控件了，我今天试过

**Comment by gz0007** [comment]
我后来测试来测试去，发现不是浏览器版本问题，而是是这个问题对115的控件造成阻碍（http://ask.csdn.net/questions/206965），按连接中的办法设置好115浏览器的快捷方式后就又能正常使用了，bingo！
