### ISSUE TITLE
功能建议：检查链接是否成功导出

### ISSUE THREAD

**Issue by zzzop** [acgotaku/115#439]
文件数较多时，例如100-200个左右的文件，文本导出结果会缺失，我反复检查了之后发现，不是文件不能下载，可能是获取链接失败了？猜测和115秒传链接导出失败一个原因？
是否可以做一个链接导出失败重试的功能？或者是最后显示错误文件路径的功能，可以供复制和索引

**Comment by acgotaku** [comment]
本插件只负责导出，检查链接这个功能比较复杂。 目前没有这个时间来做。
有下载失败的情况，就再导出一次就是了。。。

**Comment by zzzop** [comment]
> 本插件只负责导出，检查链接这个功能比较复杂。 目前没有这个时间来做。
> 有下载失败的情况，就再导出一次就是了。。。

明白，现在的困扰是再导出一次还是有缺失，目前的方法是设置aria2不自动重命名，多次导出基本可以补全。
功能的话只是显示一下没有导出的文件路径就可以，主要是想知道哪个链接缺失了，检查链接也不是刚需❤
如果很复杂就不麻烦大佬啦
