### ISSUE TITLE
Google Chrome  92.0.4515.131 下点击下载无反应，选择文本导出内容为空

### ISSUE THREAD

**Issue by tyhunter** [acgotaku/115#442]
辛苦大佬看下115是不是又改逻辑了

**Comment by guochan2019** [comment]
同样问题，已经出现两天了，新版表现为点击下载没反应，但期间试了旧版的0.3.6反而可以了，不过下载几个文件后会自动退出登录

**Comment by zzzop** [comment]
版本 92.0.4515.131（正式版本） （64 位）
0.3.9我没问题呀

**Comment by guochan2019** [comment]
> 版本 92.0.4515.131（正式版本） （64 位）
> 0.3.9我没问题呀

刚登录上去第一次下载有时是可以的，但你继续试试，并且好像不能一次选太多文件，尤其是文件夹

**Comment by zzzop** [comment]
> > 版本 92.0.4515.131（正式版本） （64 位）
> > 0.3.9我没问题呀
> 
> 刚登录上去第一次下载有时是可以的，但你继续试试，并且好像不能一次选太多文件，尤其是文件夹

我选了个多层文件夹，下了一百个文件，没问题呀

**Comment by zzzop** [comment]
难道是有什么阈值设置？

**Comment by zzzop** [comment]
> > 版本 92.0.4515.131（正式版本） （64 位）
> > 0.3.9我没问题呀
> 
> 刚登录上去第一次下载有时是可以的，但你继续试试，并且好像不能一次选太多文件，尤其是文件夹

那你秒传链接那种还能用吗

**Comment by guochan2019** [comment]
> > > 版本 92.0.4515.131（正式版本） （64 位）
> > > 0.3.9我没问题呀
> > 
> > 
> > 刚登录上去第一次下载有时是可以的，但你继续试试，并且好像不能一次选太多文件，尤其是文件夹
> 
> 那你秒传链接那种还能用吗

称传可以用，现在是aria2下载不行，目前老版0.3.6下小文件可以

**Comment by 10362227** [comment]
一样不行

**Comment by zzzop** [comment]
就是115限制了，秒传链接导出也被限制了，还有115的错误提示

**Comment by sarkrui** [comment]
> 就是 115 限制了，秒传链接导出也被限制了，还有 115 的错误提示

同意。退出 Chrome 后，重新登陆后第一次下载能成功，第二次下载就无法获取下载直链了。

**Comment by fuxin052** [comment]
8月8日时我发现获取下载直连的接口报错了, 提示提取码不能为空, 应该是115改了接口逻辑, 但是老版本115浏览器依然可以正常下载, 看了半天js, 获取直连的逻辑被封装在浏览器里, 完全没办法搞

**Comment by sarkrui** [comment]
退出登陆后重新登入，完成第一次导出下载之后就不能对其他文件导出下载了；但每天重复登陆太多次会被限制登入，需要换个ip重新登陆…😩

**Comment by zzzop** [comment]
各位有没有经验间隔时间限制多少不会被限制，今天下载1000个文件设置间隔1000ms下了300个就停了
