### ISSUE TITLE
好像还是被115限速了

### ISSUE THREAD

**Issue by zchujuz** [acgotaku/115#452]
折腾了一个多小时终于下载了最新版，但是1.27G的文件配合软件提取到Aria2速度只有190-200KB，

有朋友也遇到这类问题吗

**Comment by Chris0256** [comment]
一樣 白嫖這就是極限了吧
有這速度還可以吧...

**Comment by acgotaku** [comment]
不充会员怎么能变强，本插件只是导出，不是破解限速。
