### ISSUE TITLE
不能下载文件夹；

### ISSUE THREAD

**Issue by Jay54520** [acgotaku/115#46]
首先感谢作者，很有效果，能达到宽带的下载速度上限。下面是我的问题与建议。

我一开始一直尝试下载文件夹，就像 115 浏览器 下载一样，但是没有任何反应。
然后我尝试下载单个文件，发现能行。
我的问题是：
是否只支持选中文件然后下载，不支持文件夹下载？
    如果是的话：能不能增加下载文件夹的功能，因为下载不同文件夹还需要每次去插件设置中设置目录，并且选择也比较麻烦，如果分了多页的话。

**Comment by acgotaku** [comment]
文件夹下载是支持的 但是长时间没维护了 估计有问题了吧

**Comment by Haixing-Hu** [comment]
好吧，待我明天来研究一下，看看能否fix...
最近折腾了一台gen8，需要给大姐姐们搬家，要是不能下载目录就太麻烦了……

**Comment by acgotaku** [comment]
我测试了 能下载文件夹 是不能下载200个？

**Comment by Haixing-Hu** [comment]
我也测试了，确实不能下载目录啊

**Comment by Haixing-Hu** [comment]
经测试，Chrome中确实不能下载目录。不过我已经打了补丁，提交了pull request  (#59)
