### ISSUE TITLE
重复下载

### ISSUE THREAD

**Issue by Jay54520** [acgotaku/115#47]
我发现如果多次点击，会重复下载。需要在 Aria2 Web 方面检查还是其他方法？

**Comment by acgotaku** [comment]
自己别点 多次不就好了。。。

**Comment by z3896823** [comment]
据我使用来看，正常点击也会重复下载，后缀.1,.2这样子

**Comment by acgotaku** [comment]
@z3896823 录制个小视频看看？

**Comment by z3896823** [comment]
已经录了，在项目中没找到你的邮箱，可否回复下邮箱，我发给你

**Comment by gykpro** [comment]
我也有这个问题，chrome 69，控制台里看必发4个请求，aria2里也下了4个
