### ISSUE TITLE
115插件是不是不支持新版的Google Chrome浏览器？安装上去提示非法

### ISSUE THREAD

**Issue by soildshow** [acgotaku/115#470]
115插件是不是不支持新版的Google Chrome浏览器？安装上去提示非法

**Comment by 1265578519** [comment]
谷歌商店被强制下架了
你可以打开插件开发者模式
然后直接解压crx文件为文件夹，然后选择加载文件夹即可正常使用插件

**Comment by soildshow** [comment]
> 谷歌商店被强制下架了 你可以打开插件开发者模式 然后直接解压crx文件为文件夹，然后选择加载文件夹即可正常使用插件

你好!请问在哪下载压缩的插件？在这里我只找到CRX文件，谢谢

**Comment by acgotaku** [comment]
@soildshow 开发者模式 直接导入这个文件夹 https://github.com/acgotaku/115/tree/master/release
