### ISSUE TITLE
115下载很多文件一段时间后就报错

### ISSUE THREAD

**Issue by liangyue13** [acgotaku/115#48]
一起下载很多个文件 20+， 一两个小时没下载好的话， aria2就显示 http response header was bad or unexpected。 有些是正在下载的 有些是waiting 的都会报错然后停了。重新开始还是报错。

是下载链接过期了吗？
那链接有效期是多久？
如果有vip是不是好点

还有aria2 怎么样从下载目录里看文件是不是下载完了
有没有像例如迅雷没下载完的就是.td结尾

**Comment by liangyue13** [comment]
IOS 115客户端是一直登陆状态，不用每次登录可不可以用里面的cookie跟过期时间有关系吗？

从iOS 115客户端目录看到有个Cookies.binarycookies 提取出来
Cookie : ssov_21013667=1_21013667_7834cabbb1f6affc19a7baad7c9baae4; domain=.115.com; path=/; expires=Wed, 24 Feb 2016;

**Comment by acgotaku** [comment]
估计是下载链接过期的原因  重新导入新的链接就好

**Comment by ODtian** [comment]
批量下载必有错误 而且跟时间没关系 全部都是“HTTP response header was bad or unexpected”
