### ISSUE TITLE
蓝光原盘文件夹下载问题

### ISSUE THREAD

**Issue by crazyshitass** [acgotaku/115#486]
蓝光原盘的文件夹文件很多很散，直接用“导出下载”貌似会被后台限制下载数量，导致文件下载数量不齐，而且还直接限制一段时间无法导出任务。

**Comment by acgotaku** [comment]
我自己也买不起 115 会员， 这个问题也不好测试

**Comment by zzzop** [comment]
> 我自己也买不起 115 会员， 这个问题也不好测试

大概是100个文件左右，现在115sha1的导出导入也是加了间隔时间。特别希望如果插件能加入导出文件时间间隔，应该能解决这个问题。现在应该是只有文件夹间隔。

**Comment by crazyshitass** [comment]
> 

专业人士，期待完善

**Comment by microka** [comment]
一个思路：大文件通过aria2下载，其它文件/文件夹通过115下载。
