### ISSUE TITLE
文件名带&符号，aria2c -o 重命名文件时被替换成&amp;

### ISSUE THREAD

**Issue by poplarch** [acgotaku/115#5]
OS: Mac OS X 10.10.3
Browser: Firefox 35.0.1
例如这个磁力链接 magnet:?xt=urn:btih:OOMLXYAHSFSBVHRFUFDSXOVEIOOISGXF

**Comment by acgotaku** [comment]
@poplarch BUG已经修复 更新到0.0.5版本即可
