### ISSUE TITLE
插件在FF 47.0中好像已经失效！

### ISSUE THREAD

**Issue by twinfishxixi** [acgotaku/115#50]
最近发现用于FireFox的115插件已经失效，打开115主界面后，没有“导出下载”和“RPC下载”按钮，另外在帐号设置下面也没有“插件设置”的按钮了，同样的使用Chrome浏览器就没有问题，请大神检查！

谢谢！～
## 应用程序概要

名称: Firefox
版本: 47.0
版本 ID: 20160606114238
用户代理: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0
操作系统: Linux 4.2.0-42-generic x86-64
多进程窗口: 0/1（已禁用）
安全模式: false
## 近3天的崩溃报告

全部崩溃报告
## 扩展

名称: 115Exporter
版本: 0.1.4
启用: true
ID: @115-exporter

名称: 会话管理器
版本: 0.8.1.12
启用: true
ID: {1280606b-2510-4fe0-97ef-9b5a22eafe30}

名称: Adblock Plus
版本: 2.7.3
启用: true
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

名称: Adblock Plus 元素隐藏辅助工具
版本: 1.3.9
启用: true
ID: elemhidehelper@adblockplus.org

名称: Adblock Plus Pop-up Addon
版本: 0.9.2.1-signed.1-signed
启用: true
ID: adblockpopups@jessehakanen.net

名称: AutoProxy Fix
版本: 0.4b2.2013051811.5
启用: true
ID: autoproxy_fix@autoproxy.org

名称: BaiduExporter
版本: 0.7.2
启用: true
ID: acgotaku311@gmail.com

名称: Bookmark Current Tab Set
版本: 0.2.4.1-signed.1-signed
启用: true
ID: bookmarkcurrenttabset@jake.kasprzak.ca

名称: ChmFox
版本: 2.10.1-signed.1-signed
启用: true
ID: chmfox@zhuoqiang.me

名称: Classic Theme Restorer
版本: 1.5.6
启用: true
ID: ClassicThemeRestorer@ArisT2Noia4dev

名称: Clean Links
版本: 2.7.1-signed.1-signed
启用: true
ID: {158d7cb3-7039-4a75-8e0b-3bd0a464edd2}

名称: Download Manager Tweak
版本: 1.0.10
启用: true
ID: {F8A55C97-3DB6-4961-A81D-0DE0080E53CB}

名称: DownThemAll!
版本: 3.0.6
启用: true
ID: {DDC359D1-844A-42a7-9AA1-88A850A938A8}

名称: DownThemAll! AntiContainer
版本: 1.5
启用: true
ID: anticontainer@downthemall.net

名称: Exif Viewer
版本: 2.00.1-signed.1-signed
启用: true
ID: exif_viewer@mozilla.doslash.org

名称: Firebug
版本: 2.0.17
启用: true
ID: firebug@software.joehewitt.com

名称: Firefox Hello
版本: 1.3.2
启用: true
ID: loop@mozilla.org

名称: FlashGot
版本: 1.5.6.13
启用: true
ID: {19503e42-ca3c-4c27-b1e2-9cdb2170ee34}

名称: Forecastfox (fix version)
版本: 2.4.8
启用: true
ID: forecastfox@s3_fix_version

名称: Greasefire2
版本: 2.1.1
启用: true
ID: greasefire2@b0nk3rz.net

名称: Greasemonkey
版本: 3.9
启用: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

名称: HTTPS Everywhere
版本: 5.2.4
启用: true
ID: https-everywhere-eff@eff.org

名称: Location Bar Enhancer
版本: 5.3
启用: true
ID: UIEnhancer@girishsharma

名称: MEGA
版本: 3.5.2
启用: true
ID: firefox@mega.co.nz

名称: MinimizeToTray revived (MinTrayR)
版本: 1.3.2
启用: true
ID: mintrayr@tn123.ath.cx

名称: Multi-process staged rollout
版本: 1.0
启用: true
ID: e10srollout@mozilla.org

名称: Nimbus Screen Capture - editable screenshots.
版本: 9.1.1
启用: true
ID: nimbusscreencaptureff@everhelper.me

名称: NoScript
版本: 2.9.0.14
启用: true
ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

名称: Pocket
版本: 1.0.2
启用: true
ID: firefox@getpocket.com

名称: Show Location
版本: 0.7.2.1-signed.1-signed
启用: true
ID: {10228D1E-6D25-4ccc-903E-272D66EEC763}

名称: Tab Groups
版本: 2.0.1
启用: true
ID: tabgroups@quicksaver

名称: Tab Mix Plus
版本: 0.5.0.0
启用: true
ID: {dc572301-7619-498c-a57d-39143191b318}

名称: The Addon Bar (restored)
版本: 3.2.9-compat-fixed-4
启用: true
ID: the-addon-bar@GeekInTraining-GiT

名称: Torrent Finder Toolbar
版本: 1.3.1.1-signed.1-signed
启用: true
ID: TFToolbarX@torrent-finder

名称: WOT
版本: 20151208
启用: true
ID: {a0d7ccb3-214d-498b-b4aa-0e8fda9a7bf7}

名称: Abduction!
版本: 3.5.0.1-signed.1-signed
启用: false
ID: {b0e1b4a6-2c6f-4e99-94f2-8e625d7ae255}

名称: Ease Link
版本: 1.0.2.5.1-signed.1-signed
启用: false
ID: easelink@ashi.cn

名称: Extended Statusbar
版本: 2.0.5
启用: false
ID: {daf44bf7-a45e-4450-979c-91cf07434c3d}

名称: Magic Actions for YouTube™
版本: 6.8.8.8
启用: false
ID: jid0-UVAeBCfd34Kk5usS8A1CBiobvM8@jetpack

名称: Pan
版本: 2.7.1.1
启用: false
ID: {A065A84F-95B6-433A-A0C8-4C040B77CE8A}

名称: Scriptish
版本: 0.1.11.1-signed.1-signed
启用: false
ID: scriptish@erikvold.com

名称: SkipScreen
版本: 0.7.2.1-signed.1-signed
启用: false
ID: SkipScreen@SkipScreen

名称: Ubuntu Modifications
版本: 3.2
启用: false
ID: ubufox@ubuntu.com

名称: xThunder
版本: 1.3.4.1-signed.1-signed
启用: false
ID: xthunder@lshai.com

名称: YouTube ALL HTML5
版本: 3.0.3
启用: false
ID: jid1-qj0w91o64N7Eeg@jetpack
## 图像

厂商 ID: Intel Open Source Technology Center
驱动程序版本: 2.1 Mesa 11.0.2
设备 ID: Mesa DRI Intel(R) G41
适配器描述: Intel Open Source Technology Center -- Mesa DRI Intel(R) G41
异步平移/缩放: 无
支持 H264 硬件解码: No
GPU 加速窗口: 0/1 Basic (OMTC)
WebGL 渲染器: Intel Open Source Technology Center -- Mesa DRI Intel(R) G41
windowLayerManagerRemote: true
AzureCanvasAccelerated: 0
AzureCanvasBackend: cairo
AzureContentBackend: cairo
AzureFallbackCanvasBackend: none
CairoUseXRender: 0
## 修改过的重要首选项

accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.capacity: 358400
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size_cached_value: 358400
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.frecency_experiment: 1
browser.download.importedFromSqlite: true
browser.download.manager.alertOnEXEOpen: true
browser.download.manager.closeWhenDone: false
browser.download.manager.showWhenStarting: false
browser.download.useDownloadDir: false
browser.link.open_newwindow.restriction: 0
browser.places.smartBookmarksVersion: 7
browser.search.useDBForOrder: true
browser.sessionstore.max_tabs_undo: 50
browser.sessionstore.upgradeBackup.latestBuildID: 20160606114238
browser.startup.homepage: about:blank
browser.startup.homepage_override.buildID: 20160606114238
browser.startup.homepage_override.mstone: 47.0
browser.tabs.closeWindowWithLastTab: false
browser.tabs.remote.disabled-for-a11y: true
browser.tabs.selectOwnerOnClose: false
browser.tabs.warnOnClose: false
browser.zoom.full: false
dom.apps.reset-permissions: true
dom.disable_window_move_resize: true
dom.max_chrome_script_run_time: 40
dom.max_script_run_time: 40
dom.mozApps.used: true
extensions.lastAppVersion: 47.0
font.default.zh-CN: serif
font.internaluseonly.changed: true
font.name.sans-serif.zh-CN: 文泉驿等宽微米黑
font.name.serif.zh-CN: 宋体
gfx.color_management.mode: 1
gfx.crash-guard.glcontext.appVersion: 45.0.2
gfx.crash-guard.glcontext.deviceID: Mesa DRI Intel(R) G41
gfx.crash-guard.glcontext.driverVersion: 2.1 Mesa 11.0.2
gfx.crash-guard.status.glcontext: 2
layers.acceleration.disabled: true
media.gmp-gmpopenh264.abi: x86_64-gcc3
media.gmp-gmpopenh264.enabled: false
media.gmp-gmpopenh264.lastUpdate: 1471510055
media.gmp-gmpopenh264.version: 1.6
media.gmp-manager.buildID: 20160606114238
media.gmp-manager.lastCheck: 1473146129
media.gmp.storage.version.observed: 1
media.webrtc.debug.aec_log_dir: /tmp
media.webrtc.debug.log_file: /tmp/WebRTC.log
media.youtube-ua.override.to: 43
network.cookie.cookieBehavior: 1
network.cookie.prefsMigrated: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1473067816
places.history.expiration.transient_current_max_pages: 100235
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
plugin.soname.list:
plugin.state.115upload_plugin: 0
plugin.state.gecko-mediaplayer: 2
plugin.state.gecko-mediaplayer-dvx: 2
plugin.state.gecko-mediaplayer-qt: 1
plugin.state.gecko-mediaplayer-rm: 2
plugin.state.gecko-mediaplayer-wmp: 2
plugin.state.libaliedit: 2
plugin.state.libnpupeditor: 0
plugin.state.nppdf: 2
plugin.state.nsdejavu: 0
print.print_bgcolor: false
print.print_bgimages: false
print.print_colorspace: default
print.print_downloadfonts: false
print.print_duplex: 0
print.print_evenpages: true
print.print_footerleft:
print.print_footerright:
print.print_headerleft:
print.print_headerright:
print.print_in_color: true
print.print_margin_bottom: 0.5
print.print_margin_left: 0.5
print.print_margin_right: 0.5
print.print_margin_top: 0.5
print.print_oddpages: true
print.print_orientation: 0
print.print_page_delay: 50
print.print_paper_data: 0
print.print_paper_height: 297.00
print.print_paper_name: 自定义大小 2
print.print_paper_size_type: 1
print.print_paper_size_unit: 1
print.print_paper_width: 210.00
print.print_plex_name: default
print.print_resolution: 1200
print.print_resolution_name: default
print.print_scaling: 1.00
print.print_shrink_to_fit: false
print.print_to_file: false
print.print_unwriteable_margin_bottom: 0
print.print_unwriteable_margin_left: 16
print.print_unwriteable_margin_right: 0
print.print_unwriteable_margin_top: 0
privacy.cpd.extensions-sessionmanager: false
privacy.cpd.extensions-tabmix: false
privacy.donottrackheader.enabled: true
privacy.sanitize.migrateClearSavedPwdsOnExit: true
privacy.sanitize.migrateFx3Prefs: true
privacy.sanitize.timeSpan: 4
security.default_personal_cert: Select Automatically
security.disable_button.openCertManager: false
security.disable_button.openDeviceManager: false
security.ssl.errorReporting.automatic: true
services.sync.declinedEngines: greasemonkey
services.sync.engine.adblockplus: true
services.sync.engine.greasemonkey: false
services.sync.engine.pan: true
services.sync.engine.prefs.modified: false
services.sync.lastPing: 1473159259
services.sync.lastSync: Wed Sep 07 2016 11:01:00 GMT+0800 (CST)
services.sync.numClients: 2
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1470628275

以下略。。。。。。。。

**Comment by acgotaku** [comment]
嘛 主要维护的都是Chrome。。。 先换浏览器 FF最新更新了扩展 API 准备换新的API写了

**Comment by twinfishxixi** [comment]
平时主力浏览器是FF，所以配置插件什么的都比较丰富，用起来也得心应手，Chrome都是遇到不兼容的网页时偶尔用一下，大神不着急，慢慢写！呵呵！～～

**Comment by acgotaku** [comment]
最新版 FF 已经兼容 Chrome扩展标准 老的不再继续维护

**Comment by zhanglianbo35** [comment]
我这边谷歌浏览器上面还是可以正常使用的。

发自我的 iPhone 
