### ISSUE TITLE
有没有一键通知服务器进行视频转码的办法？如果不点击打开文件一次，服务器永远不会去转码

### ISSUE THREAD

**Issue by 1265578519** [acgotaku/115#507]
有没有一键通知服务器进行视频转码的办法？如果不点击打开文件一次，服务器永远不会去转码
![5](https://user-images.githubusercontent.com/6442439/156056755-9234b3bc-5464-4a45-852d-0b8810e2081b.png)

**Comment by acgotaku** [comment]
这个超出了本插件的功能范围了，现在只维护 不加新功能。。。
