### ISSUE TITLE
谷歌开始对还在使用Manifest version 2的报错误警告了，明年就不支持，最好更新到3

### ISSUE THREAD

**Issue by lvzhenbo** [acgotaku/115#509]
![image](https://user-images.githubusercontent.com/32427677/159047822-812c4175-bdcc-4421-99eb-9f8eb845c6ab.png)

**Comment by acgotaku** [comment]
我先看看我的 115还能不能登录进行调试

**Comment by lvzhenbo** [comment]
我看更新了，然后咋还是V2啊

**Comment by acgotaku** [comment]
更新到 V3了，https://github.com/acgotaku/115/releases/tag/v0.5.0
