### ISSUE TITLE
现在115正被阿里折磨中，顾不上插件了，麻烦老大更新一波？

### ISSUE THREAD

**Issue by guochan2019** [acgotaku/115#519]
如题，现在的版本大文件勉强还能用，小文件有数量限制，而且插件Manifest version 2也报错，辛苦老大抽时间更新一波，用了这么多年，真舍不得就这样断了

**Comment by acgotaku** [comment]
你这说了等于没说。。。

现在插件用户也不少，出了大问题，基本上至少会有几十个人来反馈，你先排查下自己的问题吧。
