### ISSUE TITLE
关于200个文件限制

### ISSUE THREAD

**Issue by pangbotommy** [acgotaku/115#53]
您好，抱歉昨天留言留错位置。现在插件非常好用，只是下载文件夹时，不管内部多少文件，只能下载200个，不知是aria2本身参数问题，还是插件问题，如后者恳请您百忙中微调一下，现在360倒闭，115寸了100t文件，不用您的插件，五年恐怕也下不完，求您帮一下，用插件现在10倍于官方115浏览器下载速度。

**Comment by acgotaku** [comment]
你都这么说了。。。 但是我现在也很尴尬 我没有 含有200个文件 的文件夹 用来测试。。。

**Comment by pangbotommy** [comment]
太感激您了，方便加我一个微信么，我送您一个账号，里面有许多资料，pangbotommy

**Comment by acgotaku** [comment]
微信太泄漏隐私了。。。  发 Gmail就行  acgotaku311 #  gmail

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/54

是不是因为这个原因？
