### ISSUE TITLE
请问下载哪个是最新版？

### ISSUE THREAD

**Issue by microka** [acgotaku/115#533]
https://github.com/acgotaku/115/releases/download/v0.4.0/115.crx - 2022年5月21日 GMT+8 15:46
https://github.com/acgotaku/115/raw/master/release/115.crx - 2022年5月21日 GMT+8 20:33
看到 /raw/master/release 里的修改时间比 /releases/download 下的要更新，请问是下载 /raw/master/release 里面的吗？

**Comment by acgotaku** [comment]
是的 最新版本是 0.4.1 下载 /raw/master/release
