### ISSUE TITLE
批量导出时出现错误的解决办法

### ISSUE THREAD

**Issue by shap2zj** [acgotaku/115#54]
其实我本来是想提问的，但是后来想了想就自己解决了。

115最近应该开始对异地登录进行验证手机短信和输入验证码的措施。
因为我在美国，买了一个的服务器欧洲批量下电影，还不断挂VPN（因为国内和欧洲连接的路线真是醉了，动不动就从反方向连，或者在欧洲各国一日游）。。所以成为了115重点验证的对象。

咳咳，不说废话了。。如果导出时显示undefined，是因为115觉得你IP太多或者下太多了。这个时候手动按照官方的正常方法下载，就会要求输入验证码，输完可继续导出。
--
其实115还是蛮有良心的，开始走高端路线。
虽然没有经销商，500一年不打折。
但是人家也没有封号或者限速什么的（尽管离线下载只能下热门资源，或者不是特别大的资源，或者不是特别新的资源）

**Comment by acgotaku** [comment]
好吧。。。 居然还有人在用
