### ISSUE TITLE
导出下载链接报错

### ISSUE THREAD

**Issue by MUSHROOMQC** [acgotaku/115#543]
Error handling response: TypeError: Cannot read properties of 115.com/:1 undefined (reading 'match')
    at chrome-extension://medpaahgifmnmfafalgmiaeopoagbebf/js/home.js:1:33042
今天下载的7天前最新版

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/540

**Comment by rui7905** [comment]
https://github.com/acgotaku/115/releases 中的 Source code (zip)中的release/js/home.js文件与代码库中对应文件不一致。

使用Source code (zip)解压后的代码，在设置中，没有“会员”选项

**Comment by acgotaku** [comment]
@rui7905 我已经确认是有的，
<img width="669" alt="Screen Shot 2022-05-31 at 8 21 54" src="https://user-images.githubusercontent.com/1191834/171067536-50dfbbfe-70dc-4722-af19-3f3606a48aea.png">

没有的话，你可以自己编译一份。
