### ISSUE TITLE
会员的全局速度依然限制在400KB/s左右

### ISSUE THREAD

**Issue by rui7905** [acgotaku/115#544]
不知道是不是只有我一个人这样，电信链路。

之前没有勾选“会员”选项无法下载大文件，勾选后可以下载，但全局下载速度被限制在400KB/s左右了。
前两天的全局速度还是1.5MB/s左右的，不知道是115更新了策略，还是插件原因。

我个人账户的确是年付会员，确认没有过期

**Comment by UnderCooled** [comment]
我也这样，移动线路，10年冤大头会员

**Comment by UnderCooled** [comment]
我这里速度又恢复到了 1.5MB/s 左右

**Comment by chenqs000** [comment]
建议换回旧版本试试，我换回0.3.6或者0.3.9后速度有4.3m/s左右，大文件也能正常下载

**Comment by chenqs000** [comment]
今天更新到最新版后，所有提交的下载都瞬间http请求失败，又换回旧的了

**Comment by acgotaku** [comment]
能用的时候 就不用随便更新。。。
