### ISSUE TITLE
现在下载提取链接都失效了

### ISSUE THREAD

**Issue by ShinonomeHana** [acgotaku/115#55]
没有115没法种庄稼了
自从有了fake 115之后115越用越爽，但最近今天开始没法正常导出下载了
选择保存idm文件打开是空的
<
 cookie: undefined
 out=
 >

好吧我懂了，是下载时弹出了验证码窗口，必须去手动完成验证几次才行

**Comment by acgotaku** [comment]
那你就关掉吧。。。。
