### ISSUE TITLE
一次导出的下载链接数有上限？

### ISSUE THREAD

**Issue by RekiDunois** [acgotaku/115#553]
如题，我文件夹里有动画一共73集，但是获取到的下载链接最多只到68集。

每集动画有一个字幕文件一个视频文件，所以一共是146个文件，但是最后几集总是选中了也无法导出

版本是 0.5.0

**Comment by zaypen** [comment]
我这里也是，每次都是最多143个文件

**Comment by acgotaku** [comment]
可能是115对API调用有上限，只能一次选一半这样来解决了。

**Comment by acgotaku** [comment]
@keiamakura https://github.com/acgotaku/115/issues/561#issuecomment-1261598674

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/issues/567
