### ISSUE TITLE
v0.5.0不兼容旧版浏览器了

### ISSUE THREAD

**Issue by harryhuangwei** [acgotaku/115#561]
雪月秋水君 您好！
一直使用您写的115插件（Windows平台），真的非常好用，感谢！

目前正在使用的方案是：115官方浏览器（115br_23.9.3.2 最后一个支持导出到Aria2的版本）+v0.4.3.crx
此方案的好处是，既能拥有Aria2的稳定性，也能达到115官方最大速度（单文件下载速度30-40MB/s），
和最新版115官方客户端下载速度一致。

对比测试Chrome v106.x+v0.5.0.crx的方案时，单文件速度只能到12M/s左右，原因不明。

所以，一直使用115br_23.9.3.2+v0.4.3.crx（及之前的版本）的方案，非常的稳定，兼具速度与Aria2的极致性能。

遗憾的是，最新的v0.5.0.crx不能兼容115br_23.9.3.2了，您之前的版本一直都是可以兼容的。

然后我爬了一下楼，是因为"manifest_version": 3 造成的吗？
往后，我现在的方案是不是就用不了呢？（代码小白，大神勿怪，还请解惑）

如果有可用解决方案的话，烦请大神在后续的版本中，能继续兼容115br_23.9.3.2（对应Chrome版本 62.0.3202.94 32位）
在此谢过！

感谢您一直以来的无私奉献，让115的下载非常省心和愉快！
大神辛苦了！再次表示感谢！

**Comment by acgotaku** [comment]
0.4.3 和 0.5.0除了升级了 manifest_version 版本没有任何区别，估计是115浏览器可以导出更快的下载链接。
你可以一直使用 0.4.3版本，因为我没有115会员也没有 Windows平台的电脑，所以无法支持115浏览器的使用。

**Comment by harryhuangwei** [comment]
好的，明白！谢谢您！
那么，如果115后期有大“动作”，必须要升级插件的时候，您是否可以顺便提供一下 "manifest_version": 2 的插件，以便我继续使用这个“古董版”的115官方浏览器呢？

**Comment by acgotaku** [comment]
如果115 有啥 大动作 这个软件可能就停止维护了 🤣

**Comment by harryhuangwei** [comment]
哈哈，比如之前，突然不能导出大文件的那次，您更新了之后，就可以啦  我是指的这种情况
您后期维护的时候，可以继续发布一下 "manifest_version": 2 的版本吗？

**Comment by acgotaku** [comment]
这就随缘了。。。

**Comment by harryhuangwei** [comment]
拜托了！还请您顺手更新一下 "manifest_version": 2
拜托！拜托！

**Comment by csanmm887123** [comment]
> 

大佬，你这嘴开光了，昨天刚说，今天115就有动作，麻烦看下，貌似是地址无法推送了，用了你的插件这么久，已经强烈依赖 @acgotaku

**Comment by acgotaku** [comment]
@csanmm887123 这次是屏蔽了浏览器下载了，很难修复的。。。 估计直接GG了

**Comment by HoodyHuo** [comment]
诶，用这个插件是为了 Linux下能够正常使用115 ，现在如果封停浏览器下载，又不提供linux客户端的话，11.5年的会员怕是要炸了
