### ISSUE TITLE
大佬，115获取地址疑似失效，无法离线了

### ISSUE THREAD

**Issue by csanmm887123** [acgotaku/115#562]
一直用大佬的这个插件，今天115貌似更新了策略，离线助手无法获取地址推送到aria2了，麻烦看下

**Comment by acgotaku** [comment]
已经确认到了，能不能修复还是未知数。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/releases/tag/v0.5.1  v0.5.1 修复了
