### ISSUE TITLE
关于无法获取到下载地址的另一种猜想

### ISSUE THREAD

**Issue by harryhuangwei** [acgotaku/115#564]
刚刚测试了最新版的115官方浏览器，发现其实是保留了浏览器下载的
那么，有没有一种可能，我们把chrome或者其他chrome内核的浏览器伪装成115官方浏览器，然后就可以获取到下载地址了呢？
我是代码小白，大家不要笑我。哈哈

**Comment by harryhuangwei** [comment]
大神辛苦了！期待你的好消息。

**Comment by mentaldease** [comment]
1，rsa公钥变化了（加密解密都用的公钥，以前是两个密钥？）
self.n = 94467199538421168685115018334776065898663751652520808966691769684389754194866868839785962914624862265689699980316658987338198288176273874160782292722912223482699621202960645813656296092078123617049558650961406540632832570073725203873545017737008711614000139573916153236215559489283800593547775766023112169091
self.e = 0x10001
2，初始密钥变化了
self.g_kts = bytes.fromhex('F0E569AEBFDCBF8A1A45E8BE7DA673B8DE8FE7C445DA86C49B648B146AB4F1AA3801359E26692C860'
                                   '06B4FA5363462A62A966818F24AFDBD6B978F4D8F8913B76C8E93ED0E0D483ED72F88D8FEFE7E8650'
                                   '954FD1EB832634DB667B9C7E9D7A8132EAB633DE3AA95934663BAABA816048B9D5819CF86C8477FF5'
                                   '478265FBEE81E369F34805C452C9B76D51B8FCCC3B8F5')
self.g_key_s = [0x29, 0x23, 0x21, 0x5E]
self.g_key_l = bytearray(bytes.fromhex('7806AD4C33865D184C013F46'))
3，useragent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 115Browser/25.0.4.1

**Comment by acgotaku** [comment]
@mentaldease 请问下 数据来源？

**Comment by callerin** [comment]
加油鸭！

**Comment by csanmm887123** [comment]
> 1，rsa公钥变化了（加密解密都用的公钥，以前是两个密钥？） self.n = 94467199538421168685115018334776065898663751652520808966691769684389754194866868839785962914624862265689699980316658987338198288176273874160782292722912223482699621202960645813656296092078123617049558650961406540632832570073725203873545017737008711614000139573916153236215559489283800593547775766023112169091 self.e = 0x10001 2，初始密钥变化了 self.g_kts = bytes.fromhex('F0E569AEBFDCBF8A1A45E8BE7DA673B8DE8FE7C445DA86C49B648B146AB4F1AA3801359E26692C860' '06B4FA5363462A62A966818F24AFDBD6B978F4D8F8913B76C8E93ED0E0D483ED72F88D8FEFE7E8650' '954FD1EB832634DB667B9C7E9D7A8132EAB633DE3AA95934663BAABA816048B9D5819CF86C8477FF5' '478265FBEE81E369F34805C452C9B76D51B8FCCC3B8F5') self.g_key_s = [0x29, 0x23, 0x21, 0x5E] self.g_key_l = bytearray(bytes.fromhex('7806AD4C33865D184C013F46')) 3，useragent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 115Browser/25.0.4.1

哈，是某坛的兄弟吗，我是给你留言的，大佬们加个油，用这个插件好几年了

**Comment by AZ-X** [comment]
It’s a little push of installing dedicated apps on your device which likes pure pill from Ali kinds.
All we can learn is good things can be broken in one day after they migrated the multifactor services to aliyuncs.
Let them suck.

**Comment by mentaldease** [comment]
还有http://proapi.115.com/app/chrome/downurl返回的Set-Cookie，好像chrome.cookies.getAll没拿到，导致下载不了，不太会JS

**Comment by mentaldease** [comment]
我目前的方案是在自己服务器转发http://proapi.115.com/app/chrome/downurl，在中间处理Set-Cookie

**Comment by csanmm887123** [comment]
> 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e

这个怎么用，我们自己手动替换原来插件里的代码吗？

**Comment by iwestlin** [comment]
> 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e

@showmethemoney2022  请问下，是使用Secret类的encode和decode方法吗？我试了下decode怎么解密不了encode加密的字符串呢...
```js
import secret from './secret.mjs'

const msg = 'test message'
console.log('origin message: ', msg)
const timestamp = Date.now()
console.log('timestamp: ', timestamp)
const encoded = secret.encode(msg, timestamp)
console.log('encoded: ', encoded)
console.log('decoded: ', secret.decode(encoded.data, encoded.key))
```
输出
```
origin message:  test message
timestamp:  1664638247155
encoded:  {
  data: 'HFhSnURDZJjTLroCQ5CuZnqj+lHs1CT89EUXEgTVpsiQ/zf5J9y/RKDtmtZ3xiyx2p+fVXnqrhy2v4tV4NmVxopBCP7qdJIb2NjmKwyntKjyKv78tShqrrYtYFp6rhC4PvwV+flWRl+8Qz3hwmNL6WXOuk/X5oX4/nr//lVUv2k=',
  key: [
    51, 54, 53, 48, 51, 53, 51, 48, 57,
    54, 56, 57, 99, 54, 56, 48, 99, 56,
    53, 48, 50, 49, 48, 97, 49, 55, 50,
    57, 98, 49, 48, 50
  ]
}
decoded:  ú4ká} êí^õ1û`g§;o'fdáÐÀ
                                     O1PIxæOÒ«>ísóà6htM
Îæ=(,`Ûð#©GRÞ¹vFáç
```

**Comment by fuxin052** [comment]
> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 115Browser/25.0.4.1

下载链接是获取到了, 但是链接是403的, 不知道缺了点什么

**Comment by zer0pwned** [comment]
> 

加密解密都用公钥就很灵，我说为什么gist里只看到了n和e没有看到d。

**Comment by zer0pwned** [comment]
> 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e

测了一下这个算法和密钥，是没问题的，可以正常下载。不过我用的是tempermonkey的[115 优化大师 js脚本](https://gist.github.com/zer0pwned/0a3385aabebe5162af2c704212cbdda7)

**Comment by acgotaku** [comment]
@showmethemoney2022 测试了一下，确实可以，可以请问下是如何分析出密钥的么？

**Comment by showmethemoney2022** [comment]
> @showmethemoney2022 测试了一下，确实可以，可以请问下是如何分析出密钥的么？

调试115PC版

**Comment by showmethemoney2022** [comment]
> > 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e
> 
> 下载链接是获取到了, 但是链接是403的, 不知道缺了点什么

有时候downurl会返回一个cookie，chrome.cookies.getAll好像没获取到这个cookie，导致403，目前我是在自己服务器转发downurl，用来处理cookie

**Comment by acgotaku** [comment]
@showmethemoney2022 cookie问题我也看到了，下个版本会修正

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/releases/tag/v0.5.1 v0.5.1 版本修复了

感谢 @showmethemoney2022 对加密算法的支持

**Comment by AZ-X** [comment]
gotcha
it works

**Comment by csanmm887123** [comment]
谢谢大佬们的工作，可以用了！另外浏览器不能直接安装的可以进入浏览器的扩展设置页面再拖动进去就可以安装了

**Comment by AZ-X** [comment]
@acgotaku I found an issue that files below 1M failed to download. Please look into it.

**Comment by Anza7i** [comment]
> > 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e
> 
> 下载链接是获取到了, 但是链接是403的, 不知道缺了点什么

我也出现403，你遇到的问题是怎样的。我的解决方法是，让发送downurl请求中携带的User-Agent和下载请求时的UA一致

**Comment by fuxin052** [comment]
> > > 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e
> > 
> > 
> > 下载链接是获取到了, 但是链接是403的, 不知道缺了点什么
> 
> 我也出现403，你遇到的问题是怎样的。我的解决方法是，让发送downurl请求中携带的User-Agent和下载请求时的UA一致，否则115浏览器的版本不一致就会403

![image](https://user-images.githubusercontent.com/46592199/193462087-1d898cd6-9d5e-488f-bb28-23ce13a6c811.png)
![image](https://user-images.githubusercontent.com/46592199/193462177-ddd97938-d157-4304-b25d-ba5d7f73a77a.png)

**Comment by SAOJSM** [comment]
> > 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e
> 
> 测了一下这个算法和密钥，是没问题的，可以正常下载。不过我用的是tempermonkey的[115 优化大师 js脚本](https://gist.github.com/zer0pwned/0a3385aabebe5162af2c704212cbdda7)

大佬，这脚本是您写的还是改的呢？
我看tempermonkey上原来的脚本有UI，您这个脚本也有UI，但最新版的看不到UI，不知道是什么问题

**Comment by fuxin052** [comment]
> > > 这是我更新的密钥https://gist.github.com/showmethemoney2022/430ef0e45eeb7c99fedda2d2585cfe2e
> > 
> > 
> > 下载链接是获取到了, 但是链接是403的, 不知道缺了点什么
> 
> 我也出现403，你遇到的问题是怎样的。我的解决方法是，让发送downurl请求中携带的User-Agent和下载请求时的UA一致，否则115浏览器的版本不一致就会403

就在刚刚, 突然又403了(不能确定是不是403, aria2所有文件速度都为0, 前一个小时还能下载), cookie和User-Agent都没有问题, 官方下载工具也没有问题

**Comment by zer0pwned** [comment]
@SAOJSM 这个是我改的4.7.6版，我一直都没有更新这个脚本，因为我只需要他的下载导出的功能。

**Comment by acgotaku** [comment]
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf?hl=en

上架谷歌商店了
