### ISSUE TITLE
115.crx 会被拦截

### ISSUE THREAD

**Issue by OUZYcn** [acgotaku/115#566]
Chrome、Edge都会拦截，即便将本地的杀毒关闭。

下载chrome.zip解压加载就可以

**Comment by csanmm887123** [comment]
确实会被拦截 ，不过只要进入浏览器的扩展设置页面再把crx拖进去就可以安装了，不必须解压什么的。

**Comment by OUZYcn** [comment]
问题是crx都下载保存不了……太狠了


csanmm887123 ***@***.***>于2022年10月2日 周日11:24写道：
