### ISSUE TITLE
恳请秋水大佬更新一个manifest_version": 2的0.5.1版本

### ISSUE THREAD

**Issue by pyyii** [acgotaku/115#567]
115官方浏览器25.0.4.1浏览器的内核是83，安装不了目前manifest_version": 3的0.5.1版，使用最新chrome可以正常使用，但是115恶心人的地方是不用他自家的浏览器每次登录都要让你填字验证再加上手机短信验证码才能登录，简直是反人类。所以希望秋水大佬抽空来一发manifest_version": 2的。

**Comment by xiaoleichen** [comment]
搭车问下不知道可不可以给Firefox也更新下？Firefox的扩展从上次115改版后就不能用了。

**Comment by acgotaku** [comment]
等  0.5.1 版本没有啥 大BUG 再说，我没有精力维护这么多版本。

**Comment by pyyii** [comment]
> 等0.5.1没有啥大BUG版本 那么，我没有精力维护这么多版本。

好的，感谢秋水大佬，慢慢来不急，等版本安定下来了，大佬有时间再搞。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/tree/feature/v2

自己去这个分支下载吧。

**Comment by acgotaku** [comment]
V2 版本只能源代码载入，本人实测是可以下载的。

**Comment by pyyii** [comment]
> V2 版本只能源代码载入，本人实测是可以下载的。

我115端是25.0.4.1版本，添加到aria2链接直接403，http返回头无效或无法识别；但是用第三方chrome直接使用v3的0.5.1就能正常下载。然后我开始自己瞎J8魔改，把v3的0.5.1版解压出来，用v2版的manifest和background.js覆盖到v3里再载入，但是问题依旧。                     ~~~不懂技术的我，默默地关掉了115浏览器~  T T

**Comment by acgotaku** [comment]
我没有115浏览器，所以不清楚。但是Chrome浏览器，V2版本是可以使用的。

**Comment by xiaoleichen** [comment]
意外发现这个feature v2 firefox也可以用。感谢感谢！

**Comment by gooddy2013** [comment]
> 意外发现这个feature v2 firefox也可以用。感谢感谢！

源码载入怎么操作？可以讲解下吗？

**Comment by gooddy2013** [comment]
> 意外发现这个feature v2 firefox也可以用。感谢感谢！

源码载入怎么操作？可以讲解下吗？

**Comment by gooddy2013** [comment]
> 意外发现这个feature v2 firefox也可以用。感谢感谢！

源码载入怎么操作？可以讲解下吗？

**Comment by xiaoleichen** [comment]
> > 意外发现这个feature v2 firefox也可以用。感谢感谢！
> 
> 源码载入怎么操作？可以讲解下吗？

我搞了个firefox的账号，把源码提交让他们给签了个名，然后直接把他们打包好的xpi拖到firefox安装的
