### ISSUE TITLE
0.51及0.50都无法安装

### ISSUE THREAD

**Issue by falltree** [acgotaku/115#568]
近期115无法通过aria2下载，115浏览器版本25.0.4.1
安装0.50，0.51版crx都报错，在chrome和centbrowser也报同样错误。
直接拖放crx无法安装，解压打包程序安装则报以下错误：

未能成功加载扩展程序
文件
C:\Temp\115\115 aria2 exporter-v0.5
错误
Invalid value for 'web_accessible_resources[0]'.
无法加载清单。

**Comment by acgotaku** [comment]
115浏览器 本扩展并不支持，等版本稳定了 会出一个兼容版本

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/tree/feature/v2

自己去这个分支下载吧。

**Comment by gexiaopeng** [comment]
> https://github.com/acgotaku/115/tree/feature/v2
> 
> 自己去这个分支下载吧。

115下载助手
0.4.3
 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的

**Comment by falltree** [comment]
刚才在115里试了以下用源码打包安装，这个0.4.3v2版可以成功导出下载链接，但是速度为0，持续5-10秒后，会下载失败而结束任务。
随机尝试了多个文件，均下载失败

**Comment by gooddy2013** [comment]
> 刚才在115里试了以下用源码打包安装，这个0.4.3v2版可以成功导出下载链接，但是速度为0，持续5-10秒后，会下载失败而结束任务。 随机尝试了多个文件，均下载失败 更新：更换了另一台电脑，安装另一个115浏览器版本，23.9.2.1，然后再安装这个插件，导出aria2下载就正常了。

请教下怎么源码安装成功的？

**Comment by falltree** [comment]
> > 刚才在115里试了以下用源码打包安装，这个0.4.3v2版可以成功导出下载链接，但是速度为0，持续5-10秒后，会下载失败而结束任务。 随机尝试了多个文件，均下载失败 更新：更换了另一台电脑，安装另一个115浏览器版本，23.9.2.1，然后再安装这个插件，导出aria2下载就正常了。
> 
> 请教下怎么源码安装成功的？

把插件扩展名crx修改成zip，然后解压到某个目录。之后在浏览器扩展那里选择加载打包文件，找到刚才解压的目录即可安装。
