### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by rozen30** [acgotaku/115#576]
点115文件，导出到ARIA2-RPC之后在AriaNG会瞬间显示下载失败。重试没用。

**Comment by rongcc1985** [comment]
勾选 115会员 就正常了，虽然不是会员。

**Comment by ffjia** [comment]
> 勾选 115会员 就正常了，虽然不是会员。

勾选吧，但是也还是瞬间失败。版本0.5.1，是版本的原因吗？
