### ISSUE TITLE
https 的jsonrpc 可以不？

### ISSUE THREAD

**Issue by ww2283** [acgotaku/115#580]
我目前配置下可以拷贝链接，并手动放置在https://aria2c.com/中。https://aria2c.com/的webgui中我在headers里面填写了user-agent, referer和cookie。这种情况下可以下载，说明配置是成功的。
目前的问题是，如果我点 导出下载->ARIA2 RPC，是不能成功的。
设置界面中，Aria2 RPC: https://token:MySecrect@myhost:6800/jsonrpc
提示：错误，请查看是否开启Aria2。

请问有什么地方出现问题了呢？是https的jsonrpc不支持吗？

**Comment by acgotaku** [comment]
你先保存RPC地址，然后点测试 连接 试试吧。

**Comment by ww2283** [comment]
谢谢回复！ 我之前翻过历史讨论，所以知道先保存再测试。。
测试的按钮不是总能有效，大部分时候没有反应，浏览器左下角会显示javascript: void(0)。请问还有什么别的可能性没？

**Comment by acgotaku** [comment]
那你可以改回 http 试试啊 你这问题也不是我插件的问题啊 我爱莫能助啊
