### ISSUE TITLE
115浏览器添加扩展报错

### ISSUE THREAD

**Issue by gooddy2013** [acgotaku/115#581]
115 浏览器版本25.4.0.1
添加0.5.1插件，报错，提示“程序包无效invalid value for web access”
请教作者有办法解决吗？

**Comment by acgotaku** [comment]
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf?hl=en

去官方商店下载

**Comment by gooddy2013** [comment]
官方商店直接提示不兼容，还有其他办法吗？我是用在115 浏览器版本25.4.0.1（最新版本）上

**Comment by acgotaku** [comment]
没有 我就没支持115浏览器

**Comment by gooddy2013** [comment]
最新版本可以向下兼容到Chrome 83版本吗？或者哪个版本支持Chrome  83
