### ISSUE TITLE
下载整个文件夹只能下其中的100个文件

### ISSUE THREAD

**Issue by anbroQ** [acgotaku/115#588]
115会员，12月底开始不正常，推送整个文件夹到NAS的AriaNg或者本机的Motrix都只能下文件夹里面的100个文件，没下到的文件aria2收不到下载地址不产生下载任务

**Comment by kkaaas** [comment]
我也是啊，都一两个月了，每次只能下载100个左右

**Comment by 627992512** [comment]
同样的问题

**Comment by fuxin052** [comment]
https://github.com/acgotaku/115/blob/257ae229b8bf7d427016a74d19e47ffff7d4c532/src/js/home.js#L10

可能115改了接口 
这个字段限制了最大值 使1000不生效 而走了默认的100
导致读取文件夹下的文件只能读到100个

**Comment by fuxin052** [comment]
我很早就提过这个问题 #548 但是不予解决
具体原因是并发太高, 115服务器报错了其中一些
于是我自己写了个油猴版本的, 请求改成单线程,并添加延时, 从来没失败过了

**Comment by 627992512** [comment]
> 

老哥方便发下油猴脚本吗，我最近快被115客户端的下载折磨死了

**Comment by fuxin052** [comment]
> > 
> 
> 老哥方便发下油猴脚本吗，我最近快被115客户端的下载折磨死了

只支持aria2, 右键点击按钮打开设置界面

**Comment by anbroQ** [comment]
> > > 
> > 
> > 
> > 老哥方便发下油猴脚本吗，我最近快被115客户端的下载折磨死了
> 
> https://github.com/fuxin052/115_aria2/raw/main/dist/115pan_aria2.user.js 只支持aria2, 右键点击按钮打开设置界面
老哥，设置配置都对，点下载解析的文件数也对，但是导入到aria2全失败可能是什么原因

**Comment by 627992512** [comment]
我也全失败

**Comment by fuxin052** [comment]
> > > > 
> > > 
> > > 
> > > 老哥方便发下油猴脚本吗，我最近快被115客户端的下载折磨死了
> > 
> > 
> > https://github.com/fuxin052/115_aria2/raw/main/dist/115pan_aria2.user.js 只支持aria2, 右键点击按钮打开设置界面
> 
> 老哥，设置配置都对，点下载解析的文件数也对，但是导入到aria2全失败可能是什么原因

脚本没权限访问你的aria2服务器， 我更新了下， 现在会弹提示框， 选全部是就好了

**Comment by fuxin052** [comment]
> 我也全失败

看[https://github.com/fuxin052/115_aria2](https://github.com/fuxin052/115_aria2)下面的说明

**Comment by acgotaku** [comment]
[chrome.zip](https://github.com/acgotaku/115/files/10728173/chrome.zip)
做了一个请求带间隔的处理，导出会变慢，但100文件应该不会出错了。自己载入浏览器试试
