### ISSUE TITLE
115开始限制批量提取下载链接：“访问被拦截！您的请求疑似攻击行为 ”

### ISSUE THREAD

**Issue by toukoubun** [acgotaku/115#594]
最近提取链接半天都没发送到aria2，打开插件控制台，发现插件提取链接的所有请求都被返回418错误（递归获取目录文件的请求没有除出错）

![图片](https://user-images.githubusercontent.com/52944472/226929730-f7f2269b-8a74-4b0d-ba6d-9eba38941202.png)

**Comment by toukoubun** [comment]
> [#588 (comment)](https://github.com/acgotaku/115/issues/588#issuecomment-1429028516)

原来是这个issue，十分感谢。不知道有没有计划把这个提取链接的间隔改为可设置，然后添加到插件的设置界面上？（和设置递归提取目录的时间间隔一样）

**Comment by acgotaku** [comment]
@toukoubun 你先试试这个加间隔的版本能否解决问题，如果好用的话 我就把这个功能完善掉 设置也复用目录的间隔 时间
