### ISSUE TITLE
115下载助手 是不是不支持 Motrix？

### ISSUE THREAD

**Issue by PrinSoul** [acgotaku/115#599]
115下载助手 是不是不支持 Motrix？我用AriaNg Native才可以

**Comment by acgotaku** [comment]
Motrix 可以的 应该是你没配置好

**Comment by PrinSoul** [comment]
> Motrix 可以的 应该是你没配置好

115下载助手只需要配置这里吧？http://localhost:16800/jsonrpc

**Comment by acgotaku** [comment]
是的

**Comment by PrinSoul** [comment]
> 是的

我就是这样配置的，但他提示：“错误,请查看是否开启Aria2”

**Comment by acgotaku** [comment]
那我就不清楚了，可能是你本地网络有问题。 或者Matrix和 115助手不在一台机器上

**Comment by PrinSoul** [comment]
> 那我就不清楚了，可能是你本地网络有问题。 或者Matrix和 115助手不在一台机器上

Matrix和 115助手是在一台机器上，
我配置设置成 http://localhost:6800/jsonrpc，能用AriaNg Native；
改成 http://localhost:16800/jsonrpc，却用不了Motrix

**Comment by acgotaku** [comment]
解铃还须系铃人 是不是你自己端口占用了？ 本地的网络问题 等等，我无法帮你解决。

**Comment by PrinSoul** [comment]
> 解铃还须系铃人 是不是你自己端口占用了？ 本地的网络问题 等等，我无法帮你解决。

找到原因了，原来是Matrix要设置 RPC授权密钥 为空的
