### ISSUE TITLE
发送下载任务至yaaw时，能否发送任务目录，自动建立子目录

### ISSUE THREAD

**Issue by poplarch** [acgotaku/115#6]
OS: Mac OS X 10.10.3
Broswer: Firefox 35.0.1
例如下载该磁力链接 magnet:?xt=urn:btih:XFRGRDJ7UFXRCDWW5SVSZK72R23JDMN6
直接选中任务目录，发送到yaaw下载是将单个文件下载到默认目录的，能否发送子目录至yaaw
aria2c --dir='/path/to/download/[KNA][Girlfriend (kari)][01-12][720P][MP4][BIG5]'
或者发送前用户手工设置子目录
感觉这样多任务才不会太混乱。

**Comment by acgotaku** [comment]
@poplarch 递归目录也不是不能实现 等我抽空完善这个功能

**Comment by poplarch** [comment]
thx:) 话说 https://github.com/binux/ThunderLixianExporter 迅雷离线发送到yaaw目录递归是实现了的。

**Comment by acgotaku** [comment]
@poplarch 我自家开发的百度网盘也实现递归了好吧。。

**Comment by poplarch** [comment]
百度离线太垃圾…同样一个磁力链接百度无法解析，但是115离线完全没问题，渣雷离线速度现在还不如115

**Comment by acgotaku** [comment]
@poplarch  115是作死模式。。。百度封了磁力链吧。。。到现在没解析成功过一次。。。

**Comment by acgotaku** [comment]
@poplarch 手动设置子目录的话 这个功能在设置里面有的哦

下载路径选项

**Comment by poplarch** [comment]
知道的，那个只能当时设置一次，然后如果手贱每次都需要改，每次都要设置…想法是第一层目录可以做成交互式的，有些种子的第一层目录不方便识别，可以直接自定义当然好。

**Comment by acgotaku** [comment]
@poplarch 那就直接全自动好了

**Comment by Paulreina** [comment]
@acgotaku 今天用115发现好像无法Aria2了，添加到YAAW都是失败？是115修改啥东西了？

**Comment by acgotaku** [comment]
@Paulreina 怎么使用的？ 我测试显示正常

**Comment by iwfq** [comment]
115我也是提示‘下载成功，赶紧去看看吧’，但控制台显示下载失败。百度网盘的没问题。

**Comment by acgotaku** [comment]
@poplarch 目录递归下载功能实现了！！！

**Comment by poplarch** [comment]
@acgotaku 用chrome加载了下最新的0.0.7版本，有个小问题，如果目录A是根目录，里面的子目录都可以正常包含在目录A里，但是目录A里面的子文件都跑出来了。

**Comment by acgotaku** [comment]
@poplarch 发现了 立马修复

**Comment by acgotaku** [comment]
@poplarch  再试试！

**Comment by poplarch** [comment]
@acgotaku 应该是正常了:) 我关闭这个issue了

**Comment by acgotaku** [comment]
@poplarch 终于关闭了 QAQ 强迫症的福音
