### ISSUE TITLE
最近两个版本，更新后依然不能用，反而旧版能用

### ISSUE THREAD

**Issue by gz0007** [acgotaku/115#606]
还以为节点阵亡了

**Comment by sbbbsbbb** [comment]
你用的是哪个版本

**Comment by acgotaku** [comment]
我测试了一下，普通文件下载是OK的 你是为啥不能用？

**Comment by sbbbsbbb** [comment]
用的Version: 0.5.1
版本，在chrome 版本 124.0.6367.92（正式版本） （64 位）
正常模式下 下载任何电影都无法下载， 配置都是正常，以前可以用
在隐身模式下测试也是一样
![image](https://github.com/user-attachments/assets/68120fae-0f47-4bf8-a55d-038813338b31)
<img width="829" alt="image" src="https://github.com/user-attachments/assets/ec7eb3a2-8178-40b5-b7f1-23c450a8479c">

**Comment by acgotaku** [comment]
可以录个屏幕看一下 为啥不能下载么？
能导入到 aria2么？ 还是导入到 aria2 之后下载失败？

**Comment by acgotaku** [comment]
可以使用文本导出 然后贴出来内容 我看看导出链接

**Comment by sbbbsbbb** [comment]
我更新chrome 后也是不可以使用，但是过了2天后，又可以了，不知道现在是不是115限制了？
现在已近可以用了

**Comment by acgotaku** [comment]
可能是你大量导出 流量异常 被屏蔽了一段时间
