### ISSUE TITLE
你好，可以删除这条讨论吗？

### ISSUE THREAD

**Issue by starwarsfen** [acgotaku/115#608]
你好，可以删除这条讨论吗？

**Comment by acgotaku** [comment]
配置界面 的测试连接 点击能显示版本号的话，就是成功配置了。

下载失败的话 可以先试试下载单文件

**Comment by acgotaku** [comment]
确实报错了，可能115更新了 下载机制 需要花时间对应

**Comment by acgotaku** [comment]
我多测试了几个文件，又可以了，可以尝试重新刷新页面 然后再导出下载

如果有问题的话，可以选择文本导出，然后把文本贴出来 我看看

**Comment by acgotaku** [comment]
SHA1 校验关掉 试试

**Comment by acgotaku** [comment]
我这扩展有注入 JS的，你可以试试关掉这个放行

**Comment by acgotaku** [comment]
我这边偶尔会报 22 错误，但是最后还是能下载的

要不你试试 用 aria2c 命令行下载 看看效果？
