### ISSUE TITLE
0.1.8版本在Chrome最新稳定版下面的问题

### ISSUE THREAD

**Issue by rocknjoekudo** [acgotaku/115#63]
感谢acgotaku大大的辛勤付出。在使用最新版本的Chrome搭配Chrome商店上最新版本的115 Exporter时，发现了两个问题：
1、Aria2-RPC模式无法正常对接，无论如何设置，最终扩展都不能正确连接到Aira2-RPC。而相同设置下，BaiduExporter就没有问题。目前鄙人只能使用导出Aria2配置文件的方式使用。
2、目前115把单文件的连接数限制到了2个，但是扩展中写到的Split=10,。这会导致115一直报错，直到超过最大重试次数。手动把生成的任务文件中的Split=10改为Split=2，问题解决。
希望大大有空可以尝试修复一下这两个问题。鄙人在此感激不尽。

**Comment by acgotaku** [comment]
我这边默认 rpc地址 http://localhost:6800/jsonrpc  是可以的  请问你的地址大概是什么格式i的？

**Comment by acgotaku** [comment]
我这边打开 Https 版本的115是不能正常显示的 你的可以？

**Comment by rocknjoekudo** [comment]
这边https版本可以打开，但是需要等待+多次尝试。最终结果如下图：
![115](https://cloud.githubusercontent.com/assets/9285188/23258205/60f39116-f9c7-11e6-8464-bd529d5d1be7.jpg)

**Comment by rocknjoekudo** [comment]
对了，我忘记说了，我用的是Chrome搭配 https://github.com/kkHAIKE/fake115 这个项目来登陆115的。

**Comment by acgotaku** [comment]
我这边https无法正常支持  算了。。。
