### ISSUE TITLE
It's not working sense 2017-03-18 

### ISSUE THREAD

**Issue by seipop** [acgotaku/115#64]
2017-03-18，115网盘修改了安全验证，禁止了第三方工具下载其内容（尚不明确验证机制），当使用此插件时，下载结果均返回
```
<!DOCTYPE html>
<html>
<head>
    <title>115下载安全升级</title>
</head>
<body>
<script type="text/javascript">
    window.location.href="http://pc.115.com/notice/index.html";
</script>
</body>
</html>
```

**Comment by jerryh80** [comment]
擦, 我这里出现这个问题了, 头疼啊, 115太恶心了..

**Comment by SirBrother** [comment]
前几天都还好，晚上突然出现这问题

**Comment by jerryh80** [comment]
是的, 我的也是今天晚上出现的这个问题
![image](https://cloud.githubusercontent.com/assets/2759820/24100902/1d71e106-0db1-11e7-9e4a-041accbc3d16.png)

**Comment by jerryh80** [comment]
目前实测, 貌似在mac下, 可以用 folx进行下载, 看了下, 里面的user-agent:
`
               Thread main : User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.25 (KHTML, like Gecko) Version/8.0 Safari/600.1.25

               Thread main : Host: vipcdntel.115.com

               Thread main : Pragma: no-cache

               Thread main : Accept: */*

               Thread main : Cookie: ssov_35771365=;PHPSESSID=;loginType=;UID=;CID=;SEID=;OOFL=;115_lang=

               Thread main : Connection: close

               Thread main : Cache-Control: no-cache

               Thread main : Range: bytes=2351330758-

`

但是copy过去没用

**Comment by gz0007** [comment]
是啊，有解决方法吗？

**Comment by scetus** [comment]
同样遇到这个问题，不知道有什么解决办法。

**Comment by insomniacdoll** [comment]
刚好换了nas，还以为是重装的aria2有问题= =原来是赖老板又作妖了= =

**Comment by insomniacdoll** [comment]
尝试了下，应该是少了cookie，在headers里面把cookie设置好就可以正常用插件+aria2c下载了。还没空研究115的cookie失效时间是啥套路。

**Comment by acgotaku** [comment]
好 那我接下来就把cookie带上就是了

**Comment by droid-Q** [comment]
#66

**Comment by SirBrother** [comment]
Aria2 在 0.2.0 版本下可以了，但是导出为 IDM 下载格式还是不行

**Comment by acgotaku** [comment]
IDM 貌似不支持多cookie 还没做支持 目前只支持 aria2

**Comment by acgotaku** [comment]
支持 IDM了

**Comment by funabashi-cn** [comment]
safari 插件没有更新啊……期待大神更新……

**Comment by acgotaku** [comment]
@funabashi-cn safari插件没得更新 不是我写的 你问 @Cee

**Comment by Cee** [comment]
最近看一下...

**Comment by zhanglianbo35** [comment]
原理是不是wmp 验证数字签名 ？  你下载一个 *.mov的文件试试

**Comment by funabashi-cn** [comment]
@Cee 小白期待更新
