### ISSUE TITLE
下载的文件只有207B

### ISSUE THREAD

**Issue by k1n** [acgotaku/115#65]
试过好几个文件，都是成功下载，但是都是207B大小。
操作系统：macos 10.12.4
浏览器：115 8.1.0.15
插件版本：0.1.8

**Comment by FinalTheory** [comment]
同样问题，插件版本0.1.9

**Comment by sw1020** [comment]
但是将下载地址复制到chrome里面可以正常下载，所以还是参数问题，就是不知道修改啥

**Comment by scutdk** [comment]
你下载下来的是这个: http://pc.115.com/notice/index.html
115现在封锁第三方下载工具了

**Comment by sw1020** [comment]
使用aria2下载是这个，但是地址拷贝到chrome浏览器里面，下载是正常的文件，所以还是可以的

**Comment by acgotaku** [comment]
我知道了 过几天修复。。。

**Comment by acgotaku** [comment]
修复了
