### ISSUE TITLE
插件无法连接局域网内的aria2

### ISSUE THREAD

**Issue by besta9188** [acgotaku/115#74]
我在局域网内内有一个aria2的进程，但是不论怎么设置rpc地址，总是提示错误无法连接，这是怎么回事？

**Comment by acgotaku** [comment]
那你试试用 YAAW能连上么？ 这一般都是自己设置的问题。。。 我又不是aria2c的客服。。。。

**Comment by besta9188** [comment]
情况大致如此，yaaw也是连不上的，这个rpc地址没有问题，其他地方都能用​

2017-07-01 16:41 GMT+08:00 雪月秋水 <notifications@github.com>:

**Comment by acgotaku** [comment]
YAAW连不上应该是你自己的问题 了。。。

**Comment by chihaya-A** [comment]
注意下115連接地址，如果是 https，aria2 rpc 也要支援 https，改回 http 就正常了。

PS: 最近改版好像會自動導向 https

**Comment by gz0007** [comment]
哎，115的续费太贵了，我已回归tr慢慢拉资源

2017年7月2日 23:36，"chihaya-A" <notifications@github.com>写道：

**Comment by besta9188** [comment]
确实如此，多谢了

发送自 Windows 10 版邮件应用

发件人: chihaya-A
发送时间: 2017年7月2日 23:36
收件人: acgotaku/115
抄送: besta9188; Author
主题: Re: [acgotaku/115] 插件无法连接局域网内的aria2 (#74)

注意下115連接地址，如果是 https，aria2 rpc 也要支援 https，改回 http 就正常了。
PS: 最近改版好像會自動導向 https

**Comment by scetus** [comment]
我也遇到同样的问题了。所有设置都没有改，突然就没法连上aria2的服务了。

我的是小米路由2 安装aria2，之前使用都是正常的。突然就连不上了，直接局域网访问aria2是正常的，就是115插件连不上，提示服务未打开。

确认不是https的问题，因为设置里头确认是关闭的。

**Comment by acgotaku** [comment]
@scetus 是插件里面点击设置里面 的测试按钮 无法连接？

**Comment by scetus** [comment]
@acgotaku 点击测试是无法连接（就是不显示aria2 版本号），点击用aria2下载提示连接不上服务（就是红色的叉叉那个）。

**Comment by linchiai** [comment]
我也遇到了，明明前一天運作正常，忽然就無法連接，怪的是桌機連不上，但筆電一樣的設定卻可以成功

**Comment by scetus** [comment]
查了一下网上的资料，有这样的操作提示

输入：http://192.168.31.1:6800/jsonrpc?jsoncallback=1
返回：1({"id":null,"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid Request."}})

**Comment by scetus** [comment]
今天突然恢复了……
