### ISSUE TITLE
請問aria2 下載115 如何使用多線程

### ISSUE THREAD

**Issue by kid2323** [acgotaku/115#76]
如題 系統是xp 瀏覽器用火狐
用你做的插件 下載115 都是單線程(連接數)
部分檔案 變慢時100k~300k 左右
暫停再開也沒用 請問如何設定成多線程

**Comment by acgotaku** [comment]
貌似115后端限制了 多线程  所以前端更改也没有效果

**Comment by adam1x** [comment]
是否可以考虑同时从4个CDN（“传输线路”）多源下载？

**Comment by netfan** [comment]
由于115后端服务监控限制，设置多个CDN没啥用处，老实用单线程下载吧
