### ISSUE TITLE
RPC导出下载那个按钮按了没反应了

### ISSUE THREAD

**Issue by zlard** [acgotaku/115#77]
之前都是正常的 今天突然出现的问题

**Comment by insomniacdoll** [comment]
我这里一样，换了浏览器也是按钮失效。

**Comment by luanxinjiu** [comment]
RPC和到处 点击后 选中文件的勾自动会掉 插件设置按钮倒是有效

**Comment by zlard** [comment]
是的 一样 RPC和导出无效 设置按钮是有用的

**Comment by leodu0926** [comment]
同问，导出和RPC下载无效，设置是有用的

**Comment by droid-Q** [comment]
@zlard @insomniacdoll @luanxinjiu @leodu0926 可以试下我的临时修改版，https://pan.baidu.com/s/1i5MMIJ7

**Comment by luanxinjiu** [comment]
太给力了！PS：你放按钮的地方好喜感2333

**Comment by droid-Q** [comment]
@luanxinjiu 随便找地方放的。只要不lost selected就可以了。

**Comment by luanxinjiu** [comment]
@droid-Q 非常感谢 你是救星

**Comment by leodu0926** [comment]
@droid-Q 太感谢了，冒昧问一下，具体出了什么问题呢？

**Comment by droid-Q** [comment]
@leodu0926 应该是115又改了前台代码，原来的区域点击会失去selected list。

**Comment by leodu0926** [comment]
@droid-Q 谢谢

**Comment by leodu0926** [comment]
@droid-Q 尝试了一下，还是有问题，RPC下载出错，说没有链接上aria2，但是我直接在aria2c上添加下载没问题

**Comment by droid-Q** [comment]
@leodu0926 这个问题的确存在，但其实已经添加成功了，我这边测试是没什么大问题。等原作者更新吧。

**Comment by leodu0926** [comment]
@droid-Q 我这边查看了，还是没有添加成功。还是谢谢啦，等原作者更新吧

**Comment by BrianLu765** [comment]
上来一看才知道出问题的不止我一个，感谢@droid-Q的分享

**Comment by yanzai** [comment]
果真是，当前文件夹路径那一行，点击空白处会导致选择项清空，我现在前面打勾了之后，手动在控制台触发一下点击事件，哈哈：
设置：$('#js_top_bar_box > div:nth-child(3)').click()
导出：$('#js_top_bar_box > div:nth-child(4)').click()
RPC下载：$('#js_top_bar_box > div:nth-child(5)').click()

**Comment by leodu0926** [comment]
@droid-Q 我犯了个很傻的错误，刚刚修复了，你的修改版本完全正常，很好用。非常感谢

**Comment by acgotaku** [comment]
还有这么多人用。。。 我好欣慰啊

**Comment by luanxinjiu** [comment]
唯一有效的特殊下载渠道，感谢秋水大神。

**Comment by acgotaku** [comment]
更新了！！！

**Comment by zlard** [comment]
感谢大神!  XD

**Comment by luanxinjiu** [comment]
感谢！辛苦了！

**Comment by kid2323** [comment]
秋水大神 火狐版好像沒更新

**Comment by acgotaku** [comment]
@kid2323 火狐不更新了。。。 你凑合着用Chrome吧

**Comment by kid2323** [comment]
chrome 那登錄腳本好幾個月都用不了 不知道是什麼問題
帳號密碼欄位 就是看不到 已經更新到最新版 也重下好幾次
就是沒用 我現在只能用火狐版登錄

**Comment by kid2323** [comment]
droid-Q 大神 請問你修改的是火狐版的嗎

**Comment by luanxinjiu** [comment]
@kid2323 现在的火狐还能用吗 卡出翔了- -
