### ISSUE TITLE
115布局更新了

### ISSUE THREAD

**Issue by zwl2012** [acgotaku/115#8]
115管理页面于04月03日更新，致您的插件配置页面无法被正常显示及触发，但导出任务功能可正常使用。希望能够更新，感谢您的插件。谢谢您！

**Comment by iwfq** [comment]
可是我的能显示按钮，也能导出，但是下载后，控制台却显示error下载失败。我复制下载地址，用download them all也下载失败，如果用浏览器单线程却能下载好。我尝试ARIA2线程数改1，也是失败。。。

**Comment by acgotaku** [comment]
哭！ 我最近事情好多  115又更新 QAQ

**Comment by acgotaku** [comment]
@zwl2012  多刷新几次页面就出来了。。。

@iwfq 下载失败具体的输出是怎样的？

**Comment by iwfq** [comment]
@acgotaku 我是openwrt上弄的aria2，死活生成不了日志。。。我在配置文件里添加了两行:
log=/var/log/aria2.log
log-level=warn
但是重启aria2之后，这两行又没了。。。

后来我试了用命令行来添加115任务，提示这些：

root@Cisco-Nexus7000:~# aria2c -c -s10 -k1M -x10 -o "iconpackager5.0a_patch.rar"
 --header "User-Agent: Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, l
ike Gecko) Chrome/31.0.1650.63 Safari/537.36 115Browser/5.1.3"  --header "Refere
r: http://115.com/"  "https://vipcdntel.115.com/down_group13/M00/47/28/d5NqqEyOV
JsAAAAAAoyYETbF3Uk9656832/iconpackager5.0a_patch.rar?k=RjDBkeQPOOXPVwCa0VTFIw&t=
1428203509&u=vip-463423460-5577467-ewwyqc83ygzg6zl6e&s=104857600&file=iconpackag
er5.0a_patch.rar"

04/05 10:43:08 [ERROR] CUID#6 - Download aborted. URI=https://vipcdntel.115.com/down_group13/M00/47/28/d5NqqEyOVJsAAAAAAoyYETbF3Uk9656832/iconpackager5.0a_patch.rar?k=RjDBkeQPOOXPVwCa0VTFIw&t=1428203509&u=vip-463423460-5577467-ewwyqc83ygzg6zl6e&s=104857600&file=iconpackager5.0a_patch.rar
Exception: [AbstractCommand.cc:350] errorCode=1 URI=https://vipcdntel.115.com/down_group13/M00/47/28/d5NqqEyOVJsAAAAAAoyYETbF3Uk9656832/iconpackager5.0a_patch.rar?k=RjDBkeQPOOXPVwCa0VTFIw&t=1428203509&u=vip-463423460-5577467-ewwyqc83ygzg6zl6e&s=104857600&file=iconpackager5.0a_patch.rar
  -> [SocketCore.cc:875] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate

04/05 10:43:08 [NOTICE] Download GID#ebd3950985243de3 not complete: /root/iconpackager5.0a_patch.rar

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
ebd395|ERR |       0B/s|/root/iconpackager5.0a_patch.rar

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
root@Cisco-Nexus7000:~#

**Comment by acgotaku** [comment]
@iwfq  Cisco-Nexus7000  这设备 吓尿。。。

这应该是网络问题导致的吧？  SSL/TLS handshake failure: unable to get local issuer certificate

**Comment by iwfq** [comment]
@acgotaku 哈哈，那个名字只是自己改的。
我前几段时间有用过RevokeChinaCerts自动吊销流氓证书。
但是这是我在路由上直接命令行下载也出现那个错误，会不会也跟我PC上的证书有关？
如果有的话，我去试试还原吊销过的证书看看。。。

**Comment by acgotaku** [comment]
@iwfq 你是不是也用了 https  everywhere... 我获取的下载地址都是 http的

**Comment by iwfq** [comment]
@acgotaku  我火狐的确用了https everywhere，但是并没有115.com的规则，而且我也用Chrome，没有https everywhere，也一样的。。。555~~

**Comment by acgotaku** [comment]
@iwfq 那为啥获取到的是 https的下载地址 。。。 你禁用https插件试试

**Comment by iwfq** [comment]
@acgotaku 哈哈哈，太谢谢了，你的提示让我找到了原因，在115的‘帐号设置→网盘设置“里，有一个 'SSL加密下载'，那个功能关了就可以了。

**Comment by acgotaku** [comment]
@iwfq 原来如此～
