### ISSUE TITLE
百度网盘web版无法使用

### ISSUE THREAD

**Issue by C-ReCaLl** [acgotaku/115#80]
之前百度网盘是可以使用导出下载的，但是最近百度网盘web版改成勾选文件后出来一大堆菜单项，把导出下载的插件直接挤掉了。请问这种问题如何解决？

**Comment by acgotaku** [comment]
???大哥 这里是115 啊。。。 你发issue的时候能不能看看啊？？？

**Comment by C-ReCaLl** [comment]
我最初是用的Chrome插件名字叫「网盘助手」开发者是您，然后后来不知道什么原因停用了。我就通过您id搜索开发者搜到了这个名叫「115下载助手」的插件，惊奇的发现百度网盘也能用，一直到最近百度网盘也不能用了。问题如上。才想到来找您求助一下。

**Comment by acgotaku** [comment]
@C-ReCaLl 最新版本好好的啊 你确定自己更新了没？

**Comment by C-ReCaLl** [comment]
@acgotaku 是最新版本。版本号0.2.3

**Comment by acgotaku** [comment]
百度最新版本都 0.9.7 了。。。 大哥

**Comment by C-ReCaLl** [comment]
哦，我说的是115下载助手这个。。。

**Comment by acgotaku** [comment]
那你这个标题是几个意思。。。

**Comment by C-ReCaLl** [comment]
是。我是想用百度那个。可是我这个停到0.8.5就不更新了。点详细信息就404.

**Comment by acgotaku** [comment]
你能不能好好表达。。。到底啥出问题了？？？

**Comment by C-ReCaLl** [comment]
就是百度网盘现在导出下载用不了。选定文件后导出下载的按钮就消失了。然后我「网盘助手」的扩展程序版本号是0.8.5也没有自动更新成您说的0.9.7

**Comment by acgotaku** [comment]
那你看项目的说明 手动安装

**Comment by C-ReCaLl** [comment]
已经可以正常使用，感谢您的回复。
