### ISSUE TITLE
插件的按钮有时刷不出

### ISSUE THREAD

**Issue by NatsuH** [acgotaku/115#82]
console中有输出错误：

> 115.js:632 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://115.com" from accessing a cross-origin frame.
>     at chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/115.js:632:55
> (anonymous) @ 115.js:632

在拓展管理中开启收集错误之后得到的报告是

> Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://115.com" from accessing a frame with origin "http://115.com". The frame requesting access set "document.domain" to "115.com", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.

浏览器的Chromium内核版本号是61.0.3163.100

狂按F5之后有很小的概率刷出来，这时候console中的错误就变成了：

> Error in event handler for (unknown): SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://115.com" from accessing a cross-origin frame.
>     at chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/115.js:617:67

然后有两个错觉……
一个是我隐身模式只开Tampermonkey+115下载助手的话刷出来的概率会高一点（可能是脸忽然变白……）（更新：关了某划词拓展之后概率也觉得变高了，这个大概不是错觉）
另外一个是https下刷出来的概率可能也会高一点（大概是错觉……
而且顺便提一下 同环境https下助手无法连接到aria2，也检测不到版本号，可能是我姿势问题…？）

**Comment by acgotaku** [comment]
是因为更新到最新版的问题？

**Comment by NatsuH** [comment]
@acgotaku （手动泪扇脸）实际上因为之前单线程差不多也能跑满没什么用AIRA2来下载的需求（IDM），一直没有来找相关的拓展啊之类的，这两天才开始用，是新用户。所以不好意思我不知道之前版本的情况_(:з」∠)_

（不过真的大家都没提这个情况诶难不成是我脸黑……不过也和上面说的一样，隐身模式排查下是如上的结果orzzz）

**Comment by acgotaku** [comment]
因为要是插件有问题 至少会有10个以上的人来反馈的。。。 各例的情况基本上都是用户某些设置不当 或者插件冲突之类的

**Comment by NatsuH** [comment]
@acgotaku 感谢菊苣回复！在虚拟机里跑了一下全新安装没有动过任何的chrome61就基本看不见这个情况了orz（图省心即便是用不大刀阔斧修改的[套壳浏览器](http://www.centbrowser.cn)也不行啊哎……）
那就只剩下后面的那个小问题了（我好烦啊…），https访问115的情况下无法连接到aria2这个该怎么办呢（我这里的http环境太痛苦了）

**Comment by acgotaku** [comment]
https目前还没有支持 不过支持https本身不是很难 但我想重构之后再支持。。。

**Comment by acgotaku** [comment]
https的时候 导出是可以用的

**Comment by NatsuH** [comment]
@acgotaku 好的，我了解啦，那我就先用导出等您有空更新好了。感谢您的耐心回复，辛苦啦┐「ε:)_

**Comment by acgotaku** [comment]
主要是现在代码太丑 想重构之后再加新功能

**Comment by NatsuH** [comment]
@acgotaku 原来如此，那我就安心等待菊苣的新版本啦

**Comment by acgotaku** [comment]
@NatsuH 新版本已更新
