### ISSUE TITLE
为什么115插件设置不了 现实没有打开aria2

### ISSUE THREAD

**Issue by 584555463** [acgotaku/115#83]
![tim 20171011022206](https://user-images.githubusercontent.com/32567195/31403809-d88aaf74-ae2c-11e7-9bfc-7c10859d4d12.png)
![tim 20171011022151](https://user-images.githubusercontent.com/32567195/31403811-d9db33c6-ae2c-11e7-8779-7b41a1aa6dfb.png)

**Comment by luanxinjiu** [comment]
我认为你应该把【RPC访问设置】的勾打上
