### ISSUE TITLE
连不上aria2

### ISSUE THREAD

**Issue by gg159753** [acgotaku/115#84]
百度网盘版本可以挂上aria2  115挂不上  提示aria2是否已开启

**Comment by liangxyz** [comment]
一样的问题，发现也是连接不上了，同时YAAW for chrome工作正常。浏览器是centbroswer 3.0.4.27，win10 15063.608

**Comment by acgotaku** [comment]
我测试是可以的啊？ URL格式不对？

**Comment by liangxyz** [comment]
经测试，是因为地址栏最右边有一个安全提示，提示有未经允许的脚本要运行，我点击允许运行就正常了
