### ISSUE TITLE
新版115已经不可用

### ISSUE THREAD

**Issue by kltt22** [acgotaku/115#85]
115改版了，设置和导出按钮均看不到了

**Comment by acgotaku** [comment]
![screenshot from 2017-11-16 23-46-34](https://user-images.githubusercontent.com/1191834/32897246-69ef5b82-cb28-11e7-82b0-a254102e70c9.png)

貌似还是能看到。。。

**Comment by kltt22** [comment]
重启电脑后，可以了。感谢回复
