### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by jieyujing** [acgotaku/115#86]
> [DL:186KiB][#8ba47f 36MiB/9.6GiB(0%)][#377eb6 6.5MiB/17GiB(0%)][#582b30 2.4MiB/225MiB(1%)][#0a04f  11/22 09:28:49 [ERROR] CUID#207 - Download aborted. URI=https://fscdntel-vip.115.com/files/c305/1/PAOMCM4hBTbTj3AcOn-sv-JZ-A3jeDQj0nXTKKrJ/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9.rar?t=1511318703&u=vip-236101051-2959992-cudbj1zlklf8tdmme&s=13107200&k=8dX1zjw_LFgQvgGeG9bX7A                  Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://fscdntel-vip.115.com/files/c305/1/PAOMCM4hBTbTj3AcOn-sv-JZ-A3jeDQj0nXTKKrJ/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9.rar?t=1511318703&u=vip-236101051-2959992-cudbj1zlklf8tdmme&s=13107200&k=8dX1zjw_LFgQvgGeG9bX7A  

`

账号为年卡vip，aria2无法满速，浏览器可以跑满。

**Comment by acgotaku** [comment]
我不是VIP 所以我也不能给你答案。。。
