### ISSUE TITLE
360急速等内核版本较低的浏览器经常刷不出导出按钮

### ISSUE THREAD

**Issue by enuma0** [acgotaku/115#88]
插件版本：0.2.4
浏览器版本：
![image](https://user-images.githubusercontent.com/3970620/33229012-44f70192-d201-11e7-8968-26d2dba358e8.png)
基本上可以百分百可以复现问题，大概刷新10次左右有几率可以刷出按钮，看控制台的输出应该是脚本加载失败了，不过在原版chrome或者centbrowser等内核较新的浏览器就不会出现这个问题。
![tim 20171125165122](https://user-images.githubusercontent.com/3970620/33229005-2aa2a3aa-d201-11e7-8ef1-62819cfd1e3d.png)

**Comment by enuma0** [comment]
补充一下，centbrowser似乎也不行了，报错跟急速一样。
浏览器版本：
![image](https://user-images.githubusercontent.com/3970620/33229072-b1bcc19e-d202-11e7-85f5-0d1263dc0f37.png)

**Comment by acgotaku** [comment]
那你试试开发板 到底是哪里出的问题？
参考： https://github.com/acgotaku/BaiduExporter/blob/master/.github/CONTRIBUTING.md

**Comment by enuma0** [comment]
![image](https://user-images.githubusercontent.com/3970620/33238040-2e3c6a96-d2bf-11e7-9fa6-fb9c26d3a295.png)
失败了= =！

**Comment by acgotaku** [comment]
@enuma0 windows的开发环境确实不太好运行 我做一份给你吧 
[115.zip](https://github.com/acgotaku/115/files/1503928/115.zip)

**Comment by enuma0** [comment]
开发板似乎还是不行，我尽可能的排查一下我的网络环境吧。
![image](https://user-images.githubusercontent.com/3970620/33240643-4ad23e30-d2f4-11e7-9f1f-ce7d84ba0a8d.png)

**Comment by UnderCooled** [comment]
我这 chrome 62.0.3202.94 ，也开始遇到这个问题了。

先访问 tab=offline&mode=wangpan 而后点击 云下载->全部 标签。

错误：

![image](https://user-images.githubusercontent.com/161503/33241379-5bf72170-d2ff-11e7-8d2f-9854e4f51a56.png)

![image](https://user-images.githubusercontent.com/161503/33241383-6f5a52dc-d2ff-11e7-9790-18b2a6365bba.png)

F5 刷新 tab=download&mode=wangpan 的页面，却又能成功插入导出按钮了。

**Comment by acgotaku** [comment]
@UnderCooled 大哥 那个任务页面 怎么导出啊。。。放按钮的地方都没有。。。
点击全部文件才可以，默认iframe切换不会出发初始化。所以需要刷新

**Comment by acgotaku** [comment]
@enuma0 http://115.com/?cid=0&offset=0&mode=wangpan  确认下 是不是这个页面

**Comment by UnderCooled** [comment]
> @UnderCooled 大哥 那个任务页面 怎么导出啊。。。放按钮的地方都没有。。。
点击全部文件才可以，默认iframe切换不会出发初始化。所以需要刷新

对啊，我说的就是点到全部文件的时候也不会初始化，如果你一开始是在离线那个页面的话。

就是你点开一个新的 TAB ，然后先访问离线下载那个页面，然后再点击云下载的那个全部文件，就不会初始化按钮的了，除非 F5 刷一次。本来之前一直可以这样的。

**Comment by acgotaku** [comment]
@UnderCooled 现在加载机制变了 这个你就费心多点一下吧。。。

**Comment by enuma0** [comment]
@acgotaku 点击后还是有几率可以刷出来
