### ISSUE TITLE
打包程序错误

### ISSUE THREAD

**Issue by chibuhu** [acgotaku/115#89]
115打包提示无法加载扩展程序图标“img/logo16.png”。

**Comment by acgotaku** [comment]
有chrome安装 你非要打包？？

**Comment by chibuhu** [comment]
不好意思，没看到有crx，我再找找，谢谢

**Comment by acgotaku** [comment]
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf
