### ISSUE TITLE
临时解决方案

### ISSUE THREAD

**Issue by zwl2012** [acgotaku/115#9]
因为115布局更新而不能正常设置aria2 rpc参数的朋友，可以下载雪月兄的源码包解压然后进chrome/js将115.js
146行内容修改为
    setting_div.appendTo('.tup-logout');
后保存。
然后将原插件删去或者禁用。
开启chrome开发者模式，点击加载正在开发的扩展程序按钮 选择刚刚解包出来的文件夹加载即可正常使用。
插件设置按钮即可正常显示在新版布局的个人信息页面。最后感谢开发雪月兄的插件。谢谢！

**Comment by acgotaku** [comment]
@zwl2012 我来更新下插件不就完事了 ==

**Comment by acgotaku** [comment]
@zwl2012 更新了～ 我开始理解错了 是设置菜单啊 抱歉抱歉
