### ISSUE TITLE
新版本的最终下载路径中总是会包含所选文件的父路径

### ISSUE THREAD

**Issue by tony1016** [acgotaku/115#90]
之前的版本不是这样的啊。现在的新版本，选择一个文件夹下载，下载路径中会包含父目录。

**Comment by acgotaku** [comment]
例如？

**Comment by tony1016** [comment]
例如我在115上有个片子的目录是/TV Show/Pegga Pig，我现在想下载Pegga
Pig，于是勾选它，在下载路径中设置为/mnt/nvidia/Download，最终的下载就变成了/mnt/nvidia/Download/TV
Show/Pegga Pig ，最终的目录里多了一个TV Show

2017年12月25日 下午9:54，"雪月秋水" <notifications@github.com>写道：

**Comment by acgotaku** [comment]
为什么我的测试没有问题。。。

你可以录一个短视频么？

**Comment by tony1016** [comment]
Let me try

2017年12月30日 下午3:35，"雪月秋水" <notifications@github.com>写道：

**Comment by zhanglianbo35** [comment]
我也有这样的issue，它会把上层所有的文件夹都会同步下来。

**Comment by tony1016** [comment]
嗯，确认问题出现在下载目标是个文件夹的时候

**Comment by acgotaku** [comment]
确实是的 我修复下

**Comment by acgotaku** [comment]
0.2.7应该修复了这个问题 你们可以更新看看

**Comment by tony1016** [comment]
确认修复
