### ISSUE TITLE
請問有沒有辦法解除種子離線下載50g的限制

### ISSUE THREAD

**Issue by kid2323** [acgotaku/115#91]
永V可添加50g 以上  現在極限是多少忘了
最早之前是無限制
一般年v 只能離線50g以下 或用磁力碰碰運氣 
請問大神有沒有方法解決~

**Comment by acgotaku** [comment]
这个有点难啊 我没VIP的测试帐号 不知道API

**Comment by kid2323** [comment]
大神可否提供你的 115帳號 或 qq 號 我先幫你充一年vip

**Comment by acgotaku** [comment]
你给我充了 我就失去了普通会员的测试帐号了。。。

**Comment by kid2323** [comment]
你可以再辦一個帳號嗎

**Comment by acgotaku** [comment]
貌似现在都需要实名了。。。 有点难

**Comment by kid2323** [comment]
我幫你買個空白的可以嗎

**Comment by acgotaku** [comment]
这么热情。。。 买了我也不一定能确保这个功能可以加上

**Comment by kid2323** [comment]
至少有機會 我沒有認識的永v 很多檔案都還沒下完就死檔了
每次用磁力這樣搞也不是辦法 要想官方改回來我看是不可能了
每次一改都是福利越來越縮水

**Comment by kid2323** [comment]
我剛才發現一個問題 空白的還要綁手機 = ="
大神方便提供qq告知嗎 
還是綁我的手機就好

**Comment by kid2323** [comment]
大神 我空白帳號買好了
可以給個qq 我好給你帳密

**Comment by acgotaku** [comment]
好吧。。。 发我邮箱吧。。。  acgotaku311 gmail com

**Comment by kid2323** [comment]
已看到 信箱地址可以刪了

**Comment by kid2323** [comment]
大神已發另一個 你試試看

**Comment by acgotaku** [comment]
![screenshot from 2018-01-18 23-13-05](https://user-images.githubusercontent.com/1191834/35102071-284da31a-fca5-11e7-8790-a181152ff7a4.png)

我添加的倆磁性链接 貌似都可以？

**Comment by kid2323** [comment]
我有些也是這樣 不過沒多久就失敗了
0% 不一定可以離線  0%以上尚有機會
有些會直接失敗 不知道它的審核機制是什麼
正常資源也常遇到 有可能繞過他的審核嗎

**Comment by acgotaku** [comment]
我觉得这个限制应该是服务器限制 前端很难做到各种hack。。。

**Comment by liuyangno1** [comment]
可以考虑先将种子文件转换为磁链，然后添加。实测可行。
