### ISSUE TITLE
有时不能加载成功

### ISSUE THREAD

**Issue by overfirmament** [acgotaku/115#94]
http/https都能使用extension
不过有时候刷新一下就能没弹出"加载成功"的信息和没能出现"导出下载"的按钮 要疯狂刷新数次才能

无法加载时console显示:
chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/start.js:1 Uncaught DOMException: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "https://115.com" from accessing a cross-origin frame.
    at Object.n.1 (chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/start.js:1:713)
    at o (chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/start.js:1:254)
    at e (chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/start.js:1:420)
    at chrome-extension://ojafklbojgenkohhdgdjeaepnbjffdjf/js/start.js:1:437

**Comment by acgotaku** [comment]
有时候插件先加载了 多刷新几下就好（

**Comment by IsoaSFlus** [comment]
我这也出现了类似的情况，每次要刷新一次才能看到导出按钮，好难受。。。

**Comment by overfirmament** [comment]
关键是有时候刷新多了就直接502不能上了 感觉115暂时ban掉你那样。。。

**Comment by overfirmament** [comment]
"content_scripts": [ {
     "js": ["js/start.js" ],
	 **"all_frames": true,
	 "run_at": "document_end",**
      "matches": ["*://*.115.com/*"]

manifest.json好像加了這兩句就好了很多...差不多每次刷新都可以了
