### ISSUE TITLE
无法加载扩展程序图标

### ISSUE THREAD

**Issue by lll113** [acgotaku/115#95]
你好，已经根据论坛上的帖子下载了您的插件，并按流程安装，但在打包刚解压出来的扩展程序的时候弹出“无法加载扩展程序图标“img/logo16.png”的错误，秘钥是生成出来了，但那个chrome.crx文件却生成不了，已经尝试过几台电脑重新下载安装都是一样的错误，不知道是什么问题？谢谢回复。

**Comment by acgotaku** [comment]
https://chrome.google.com/webstore/detail/115exporter/ojafklbojgenkohhdgdjeaepnbjffdjf

不是可以直接用么。。。

**Comment by lll113** [comment]
谢谢回复，但我们这边打不开您的链接，不知道是否能够发个给我邮箱呢？79124606@qq.com。再次谢谢。

**Comment by acgotaku** [comment]
https://github.com/acgotaku/115/releases/tag/v0.2.6

去这里下载 CRX文件
