### ISSUE TITLE
导出为aria2文件下载后文件路径带上了引号

### ISSUE THREAD

**Issue by IsoaSFlus** [acgotaku/115#96]
![screenshot_20180125_143301](https://user-images.githubusercontent.com/5125031/35374175-bd5343f2-01dc-11e8-8cfb-f86dc1538766.png)
![screenshot_20180125_143316](https://user-images.githubusercontent.com/5125031/35374177-befffb14-01dc-11e8-9dec-ba3541600d4b.png)

**Comment by acgotaku** [comment]
0.2.6版本修复了 文本导出带引号的BUG
